<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeInterface;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Payload;

/**
 * Audit Log: 1 endpoint.
 *
 * Reach it with $sendseven->auditLog().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Audit%20Log
 */
final readonly class AuditLog
{
    public function __construct(private Connector $connector) {}

    /**
     * List Audit Log.
     *
     * List API audit log entries for the current tenant.
     *
     * Returns paginated, sanitized records of API calls made against this tenant. Sorted by most
     * recent first.
     *
     * Scopes: settings:admin.
     *
     * @param  ?string  $method  Filter by HTTP method (GET, POST, etc.)
     * @param  ?int  $statusCode  Filter by status code
     * @param  ?string  $path  Filter by path (partial match)
     * @param  DateTimeInterface|string|null  $startDate  Filter from date (ISO 8601)
     * @param  DateTimeInterface|string|null  $endDate  Filter to date (ISO 8601)
     * @param  ?int  $page  Page number
     * @param  ?int  $pageSize  Items per page
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Audit%20Log/list_audit_log_api_v1_audit_log_get
     */
    public function list(?string $method = null, ?int $statusCode = null, ?string $path = null, DateTimeInterface|string|null $startDate = null, DateTimeInterface|string|null $endDate = null, ?int $page = null, ?int $pageSize = null): void
    {
        $this->connector->send(new Request(
            Method::Get,
            '/audit-log',
            query: Payload::query(['method' => $method, 'status_code' => $statusCode, 'path' => $path, 'start_date' => $startDate, 'end_date' => $endDate, 'page' => $page, 'page_size' => $pageSize]),
        ));
    }
}
