<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\Archive;
use Reshapify\SendSeven\Data\Channel;
use Reshapify\SendSeven\Data\ChannelCapabilities;
use Reshapify\SendSeven\Data\ChannelCommentCapabilities;
use Reshapify\SendSeven\Data\ChannelCommentCapability;
use Reshapify\SendSeven\Data\ChannelHealth;
use Reshapify\SendSeven\Data\ChannelProfile;
use Reshapify\SendSeven\Data\ChannelProfileUpdate;
use Reshapify\SendSeven\Data\ChannelTypes;
use Reshapify\SendSeven\Data\FacebookPagePostItem;
use Reshapify\SendSeven\Data\InstagramMediaItem;
use Reshapify\SendSeven\Data\ProfilePhotoUpload;
use Reshapify\SendSeven\Data\RcsCapability;
use Reshapify\SendSeven\Data\WebhookRefresh;
use Reshapify\SendSeven\Data\WhatsAppUsername;
use Reshapify\SendSeven\Data\WhatsAppUsernameDelete;
use Reshapify\SendSeven\Data\WhatsAppUsernameUpdate;
use Reshapify\SendSeven\Enums\ChannelType;
use Reshapify\SendSeven\Enums\WhatsAppVertical;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\FilePart;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Pagination\Page;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * Channels: 21 endpoints.
 *
 * Reach it with $sendseven->channels().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Channels
 */
final readonly class Channels
{
    public function __construct(private Connector $connector) {}

    /**
     * List Channels.
     *
     * List all active (non-archived) channels for the tenant.
     *
     * Any authenticated team member can list channels (used for app initialization).
     *
     * Security model (inverted May 2026): Non-admin/non-owner callers ALWAYS see only the channels
     * reachable through their accessible Custom Inboxes -- regardless of the for_compose query param.
     * Previously this filter was opt-in via for_compose=true, which meant a restricted user could drop
     * the param and see every channel in the tenant (UX leak / info disclosure -- they still couldn't
     * send, but channel names appeared in any listing/picker). The filter is now mandatory for
     * non-admins.
     *
     * Scopes: channels:read.
     *
     * @param  ?string  $channelType  Optional: filter results to a single channel_type (e.g. 'whatsapp')
     * @return list<Channel>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/list_channels_api_v1_channels_get
     */
    public function list(?bool $forCompose = null, ?string $channelType = null): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels',
            query: Payload::query(['for_compose' => $forCompose, 'channel_type' => $channelType]),
        ));

        return Hydrate::list($response->data(), Channel::fromArray(...));
    }

    /**
     * Create Channel.
     *
     * Connect a new messaging channel
     *
     * RCS channels cannot be created here: SendSeven sets up and manages RCS agents (403
     * rcs_managed_by_sendseven).
     *
     * Scopes: channels:create.
     *
     * @param  array<string, mixed>|null  $config
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/create_channel_api_v1_channels_post
     */
    public function create(ChannelType|string $channelType, string $identifier, string $name, ?array $config = null, ?string $idempotencyKey = null): Channel
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/channels',
            body: Payload::body(['channel_type' => $channelType, 'identifier' => $identifier, 'name' => $name, 'config' => $config]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return Channel::fromArray($response->data());
    }

    /**
     * Get Comment Capabilities.
     *
     * Can these channels receive comments? ("Comments -> Private Reply" beta)
     *
     * Reports, for every non-archived Instagram and Facebook Messenger channel, whether comment
     * webhooks would actually arrive today — so the UI can show a "reconnect to enable comments"
     * prompt instead of offering a feature that would silently never fire.
     *
     * - Instagram needs the instagram_business_manage_comments permission, which is fixed at connect
     * time and can only be added by reconnecting. - Facebook Messenger needs the Page subscribed to
     * the feed webhook field. This is read LIVE from Facebook on every call, because the subscription
     * can change without any change to the channel.
     *
     * Scopes: channels:read.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_comment_capabilities_api_v1_channels_comment_capabilities_get
     */
    public function getCommentCapabilities(): ChannelCommentCapabilities
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/comment-capabilities',
        ));

        return ChannelCommentCapabilities::fromArray($response->data());
    }

    /**
     * Get Channel Health.
     *
     * Get health status of all channel integrations.
     *
     * Returns the connection status of all active channel integrations, highlighting any that have
     * errors that need attention.
     *
     * Currently supports: - Email integrations (Gmail, SMTP/IMAP, etc.) - Messaging channels
     * (Messenger / Instagram) whose access token was invalidated (Graph API code=190) and need
     * reconnecting. These appear with channel_type = the messaging type ("messenger", "instagram",
     * ...), connection_status = "disconnected", last_error = the disconnection_reason
     * ("token_invalidated"), and last_error_at = when the channel was disconnected.
     *
     * Scopes: channels:read.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_health_api_v1_channels_health_get
     */
    public function getHealth(): ChannelHealth
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/health',
        ));

        return ChannelHealth::fromArray($response->data());
    }

    /**
     * Get Channel Types.
     *
     * Get available channel types.
     *
     * Returns a list of available (implemented) channel types, coming soon channel types, and detailed
     * info for all types.
     *
     * This endpoint is public (no auth required) as it's used during channel setup and onboarding
     * flows.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_types_api_v1_channels_types_get
     */
    public function getTypes(): ChannelTypes
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/types',
        ));

        return ChannelTypes::fromArray($response->data());
    }

    /**
     * Delete Channel.
     *
     * Archive (soft-delete) a channel.
     *
     * This preserves the channel record for billing history and audit purposes while: - Marking it as
     * archived (hidden from normal listings) - Clearing sensitive credentials from config - Recording
     * who archived it and when
     *
     * For WhatsApp channels, the phone number is also deregistered from Meta. For Messenger/Instagram
     * channels, the Facebook Page is unsubscribed from our app so the asset can be cleanly
     * re-connected later.
     *
     * Scopes: channels:delete.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/delete_channel_api_v1_channels__channel_id__delete
     */
    public function delete(string $channelId): Archive
    {
        $response = $this->connector->send(new Request(
            Method::Delete,
            '/channels/'.Payload::segment($channelId),
        ));

        return Archive::fromArray($response->data());
    }

    /**
     * Get Channel.
     *
     * Get a specific channel
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_api_v1_channels__channel_id__get
     */
    public function get(string $channelId): Channel
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId),
        ));

        return Channel::fromArray($response->data());
    }

    /**
     * Update Channel.
     *
     * Update a channel configuration
     *
     * On an RCS channel only name and is_active may change here; an identifier or config change
     * answers 403 rcs_managed_by_sendseven (SendSeven manages RCS agents and their credentials).
     *
     * Scopes: channels:update.
     *
     * @param  array<string, mixed>|null  $config
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/update_channel_api_v1_channels__channel_id__put
     */
    public function update(string $channelId, ?array $config = null, ?string $identifier = null, ?bool $isActive = null, ?string $name = null): Channel
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/channels/'.Payload::segment($channelId),
            body: Payload::body(['config' => $config, 'identifier' => $identifier, 'is_active' => $isActive, 'name' => $name]),
        ));

        return Channel::fromArray($response->data());
    }

    /**
     * Get Channel Capabilities.
     *
     * Get the feature capabilities matrix for a specific channel.
     *
     * Returns what message types and interactive elements are supported by the channel's messaging
     * platform.
     *
     * Feature Categories: - Basic message types: text, images, videos, audio, voice (PTT), documents,
     * stickers - Rich content: location, contacts - Engagement: reactions - Interactive elements:
     * interactive_buttons, interactive_lists, carousels, quick_replies - Other: templates
     * (pre-approved message templates), proxy (proxy/passthrough support)
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_capabilities_api_v1_channels__channel_id__capabilities_get
     */
    public function getCapabilities(string $channelId): ChannelCapabilities
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/capabilities',
        ));

        return ChannelCapabilities::fromArray($response->data());
    }

    /**
     * Get Channel Comment Capability.
     *
     * Can THIS channel receive comments? ("Comments -> Private Reply" beta)
     *
     * Single-channel form of GET /channels/comment-capabilities — same fail-closed contract and the
     * same reason codes. A channel of a type that can never do comments returns comments_supported:
     * false with reason channel_type_not_supported rather than an error.
     *
     * Read-only: nothing is subscribed, changed or repaired.
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_comment_capability_api_v1_channels__channel_id__comment_capability_get
     */
    public function getCommentCapability(string $channelId): ChannelCommentCapability
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/comment-capability',
        ));

        return ChannelCommentCapability::fromArray($response->data());
    }

    /**
     * List Facebook Page Posts.
     *
     * List published posts for a Facebook Page (Messenger) channel.
     *
     * Used by the comment auto-reply rules UI and the comment_received flow-trigger config to let the
     * user pick specific posts to watch.
     *
     * Reads /{page_id}/published_posts rather than /feed: feed also returns posts made BY OTHERS on
     * the Page and scheduled/unpublished drafts, none of which a customer can meaningfully pick as "a
     * post of mine to auto-reply on".
     *
     * Scopes: channels:read.
     *
     * @param  ?string  $after  Meta Graph API pagination cursor (opaque).
     * @param  ?int  $limit  Number of items per page (1-50).
     * @return Page<FacebookPagePostItem>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/list_facebook_page_posts_api_v1_channels__channel_id__facebook_posts_get
     */
    public function listFacebookPagePosts(string $channelId, ?string $after = null, ?int $limit = null): Page
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/facebook/posts',
            query: Payload::query(['after' => $after, 'limit' => $limit]),
        ));

        return Hydrate::page($response->data(), FacebookPagePostItem::fromArray(...), null);
    }

    /**
     * Get Channel File Support.
     *
     * Get the supported file formats and size limits for a specific channel.
     *
     * Returns which file types (extensions) and categories (image, video, audio, document) are
     * supported by the channel, along with maximum file size per category.
     *
     * Useful for client-side validation before uploading/sending attachments.
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_file_support_api_v1_channels__channel_id__file_support_get
     */
    public function getFileSupport(string $channelId): void
    {
        $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/file-support',
        ));
    }

    /**
     * List Instagram Media.
     *
     * List media (posts, reels, carousels) for an Instagram channel.
     *
     * Used by the comment_received flow-trigger config UI to let the user pick specific posts to
     * monitor for comments.
     *
     * Pagination: - Cursor-based via Meta's after parameter. - limit defaults to 25, max 50 (Meta
     * enforces an upper bound around this). - Response includes pagination.next_cursor (null on the
     * last page).
     *
     * Scopes: channels:read.
     *
     * @param  ?string  $after  Meta Graph API pagination cursor (opaque).
     * @param  ?int  $limit  Number of items per page (1-50).
     * @return Page<InstagramMediaItem>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/list_instagram_media_api_v1_channels__channel_id__instagram_media_get
     */
    public function listInstagramMedia(string $channelId, ?string $after = null, ?int $limit = null): Page
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/instagram/media',
            query: Payload::query(['after' => $after, 'limit' => $limit]),
        ));

        return Hydrate::page($response->data(), InstagramMediaItem::fromArray(...), null);
    }

    /**
     * Get Channel Profile.
     *
     * Fetch channel profile from platform API (WhatsApp or Telegram).
     *
     * This endpoint fetches the current profile data directly from the messaging platform's API. No
     * data is stored locally.
     *
     * Supported Channels: - WhatsApp: Returns business profile (about, address, description, email,
     * profile picture, websites, vertical) - Telegram: Returns bot profile (name, username,
     * description, short description, commands, permissions)
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_channel_profile_api_v1_channels__channel_id__profile_get
     */
    public function getProfile(string $channelId): ChannelProfile
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/profile',
        ));

        return ChannelProfile::fromArray($response->data());
    }

    /**
     * Update Channel Profile.
     *
     * Update channel profile on platform API.
     *
     * This endpoint updates the profile data directly on the messaging platform's API. Only provided
     * fields are updated.
     *
     * Supported Channels:
     *
     * Scopes: channels:update.
     *
     * @param  ?string  $about  [WhatsApp] Short description shown in profile
     * @param  ?string  $address  [WhatsApp] Business address
     * @param  list<array<string, mixed>>|null  $commands  [Telegram] List of bot commands
     * @param  ?string  $description  Full description (max 512 chars)
     * @param  ?string  $email  [WhatsApp] Business contact email
     * @param  ?string  $name  [Telegram] Bot display name
     * @param  ?string  $shortDescription  [Telegram] Short description shown in chat list
     * @param  WhatsAppVertical|string|null  $vertical  [WhatsApp] Business category
     * @param  list<string>|null  $websites  [WhatsApp] List of website URLs (max 2)
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/update_channel_profile_api_v1_channels__channel_id__profile_put
     */
    public function updateProfile(string $channelId, ?string $about = null, ?string $address = null, ?array $commands = null, ?string $description = null, ?string $email = null, ?string $name = null, ?string $shortDescription = null, WhatsAppVertical|string|null $vertical = null, ?array $websites = null): ChannelProfileUpdate
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/channels/'.Payload::segment($channelId).'/profile',
            body: Payload::body(['about' => $about, 'address' => $address, 'commands' => $commands, 'description' => $description, 'email' => $email, 'name' => $name, 'short_description' => $shortDescription, 'vertical' => $vertical, 'websites' => $websites]),
        ));

        return ChannelProfileUpdate::fromArray($response->data());
    }

    /**
     * Upload Channel Profile Photo.
     *
     * Upload a profile photo for a WhatsApp channel.
     *
     * This endpoint uploads a new profile picture directly to the WhatsApp Business Account via Meta's
     * API.
     *
     * Supported Channels: WhatsApp only (Telegram uses @BotFather for profile photos)
     *
     * Scopes: channels:update.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/upload_channel_profile_photo_api_v1_channels__channel_id__profile_photo_post
     */
    public function uploadProfilePhoto(string $channelId, FilePart $file, ?string $idempotencyKey = null): ProfilePhotoUpload
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/channels/'.Payload::segment($channelId).'/profile/photo',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
            multipart: Payload::multipart(['file' => $file]),
        ));

        return ProfilePhotoUpload::fromArray($response->data());
    }

    /**
     * Check Rcs Capabilities.
     *
     * Check whether one number can receive RCS from this agent.
     *
     * Also requires the tenant's rcs_enabled feature flag (403 otherwise).
     *
     * Returns 200 with reachable: false for every kind of unreachable — this is an answer, not an
     * error. Google answers 404 whether the device has no RCS, has RCS switched off, sits on a carrier
     * the agent is not launched on, or belongs to a tester who has not accepted the invite, and it
     * cannot tell those apart, so neither can we.
     *
     * Scopes: channels:read.
     *
     * @param  string  $channelId  RCS channel id
     * @param  string  $msisdn  Number to probe
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/check_rcs_capabilities_api_v1_channels__channel_id__rcs_capabilities_get
     */
    public function checkRcsCapabilities(string $channelId, string $msisdn): RcsCapability
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/rcs/capabilities',
            query: Payload::query(['msisdn' => $msisdn]),
        ));

        return RcsCapability::fromArray($response->data());
    }

    /**
     * Refresh Channel Webhook.
     *
     * Re-register the webhook for a channel.
     *
     * This is useful when: - Webhook URL needs to be updated - Webhook registration failed initially -
     * You want to verify the webhook is correctly set
     *
     * Webhooks are always registered to point to production (api.sendseven.com) to ensure proper
     * message delivery and staging forwarding.
     *
     * Scopes: channels:update.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/refresh_channel_webhook_api_v1_channels__channel_id__refresh_webhook_post
     */
    public function refreshWebhook(string $channelId, ?string $idempotencyKey = null): WebhookRefresh
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/channels/'.Payload::segment($channelId).'/refresh-webhook',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return WebhookRefresh::fromArray($response->data());
    }

    /**
     * Delete Whatsapp Username.
     *
     * Release the WhatsApp business username held by this channel's number.
     *
     * WhatsApp does not return a released handle to the pool immediately, so someone else may not be
     * able to claim it right away — and neither can you. Treat this as destructive.
     *
     * Scopes: channels:write.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/delete_whatsapp_username_api_v1_channels__channel_id__whatsapp_username_delete
     */
    public function deleteWhatsAppUsername(string $channelId): WhatsAppUsernameDelete
    {
        $response = $this->connector->send(new Request(
            Method::Delete,
            '/channels/'.Payload::segment($channelId).'/whatsapp/username',
        ));

        return WhatsAppUsernameDelete::fromArray($response->data());
    }

    /**
     * Get Whatsapp Username.
     *
     * Get the WhatsApp business username claimed by this channel's phone number.
     *
     * A username lets customers reach the business through wa.me/<username> without knowing its phone
     * number. It belongs to the PHONE NUMBER, so each WhatsApp channel has at most one.
     *
     * Response: - username: the current handle, or null when none is claimed - status: approved (live)
     * or reserved (accepted, still propagating) - wa_me_url: short link to share with customers -
     * suggestions: available handles suggested by WhatsApp (best-effort — an empty list simply means
     * WhatsApp returned none)
     *
     * Scopes: channels:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/get_whatsapp_username_api_v1_channels__channel_id__whatsapp_username_get
     */
    public function getWhatsAppUsername(string $channelId): WhatsAppUsername
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/channels/'.Payload::segment($channelId).'/whatsapp/username',
        ));

        return WhatsAppUsername::fromArray($response->data());
    }

    /**
     * Set Whatsapp Username.
     *
     * Claim or change the WhatsApp business username for this channel's number.
     *
     * Format: 3-35 characters of lowercase letters, numbers, periods and underscores; at least one
     * letter; no leading/trailing period, no .., no www prefix, no domain-like suffix. Periods and
     * underscores are distinct.
     *
     * Transfers: if the handle is already held by another phone number in the same Meta business
     * portfolio, WhatsApp answers with error 147005. Repeat the request with force_transfer: true to
     * move it to this number.
     *
     * Scopes: channels:write.
     *
     * @param  string  $username  3-35 characters of lowercase letters, numbers, periods and underscores; must contain a letter, may not start/end with a period, contain '..', start with 'www' or end with a domain suffix
     * @param  ?bool  $forceTransfer  Only for retrying after error 147005: moves the username off another phone number in the same Meta portfolio
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Channels/set_whatsapp_username_api_v1_channels__channel_id__whatsapp_username_post
     */
    public function setWhatsAppUsername(string $channelId, string $username, ?bool $forceTransfer = null, ?string $idempotencyKey = null): WhatsAppUsernameUpdate
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/channels/'.Payload::segment($channelId).'/whatsapp/username',
            body: Payload::body(['username' => $username, 'force_transfer' => $forceTransfer]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return WhatsAppUsernameUpdate::fromArray($response->data());
    }
}
