<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\CsvSniff;
use Reshapify\SendSeven\Data\EmailContact;
use Reshapify\SendSeven\Data\EmailContactList;
use Reshapify\SendSeven\Data\ImportJobStart;
use Reshapify\SendSeven\Data\ImportJobStatus;
use Reshapify\SendSeven\Enums\SubscriptionStatusEnum;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\FilePart;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Payload;

/**
 * Email Contacts: 8 endpoints.
 *
 * Reach it with $sendseven->emailContacts().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts
 */
final readonly class EmailContacts
{
    public function __construct(private Connector $connector) {}

    /**
     * List Email Contacts.
     *
     * List email contacts with filters
     *
     * Filters: - subscription_status: pending, subscribed, unsubscribed - category: newsletter,
     * promotions, updates, etc. - search: Search by email or name
     *
     * Pagination: - limit: Max results per page (1-100) - offset: Number of results to skip
     *
     * Scopes: contacts:read.
     *
     * @param  SubscriptionStatusEnum|string|null  $subscriptionStatus  Filter by subscription status
     * @param  ?string  $category  Filter by category
     * @param  ?string  $search  Search by email or name
     * @param  ?int  $limit  Maximum number of results
     * @param  ?int  $offset  Pagination offset
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/list_email_contacts_api_v1_email_contacts_get
     */
    public function list(
        SubscriptionStatusEnum|string|null $subscriptionStatus = null,
        ?string $category = null,
        ?string $search = null,
        ?int $limit = null,
        ?int $offset = null,
    ): EmailContactList {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/email-contacts',
            query: Payload::query([
                'subscription_status' => $subscriptionStatus,
                'category' => $category,
                'search' => $search,
                'limit' => $limit,
                'offset' => $offset,
            ]),
        ));

        return EmailContactList::fromArray($response->data());
    }

    /**
     * Import Email Contacts.
     *
     * Import contacts from CSV file
     *
     * Imports contacts from a CSV file. At least one of email, phone, whatsapp_id, display_name,
     * first_name, or last_name is required per row. Optionally creates email subscriptions for
     * contacts that have an email address.
     *
     * Supported columns (all optional except for the row anchor above):
     *
     * Scopes: contacts:create.
     *
     * @param  FilePart  $file  CSV or XLSX file (.xlsx: first sheet, first row = headers). Anchor columns (at least one per row): contact_id, email, phone, whatsapp_id, display_name, first_name, last_name. Supports contact_id (UUID match target), first_name, last_name, display_name, email, phone, whatsapp_id, languages, birthday, tags, linkedin, instagram_handle, facebook, homepage, custom_fields.
     * @param  ?string  $columnMapping  JSON string mapping target fields to CSV column names, e.g. {"email": "E-Mail", "name": "Full Name", "phone": "Telefon"}. Per-EAV custom-field targets use the key "custom_field:<field_definition_id>".
     * @param  ?string  $duplicateMode  Override the tenant's duplicate_contact_mode for this import. Values: auto_merge, allow_duplicates, dont_allow_duplicates, update_existing. Omit to use the tenant default.
     * @param  ?string  $updateFieldMode  Only used with duplicate_mode=update_existing. 'overwrite' (default) replaces standard + EAV custom fields from the CSV (blank cells never wipe); 'fill_empty' only populates empty fields. Values: overwrite, fill_empty.
     * @param  ?string  $subscriptions  JSON array of structured channel->list subscription targets, e.g. [{"channel_type":"email","list_id":"..."},{"channel_type":"whatsapp","list_id":"..."}]. A contact is subscribed to a target only if it has the channel's required method (email→email, sms→phone, whatsapp→whatsapp_id/phone); others are silently skipped. Supported channels: email, sms, whatsapp. Takes precedence over create_subscription. Requires optin_confirmed=true.
     * @param  ?string  $delimiter  CSV delimiter override. One of: ',' ';' tab '|'. Omit to auto-sniff.
     * @param  ?string  $quotechar  CSV quote character override (default '"'). Omit to auto-detect.
     * @param  ?string  $defaultPhoneRegion  ISO-3166 alpha-2 region (e.g. 'DE') used to auto-prefix phone numbers lacking a '+' to E.164 (national '0175…' → '+49175…'). Omit to keep the lenient digit-prepend behaviour.
     * @param  ?string  $applyTagIds  Post-import action: JSON array of tag IDs (e.g. ["id1","id2"]) applied to EVERY contact this import creates OR updates. Tag IDs must belong to the tenant (404 otherwise).
     * @param  ?string  $applyCustomField  Post-import action: JSON object {"field_id": "...", "value": ...} — the custom-field value is set (overwrite) on EVERY contact this import creates OR updates. The field must be an active custom field of the tenant; SELECT/MULTISELECT values are options-validated, DATE/DATETIME must be ISO.
     * @param  ?bool  $createSubscription  Create email subscriptions for imported contacts
     * @param  ?bool  $optinConfirmed  User confirms all contacts have valid opt-in consent
     * @param  ?string  $listId  Optional list ID to add imported contacts to
     * @param  ?string  $listIds  Comma-separated list IDs to subscribe contacts to
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/import_email_contacts_api_v1_email_contacts_import_post
     */
    public function import(
        FilePart $file,
        ?string $columnMapping = null,
        ?string $duplicateMode = null,
        ?string $updateFieldMode = null,
        ?string $subscriptions = null,
        ?string $delimiter = null,
        ?string $quotechar = null,
        ?string $defaultPhoneRegion = null,
        ?string $applyTagIds = null,
        ?string $applyCustomField = null,
        ?bool $createSubscription = null,
        ?bool $optinConfirmed = null,
        ?string $listId = null,
        ?string $listIds = null,
        ?string $idempotencyKey = null,
    ): ImportJobStart {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/email-contacts/import',
            query: Payload::query([
                'create_subscription' => $createSubscription,
                'optin_confirmed' => $optinConfirmed,
                'list_id' => $listId,
                'list_ids' => $listIds,
            ]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
            multipart: Payload::multipart([
                'file' => $file,
                'column_mapping' => $columnMapping,
                'duplicate_mode' => $duplicateMode,
                'update_field_mode' => $updateFieldMode,
                'subscriptions' => $subscriptions,
                'delimiter' => $delimiter,
                'quotechar' => $quotechar,
                'default_phone_region' => $defaultPhoneRegion,
                'apply_tag_ids' => $applyTagIds,
                'apply_custom_field' => $applyCustomField,
            ]),
        ));

        return ImportJobStart::fromArray($response->data());
    }

    /**
     * Download Import Template.
     *
     * Download a contact-import template (CSV or XLSX) with 1–2 example rows.
     *
     * The headers are EXACTLY the contact-export format (auto-detected by the importer with no manual
     * mapping): a leading contact_id column (empty in the template — fill it to update an existing
     * contact, leave it empty to create), the standard contact fields, and one custom.<key> column per
     * active custom-field definition of the tenant.
     *
     * Note: telegram_id / messenger_id / instagram_id appear for export parity but are ignored on
     * import (channel-scoped platform IDs cannot be imported).
     *
     * Scopes: contacts:create.
     *
     * @param  ?string  $format  Template file format: csv | xlsx
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/download_import_template_api_v1_email_contacts_import_template_get
     */
    public function downloadImportTemplate(?string $format = null): void
    {
        $this->connector->send(new Request(
            Method::Get,
            '/email-contacts/import/template',
            query: Payload::query(['format' => $format]),
        ));
    }

    /**
     * Get Import Job Status.
     *
     * Get the status/progress of an async contact import job.
     *
     * Poll this endpoint after POST /email-contacts/import. When status is completed the full import
     * summary is returned under summary; when failed see error_message.
     *
     * Scopes: contacts:create.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/get_import_job_status_api_v1_email_contacts_import__job_id__status_get
     */
    public function getImportJobStatus(string $jobId): ImportJobStatus
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/email-contacts/import/'.Payload::segment($jobId).'/status',
        ));

        return ImportJobStatus::fromArray($response->data());
    }

    /**
     * Sniff Csv.
     *
     * Sniff a CSV/XLSX file's dialect and headers.
     *
     * Returns the detected delimiter, quote character, header column names, and a best-effort
     * suggested phone region (from the tenant's company_country) so the frontend preview parser
     * matches the backend importer exactly. Does NOT import anything. For .xlsx uploads the headers
     * come from the first sheet's first row and delimiter/ quotechar are reported as "," / '"' (the
     * dialect the backend's xlsx→csv conversion emits).
     *
     * Returns: { delimiter, quotechar, headers, suggested_phone_region }
     *
     * Scopes: contacts:create.
     *
     * @param  FilePart  $file  CSV or XLSX file to inspect for delimiter/quotechar/headers
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/sniff_csv_api_v1_email_contacts_sniff_post
     */
    public function sniffCsv(FilePart $file, ?string $idempotencyKey = null): CsvSniff
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/email-contacts/sniff',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
            multipart: Payload::multipart(['file' => $file]),
        ));

        return CsvSniff::fromArray($response->data());
    }

    /**
     * Delete Email Contact.
     *
     * Delete email contact subscription
     *
     * Note: This permanently removes the email subscription. The contact record itself is not deleted.
     *
     * Scopes: contacts:delete.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/delete_email_contact_api_v1_email_contacts__subscription_id__delete
     */
    public function delete(string $subscriptionId): void
    {
        $this->connector->send(new Request(
            Method::Delete,
            '/email-contacts/'.Payload::segment($subscriptionId),
        ));
    }

    /**
     * Get Email Contact.
     *
     * Get email contact details by subscription ID
     *
     * Scopes: contacts:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/get_email_contact_api_v1_email_contacts__subscription_id__get
     */
    public function get(string $subscriptionId): EmailContact
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/email-contacts/'.Payload::segment($subscriptionId),
        ));

        return EmailContact::fromArray($response->data());
    }

    /**
     * Update Email Contact.
     *
     * Update email contact subscription
     *
     * Updatable fields: - name - phone - subscription_status (pending, subscribed, unsubscribed) -
     * subscription_category - unsubscribe_reason (when unsubscribing)
     *
     * Scopes: contacts:update.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Contacts/update_email_contact_api_v1_email_contacts__subscription_id__patch
     */
    public function update(
        string $subscriptionId,
        ?string $name = null,
        ?string $phone = null,
        SubscriptionStatusEnum|string|null $subscriptionStatus = null,
        ?string $subscriptionCategory = null,
        ?string $unsubscribeReason = null,
        ?string $idempotencyKey = null,
    ): EmailContact {
        $response = $this->connector->send(new Request(
            Method::Patch,
            '/email-contacts/'.Payload::segment($subscriptionId),
            body: Payload::body([
                'name' => $name,
                'phone' => $phone,
                'subscription_status' => $subscriptionStatus,
                'subscription_category' => $subscriptionCategory,
                'unsubscribe_reason' => $unsubscribeReason,
            ]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return EmailContact::fromArray($response->data());
    }
}
