<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\EmailLayoutPreview;
use Reshapify\SendSeven\Data\EmailLayoutTemplate;
use Reshapify\SendSeven\Data\EmailLayoutTemplateList;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * Email Templates: 7 endpoints.
 *
 * Reach it with $sendseven->emailTemplates().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates
 */
final readonly class EmailTemplates
{
    public function __construct(private Connector $connector) {}

    /**
     * List Layout Templates.
     *
     * List email templates for the tenant
     *
     * - Can filter by category (business, creative, minimal) - Can filter by system template flag -
     * Can filter by active status - By default excludes hidden templates (use include_hidden=true to
     * include) - Returns list without full MJML source (for performance) - Supports pagination with
     * limit and offset
     *
     * Scopes: email:read.
     *
     * @param  ?string  $category  Filter by category
     * @param  ?bool  $isSystemTemplate  Filter by system template flag
     * @param  ?bool  $isActive  Filter by active status
     * @param  ?bool  $includeHidden  Include hidden/archived templates
     * @param  ?int  $limit  Max results
     * @param  ?int  $offset  Results offset
     * @return list<EmailLayoutTemplateList>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/list_layout_templates_api_v1_email_templates_get
     */
    public function listLayout(?string $category = null, ?bool $isSystemTemplate = null, ?bool $isActive = null, ?bool $includeHidden = null, ?int $limit = null, ?int $offset = null): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/email-templates',
            query: Payload::query(['category' => $category, 'is_system_template' => $isSystemTemplate, 'is_active' => $isActive, 'include_hidden' => $includeHidden, 'limit' => $limit, 'offset' => $offset]),
        ));

        return Hydrate::list($response->data(), EmailLayoutTemplateList::fromArray(...));
    }

    /**
     * Create Layout Template.
     *
     * Create a new email template with variable system
     *
     * - Define structural framework with MJML - Use {{variable_name}} placeholders for customization -
     * Set color palette and fonts for brand consistency - MJML is validated and compiled to HTML on
     * creation - Variables use lowercase_with_underscores naming convention
     *
     * Variable System: - Template variables: {{hero_title}}, {{cta_url}}, {{main_content}} - Contact
     * variables: {{contact.name}}, {{contact.email}} - Company variables: {{company.name}} - System
     * variables: {{system.year}}
     *
     * Scopes: email:create.
     *
     * @param  string  $mjmlSource  MJML source with {{variable_name}} placeholders
     * @param  string  $name  Email template name
     * @param  ?string  $category  Category (transactional, promotional, custom)
     * @param  array<string, mixed>|null  $colorPalette  Color palette (e.g., {'primary': '#0066CC'})
     * @param  ?string  $description  Template description
     * @param  ?string  $fontFamily  Font family (e.g., 'Arial, sans-serif')
     * @param  ?string  $thumbnailUrl  Template preview thumbnail URL
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/create_layout_template_api_v1_email_templates_post
     */
    public function createLayout(string $mjmlSource, string $name, ?string $category = null, ?array $colorPalette = null, ?string $description = null, ?string $fontFamily = null, ?string $thumbnailUrl = null, ?string $idempotencyKey = null): EmailLayoutTemplate
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/email-templates',
            body: Payload::body(['mjml_source' => $mjmlSource, 'name' => $name, 'category' => $category, 'color_palette' => $colorPalette, 'description' => $description, 'font_family' => $fontFamily, 'thumbnail_url' => $thumbnailUrl]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return EmailLayoutTemplate::fromArray($response->data());
    }

    /**
     * Preview Layout.
     *
     * Preview MJML template without saving (with variable replacement)
     *
     * - Accepts MJML source with {{variable}} placeholders - Replaces variables with example values -
     * Brand variables are auto-filled from tenant settings - Compiles MJML to HTML - Returns HTML for
     * preview - Does not save to database
     *
     * Brand Variables (auto-filled): - {{company.brand_color_primary}} - Primary brand color -
     * {{company.brand_color_secondary}} - Secondary brand color - {{company.brand_color_accent}} -
     * Accent brand color - {{company.logo_url}} - Company logo URL - {{company.name}} - Company name
     *
     * Scopes: email:read.
     *
     * @param  array<string, mixed>  $body  The request body
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/preview_layout_api_v1_email_templates_preview_post
     */
    public function previewLayout(array $body, ?string $idempotencyKey = null): EmailLayoutPreview
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/email-templates/preview',
            body: $body,
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return EmailLayoutPreview::fromArray($response->data());
    }

    /**
     * Delete Layout Template.
     *
     * Delete email template
     *
     * - System templates cannot be deleted - Templates with EmailContents referencing them cannot be
     * deleted (409 Conflict) - Use this endpoint to clean up unused templates
     *
     * Scopes: email:delete.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/delete_layout_template_api_v1_email_templates__template_id__delete
     */
    public function deleteLayout(string $templateId): void
    {
        $this->connector->send(new Request(
            Method::Delete,
            '/email-templates/'.Payload::segment($templateId),
        ));
    }

    /**
     * Get Layout Template.
     *
     * Get a specific email template with full MJML source
     *
     * Scopes: email:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/get_layout_template_api_v1_email_templates__template_id__get
     */
    public function getLayout(string $templateId): EmailLayoutTemplate
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/email-templates/'.Payload::segment($templateId),
        ));

        return EmailLayoutTemplate::fromArray($response->data());
    }

    /**
     * Update Layout Template.
     *
     * Update email template with variable system
     *
     * - If MJML source is updated, recompiles to HTML - Creates new version (increments version
     * number) - System templates cannot be modified - Template changes will affect future
     * EmailContents using this template - Variables use {{variable_name}} syntax
     *
     * Scopes: email:update.
     *
     * @param  array<string, mixed>|null  $colorPalette
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/update_layout_template_api_v1_email_templates__template_id__patch
     */
    public function updateLayout(string $templateId, ?string $category = null, ?array $colorPalette = null, ?string $description = null, ?string $fontFamily = null, ?string $mjmlSource = null, ?string $name = null, ?string $thumbnailUrl = null, ?string $idempotencyKey = null): EmailLayoutTemplate
    {
        $response = $this->connector->send(new Request(
            Method::Patch,
            '/email-templates/'.Payload::segment($templateId),
            body: Payload::body(['category' => $category, 'color_palette' => $colorPalette, 'description' => $description, 'font_family' => $fontFamily, 'mjml_source' => $mjmlSource, 'name' => $name, 'thumbnail_url' => $thumbnailUrl]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return EmailLayoutTemplate::fromArray($response->data());
    }

    /**
     * Duplicate Layout Template.
     *
     * Duplicate an email template
     *
     * Creates a copy of the template with a new name. All content fields are copied (MJML, HTML,
     * category, colors, thumbnail, description). The duplicate is always a non-system, non-hidden
     * template owned by the requesting tenant.
     *
     * Scopes: email:create.
     *
     * @param  string  $newName  Name for the duplicated template
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Email%20Templates/duplicate_layout_template_api_v1_email_templates__template_id__duplicate_post
     */
    public function duplicateLayout(string $templateId, string $newName, ?string $idempotencyKey = null): EmailLayoutTemplate
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/email-templates/'.Payload::segment($templateId).'/duplicate',
            body: Payload::body(['new_name' => $newName]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return EmailLayoutTemplate::fromArray($response->data());
    }
}
