<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\KbHealthResponse;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Payload;

/**
 * KB Health: 1 endpoint.
 *
 * Reach it with $sendseven->kbHealth().
 *
 * @see https://api.sendseven.com/api/v1/docs#/KB%20Health
 */
final readonly class KbHealth
{
    public function __construct(private Connector $connector) {}

    /**
     * Get Kb Health.
     *
     * Knowledge-base health dashboard.
     *
     * Buckets: most used, never used, flagged, low quality, possible duplicates, stale. Note
     * never_used counts *sent replies*, not retrievals — an entry that keeps getting retrieved but
     * never makes it into an answer is exactly the kind of dead weight this view exists to surface.
     *
     * Bulk-migration ledger rows are excluded from every bucket and every total.
     *
     * Scopes: knowledge_base:read.
     *
     * @param  ?string  $folderId  Restrict to one KB folder
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/KB%20Health/get_kb_health_api_v1_kb_health_get
     */
    public function get(?string $folderId = null): KbHealthResponse
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/kb-health',
            query: Payload::query(['folder_id' => $folderId]),
        ));

        return KbHealthResponse::fromArray($response->data());
    }
}
