<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\AddMember;
use Reshapify\SendSeven\Data\ListContacts;
use Reshapify\SendSeven\Data\ListResponse;
use Reshapify\SendSeven\Data\ListSignupOptions;
use Reshapify\SendSeven\Data\ListSubscriptionStats;
use Reshapify\SendSeven\Data\SubscriptionActivityItem;
use Reshapify\SendSeven\Enums\ListType;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Pagination\Page;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * Lists: 14 endpoints.
 *
 * Reach it with $sendseven->lists().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Lists
 */
final readonly class Lists
{
    public function __construct(private Connector $connector) {}

    /**
     * List Lists.
     *
     * List all lists for the tenant with pagination.
     *
     * Returns paginated list of all static, dynamic, and newsletter lists. Each list includes its
     * computed contact count (for email subscriptions).
     *
     * Any authenticated team member can list contact lists (used for app initialization).
     *
     * @param  ?int  $page  Page number (1-indexed)
     * @param  ?int  $pageSize  Items per page
     * @return Page<ListResponse>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/list_lists_api_v1_lists_get
     */
    public function listLists(?int $page = null, ?int $pageSize = null): Page
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists',
            query: Payload::query(['page' => $page, 'page_size' => $pageSize]),
        ));

        return Hydrate::page($response->data(), ListResponse::fromArray(...), fn (int $page): Page => $this->listLists(page: $page, pageSize: $pageSize));
    }

    /**
     * Create List.
     *
     * Create a new list (static, dynamic, or newsletter).
     *
     * - Static lists: Contacts are manually added/removed - Dynamic lists: Contacts are matched via
     * segment conditions - Newsletter lists: Contacts subscribe via widgets/deep links
     *
     * Scopes: lists:create.
     *
     * @param  string  $name  List name
     * @param  ListType|string  $listType  Type of list: static, dynamic, or newsletter
     * @param  ?string  $description  List description
     * @param  array<string, mixed>|null  $segmentConditions  Segment conditions for dynamic lists
     * @param  ?string  $slug  URL-safe slug for newsletter lists (auto-generated if not provided)
     * @param  ?string  $newsletterConfig  JSON string for newsletter configuration. Keys: `opt_in_keywords`, `opt_out_keywords`, `welcome_message`, `goodbye_message`, `confirmation_message`, `auto_subscribe_via_deeplink`, plus the button lists `welcome_buttons` / `goodbye_buttons` — each up to 3 objects of `{"type": "unsubscribe"|"unsubscribe_all"|"subscribe"|"url", "caption": "max 20 chars", "url": "https://… (url type only)"}`. Buttons render natively on WhatsApp / Telegram / Messenger / Instagram and degrade to a keyword text hint elsewhere. Omitting `goodbye_buttons` entirely means a default "Re-subscribe" button is added; send `[]` for none.
     * @param  ?bool  $showInPreferenceCenter  Whether this newsletter list is offered in the hosted email preference center (the 'Manage preferences' link in emails). Defaults to false — opt in explicitly to expose a list. Lists created before this field existed remain visible.
     * @param  ?bool  $isDefault  Whether this is the default list for global 'start'/'stop' keywords. Only one list per tenant can be default.
     * @param  array<string, mixed>|null  $optInAction  Per-channel opt-in action (send a MESSAGE or start a FLOW — never both). `{default, per_channel}`; per_channel keys are SubscriptionChannelType values. Omit to keep the legacy welcome message from `newsletter_config`. Flow actions must reference a published, same-tenant flow.
     * @param  array<string, mixed>|null  $optOutAction  Per-channel opt-out action (MESSAGE or FLOW). Same shape as `opt_in_action`. Omit to keep the legacy goodbye message.
     * @param  array<string, mixed>|null  $hubSpotOptinFieldConfig  Per-channel HubSpot contact-property mapping applied on opt-in / opt-out (`{default, per_channel}` of `{property_name, opt_in_value, opt_out_value}`). Persisted here; the HubSpot write is performed off the contact.subscribed/unsubscribed event by the integrations layer.
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/create_list_api_v1_lists_post
     */
    public function create(
        string $name,
        ListType|string $listType,
        ?string $description = null,
        ?array $segmentConditions = null,
        ?string $slug = null,
        ?string $newsletterConfig = null,
        ?bool $showInPreferenceCenter = null,
        ?bool $isDefault = null,
        ?array $optInAction = null,
        ?array $optOutAction = null,
        ?array $hubSpotOptinFieldConfig = null,
        ?string $idempotencyKey = null,
    ): ListResponse {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/lists',
            body: Payload::body([
                'name' => $name,
                'list_type' => $listType,
                'description' => $description,
                'segment_conditions' => $segmentConditions,
                'slug' => $slug,
                'newsletter_config' => $newsletterConfig,
                'show_in_preference_center' => $showInPreferenceCenter,
                'is_default' => $isDefault,
                'opt_in_action' => $optInAction,
                'opt_out_action' => $optOutAction,
                'hubspot_optin_field_config' => $hubSpotOptinFieldConfig,
            ]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return ListResponse::fromArray($response->data());
    }

    /**
     * Evaluate Conditions Count.
     *
     * Count contacts matching inline segment conditions.
     *
     * Accepts segment conditions directly (no saved list required) and returns the count of matching
     * contacts without loading them into memory.
     *
     * Response:
     *
     * Scopes: lists:read.
     *
     * @param  ?string  $operator  Logical operator: AND or OR
     * @param  list<array<string, mixed>>|null  $conditions  Flat list of conditions (legacy format)
     * @param  list<array<string, mixed>>|null  $groups  Nested condition groups for complex queries
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/evaluate_conditions_count_api_v1_lists_evaluate_count_post
     */
    public function evaluateConditionsCount(
        ?string $operator = null,
        ?array $conditions = null,
        ?array $groups = null,
        ?string $idempotencyKey = null,
    ): void {
        $this->connector->send(new Request(
            Method::Post,
            '/lists/evaluate-count',
            body: Payload::body(['operator' => $operator, 'conditions' => $conditions, 'groups' => $groups]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));
    }

    /**
     * Get Lists Subscription Stats.
     *
     * Batch opt-in / opt-out / net-change counts for every list in the window.
     *
     * Returns a row for EVERY list the tenant has (zeros for lists with no subscription activity) so
     * the frontend can map results by list_id.
     *
     * - opt_ins — subscriptions whose confirmed-opt-in timestamp (opt_in_confirmed_at) falls in the
     * window. - opt_outs — subscriptions with status unsubscribed whose unsubscribed_at falls in the
     * window. - net_change — opt_ins - opt_outs.
     *
     * Scopes: lists:read.
     *
     * @param  ?int  $windowDays  Rolling window size in days
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/get_lists_subscription_stats_api_v1_lists_subscription_stats_get
     */
    public function getSubscriptionStats(?int $windowDays = null): ListSubscriptionStats
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists/subscription-stats',
            query: Payload::query(['window_days' => $windowDays]),
        ));

        return ListSubscriptionStats::fromArray($response->data());
    }

    /**
     * Delete List.
     *
     * Delete a list.
     *
     * Permanently removes the list and all associated subscriptions.
     *
     * Scopes: lists:delete.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/delete_list_api_v1_lists__list_id__delete
     */
    public function delete(string $listId): void
    {
        $this->connector->send(new Request(
            Method::Delete,
            '/lists/'.Payload::segment($listId),
        ));
    }

    /**
     * Get List.
     *
     * Get a specific list by ID.
     *
     * Returns full list details including segment conditions and contact count.
     *
     * Scopes: lists:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/get_list_api_v1_lists__list_id__get
     */
    public function get(string $listId): ListResponse
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists/'.Payload::segment($listId),
        ));

        return ListResponse::fromArray($response->data());
    }

    /**
     * Update List.
     *
     * Update a list.
     *
     * Updates name, description, segment conditions, slug, or newsletter config. For dynamic lists,
     * contact count is automatically recalculated.
     *
     * Scopes: lists:update.
     *
     * @param  array<string, mixed>|null  $segmentConditions
     * @param  ?string  $newsletterConfig  Newsletter configuration JSON — same shape as on create, including `welcome_buttons` / `goodbye_buttons`
     * @param  ?bool  $showInPreferenceCenter  Whether this newsletter list is offered in the hosted email preference center. Omit to leave unchanged.
     * @param  ?bool  $isDefault  Whether this is the default list for global 'start'/'stop' keywords. Setting to true unsets any other default list for this tenant.
     * @param  array<string, mixed>|null  $optInAction  Per-channel opt-in action (MESSAGE or FLOW). Omit to leave unchanged. Flow actions must reference a published, same-tenant flow.
     * @param  array<string, mixed>|null  $optOutAction  Per-channel opt-out action (MESSAGE or FLOW). Omit to leave unchanged.
     * @param  array<string, mixed>|null  $hubSpotOptinFieldConfig  Per-channel HubSpot opt-in/opt-out field mapping. Omit to leave unchanged.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/update_list_api_v1_lists__list_id__put
     */
    public function update(
        string $listId,
        ?string $name = null,
        ?string $description = null,
        ?array $segmentConditions = null,
        ?string $slug = null,
        ?string $newsletterConfig = null,
        ?bool $showInPreferenceCenter = null,
        ?bool $isDefault = null,
        ?array $optInAction = null,
        ?array $optOutAction = null,
        ?array $hubSpotOptinFieldConfig = null,
    ): ListResponse {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/lists/'.Payload::segment($listId),
            body: Payload::body([
                'name' => $name,
                'description' => $description,
                'segment_conditions' => $segmentConditions,
                'slug' => $slug,
                'newsletter_config' => $newsletterConfig,
                'show_in_preference_center' => $showInPreferenceCenter,
                'is_default' => $isDefault,
                'opt_in_action' => $optInAction,
                'opt_out_action' => $optOutAction,
                'hubspot_optin_field_config' => $hubSpotOptinFieldConfig,
            ]),
        ));

        return ListResponse::fromArray($response->data());
    }

    /**
     * Get List Contacts.
     *
     * Get all contacts in a list.
     *
     * For static lists, returns subscribed contacts. For dynamic lists, evaluates segment conditions
     * in real-time.
     *
     * Scopes: lists:read, contacts:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/get_list_contacts_api_v1_lists__list_id__contacts_get
     */
    public function getContacts(string $listId): ListContacts
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists/'.Payload::segment($listId).'/contacts',
        ));

        return ListContacts::fromArray($response->data());
    }

    /**
     * Count Dynamic List.
     *
     * Count contacts matching a saved dynamic list's conditions.
     *
     * Efficiently counts matching contacts using SELECT COUNT(*) instead of loading all contacts into
     * memory.
     *
     * Response:
     *
     * Scopes: lists:read.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/count_dynamic_list_api_v1_lists__list_id__count_post
     */
    public function countDynamic(string $listId, ?string $idempotencyKey = null): void
    {
        $this->connector->send(new Request(
            Method::Post,
            '/lists/'.Payload::segment($listId).'/count',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));
    }

    /**
     * Evaluate Dynamic List.
     *
     * Preview contacts that match segment conditions.
     *
     * Used for testing/previewing dynamic list conditions before saving. Temporarily applies the
     * provided conditions and returns matching contacts.
     *
     * Scopes: lists:read.
     *
     * @param  ?string  $operator  Logical operator: AND or OR
     * @param  list<array<string, mixed>>|null  $conditions  Flat list of conditions (legacy format)
     * @param  list<array<string, mixed>>|null  $groups  Nested condition groups for complex queries
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/evaluate_dynamic_list_api_v1_lists__list_id__evaluate_post
     */
    public function evaluateDynamic(
        string $listId,
        ?string $operator = null,
        ?array $conditions = null,
        ?array $groups = null,
        ?string $idempotencyKey = null,
    ): ListContacts {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/lists/'.Payload::segment($listId).'/evaluate',
            body: Payload::body(['operator' => $operator, 'conditions' => $conditions, 'groups' => $groups]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return ListContacts::fromArray($response->data());
    }

    /**
     * Add Contact To List.
     *
     * Add a contact to a list (static or newsletter).
     *
     * - Static lists: channel_type should be None (uses email by default) - Newsletter lists:
     * channel_type is required (email, telegram, messenger, instagram, etc.); channel_id is
     * additionally required for the scoped channels telegram / messenger / instagram.
     *
     * Note: for backwards compatibility a newsletter request that omits channel_type is still accepted
     * and falls back to email, but this behavior is DEPRECATED and will be removed in a future release
     * — always send channel_type explicitly.
     *
     * Scopes: lists:update.
     *
     * @param  string  $contactId  ID of the contact to add
     * @param  ?string  $channelType  Required for newsletter subscriptions (email, telegram, messenger, instagram, ...). DEPRECATED fallback: if omitted for a newsletter list it defaults to email, but this fallback will be removed in a future release — always pass channel_type.
     * @param  ?string  $channelId  Channel ID (which bot/page). Required only for scoped newsletter channels: telegram, messenger, instagram.
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/add_contact_to_list_api_v1_lists__list_id__members_post
     */
    public function addContactTo(
        string $listId,
        string $contactId,
        ?string $channelType = null,
        ?string $channelId = null,
        ?string $idempotencyKey = null,
    ): AddMember {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/lists/'.Payload::segment($listId).'/members',
            body: Payload::body([
                'contact_id' => $contactId,
                'channel_type' => $channelType,
                'channel_id' => $channelId,
            ]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return AddMember::fromArray($response->data());
    }

    /**
     * Remove Contact From List.
     *
     * Remove a contact from a list.
     *
     * - Static lists: Removes the contact completely - Newsletter lists: Removes the subscription for
     * a specific channel; channel_type is required. (For backwards compatibility a missing
     * channel_type still falls back to email, but this is DEPRECATED and will be removed in a future
     * release.) - Dynamic lists: Cannot remove (membership determined by conditions)
     *
     * Scopes: lists:update.
     *
     * @param  ?string  $channelType  Required for newsletter unsubscriptions (email, telegram, messenger, instagram, ...). DEPRECATED fallback: if omitted for a newsletter list it defaults to email, but this fallback will be removed in a future release — always pass channel_type.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/remove_contact_from_list_api_v1_lists__list_id__members__contact_id__delete
     */
    public function removeContactFrom(string $listId, string $contactId, ?string $channelType = null): void
    {
        $this->connector->send(new Request(
            Method::Delete,
            '/lists/'.Payload::segment($listId).'/members/'.Payload::segment($contactId),
            query: Payload::query(['channel_type' => $channelType]),
        ));
    }

    /**
     * Get List Signup Options.
     *
     * Get signup options (deep links + QR codes) for a newsletter list.
     *
     * Generates channel-specific signup links and QR codes for newsletter subscriptions. Useful for
     * widgets and marketing materials.
     *
     * Only available for newsletter-type lists.
     *
     * Scopes: lists:read.
     *
     * @param  ?bool  $includeQr  Whether to generate QR codes
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/get_list_signup_options_api_v1_lists__list_id__signup_options_get
     */
    public function getSignupOptions(string $listId, ?bool $includeQr = null): ListSignupOptions
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists/'.Payload::segment($listId).'/signup-options',
            query: Payload::query(['include_qr' => $includeQr]),
        ));

        return ListSignupOptions::fromArray($response->data());
    }

    /**
     * Get List Subscription Activity.
     *
     * Per-list opt-in / opt-out event drill-down (paginated, newest first).
     *
     * - direction filters to opt-in events (in), opt-out events (out), or both (all), all within the
     * window. - last_message_in_list is populated only for unsubscribed events (the last outbound
     * campaign message this contact received on this channel that belongs to the list), with
     * attribution of exact / ambiguous / none. It is null for subscribed events.
     *
     * A single current-state subscription row can surface both a subscribed and an unsubscribed event
     * when both timestamps fall in the window.
     *
     * Scopes: lists:read, contacts:read.
     *
     * @param  ?int  $windowDays  Rolling window size in days
     * @param  ?string  $direction  all | in | out
     * @param  ?int  $page  Page number (1-indexed)
     * @param  ?int  $pageSize  Items per page
     * @return Page<SubscriptionActivityItem>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Lists/get_list_subscription_activity_api_v1_lists__list_id__subscription_activity_get
     */
    public function getSubscriptionActivity(
        string $listId,
        ?int $windowDays = null,
        ?string $direction = null,
        ?int $page = null,
        ?int $pageSize = null,
    ): Page {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/lists/'.Payload::segment($listId).'/subscription-activity',
            query: Payload::query([
                'window_days' => $windowDays,
                'direction' => $direction,
                'page' => $page,
                'page_size' => $pageSize,
            ]),
        ));

        return Hydrate::page($response->data(), SubscriptionActivityItem::fromArray(...), fn (int $page): Page => $this->getSubscriptionActivity(listId: $listId, windowDays: $windowDays, direction: $direction, page: $page, pageSize: $pageSize));
    }
}
