<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\OAuthApp;
use Reshapify\SendSeven\Data\OAuthAppCreateResponse;
use Reshapify\SendSeven\Data\OAuthAuthorization;
use Reshapify\SendSeven\Data\OAuthDelete;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * OAuth2 Apps: 8 endpoints.
 *
 * Reach it with $sendseven->oAuth2Apps().
 *
 * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps
 */
final readonly class OAuth2Apps
{
    public function __construct(private Connector $connector) {}

    /**
     * List Apps.
     *
     * List registered OAuth apps for the current tenant.
     *
     * Scopes: api:admin.
     *
     * @param  ?bool  $activeOnly  Filter to active apps only
     * @return list<OAuthApp>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/list_apps_api_v1_oauth_apps_apps_get
     */
    public function list(?bool $activeOnly = null): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/oauth-apps/apps',
            query: Payload::query(['active_only' => $activeOnly]),
        ));

        return Hydrate::list($response->data(), OAuthApp::fromArray(...));
    }

    /**
     * Create App.
     *
     * Register a new OAuth app for the current tenant.
     *
     * Returns the client_secret once - it cannot be retrieved again. Store it securely!
     *
     * Note: Public unverified apps are limited to OIDC and read-only scopes. To use
     * write/create/delete scopes publicly, submit for verification.
     *
     * Scopes: api:admin.
     *
     * @param  list<string>  $allowedScopes  Scopes the app can request
     * @param  string  $name  App display name
     * @param  list<string>  $redirectUris  Allowed redirect URIs
     * @param  ?string  $description  App description for consent screen
     * @param  ?string  $homepageUrl  App homepage URL
     * @param  ?bool  $isPublic  Can authorize users outside creator's organization
     * @param  ?string  $logoUrl  App logo URL
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/create_app_api_v1_oauth_apps_apps_post
     */
    public function create(array $allowedScopes, string $name, array $redirectUris, ?string $description = null, ?string $homepageUrl = null, ?bool $isPublic = null, ?string $logoUrl = null, ?string $idempotencyKey = null): OAuthAppCreateResponse
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/oauth-apps/apps',
            body: Payload::body(['allowed_scopes' => $allowedScopes, 'name' => $name, 'redirect_uris' => $redirectUris, 'description' => $description, 'homepage_url' => $homepageUrl, 'is_public' => $isPublic, 'logo_url' => $logoUrl]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return OAuthAppCreateResponse::fromArray($response->data());
    }

    /**
     * Delete App.
     *
     * Delete an OAuth app.
     *
     * This revokes all authorizations and removes the app.
     *
     * Scopes: api:admin.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/delete_app_api_v1_oauth_apps_apps__app_id__delete
     */
    public function delete(string $appId): OAuthDelete
    {
        $response = $this->connector->send(new Request(
            Method::Delete,
            '/oauth-apps/apps/'.Payload::segment($appId),
        ));

        return OAuthDelete::fromArray($response->data());
    }

    /**
     * Get App.
     *
     * Get OAuth app details.
     *
     * Scopes: api:admin.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/get_app_api_v1_oauth_apps_apps__app_id__get
     */
    public function get(string $appId): OAuthApp
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/oauth-apps/apps/'.Payload::segment($appId),
        ));

        return OAuthApp::fromArray($response->data());
    }

    /**
     * Update App.
     *
     * Update an OAuth app's settings.
     *
     * Note: Public unverified apps are limited to OIDC and read-only scopes. To use
     * write/create/delete scopes publicly, submit for verification.
     *
     * Scopes: api:admin.
     *
     * @param  list<string>|null  $allowedScopes
     * @param  list<string>|null  $redirectUris
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/update_app_api_v1_oauth_apps_apps__app_id__put
     */
    public function update(string $appId, ?array $allowedScopes = null, ?string $description = null, ?string $homepageUrl = null, ?bool $isActive = null, ?bool $isPublic = null, ?string $logoUrl = null, ?string $name = null, ?array $redirectUris = null): OAuthApp
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/oauth-apps/apps/'.Payload::segment($appId),
            body: Payload::body(['allowed_scopes' => $allowedScopes, 'description' => $description, 'homepage_url' => $homepageUrl, 'is_active' => $isActive, 'is_public' => $isPublic, 'logo_url' => $logoUrl, 'name' => $name, 'redirect_uris' => $redirectUris]),
        ));

        return OAuthApp::fromArray($response->data());
    }

    /**
     * Regenerate App Secret.
     *
     * Regenerate the client secret for an OAuth app.
     *
     * This immediately invalidates the old secret. The new secret is returned once and cannot be
     * retrieved again.
     *
     * Existing access tokens remain valid until they expire, but the old secret can no longer be used
     * for token exchanges or refreshes.
     *
     * Scopes: api:admin.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/regenerate_app_secret_api_v1_oauth_apps_apps__app_id__regenerate_secret_post
     */
    public function regenerateSecret(string $appId, ?string $idempotencyKey = null): OAuthAppCreateResponse
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/oauth-apps/apps/'.Payload::segment($appId).'/regenerate-secret',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return OAuthAppCreateResponse::fromArray($response->data());
    }

    /**
     * List Authorizations.
     *
     * List user's connected OAuth apps.
     *
     * Shows apps the user has authorized to access their account.
     *
     * By default (scope=tenant) only authorizations belonging to the currently-active tenant are
     * returned, preventing cross-tenant leakage on the Connected Apps settings page. Pass scope=all to
     * list the user's connected apps across every tenant they belong to.
     *
     * @param  ?string  $scope  Which authorizations to return. 'tenant' (default) limits the list to the currently-active tenant; 'all' returns the user's connected apps across every tenant.
     * @return list<OAuthAuthorization>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/list_authorizations_api_v1_oauth_apps_authorizations_get
     */
    public function listAuthorizations(?string $scope = null): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/oauth-apps/authorizations',
            query: Payload::query(['scope' => $scope]),
        ));

        return Hydrate::list($response->data(), OAuthAuthorization::fromArray(...));
    }

    /**
     * Revoke Authorization.
     *
     * Revoke access for a connected app.
     *
     * Immediately invalidates all tokens for this app-user combination.
     *
     * Requires authentication.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/OAuth2%20Apps/revoke_authorization_api_v1_oauth_apps_authorizations__authorization_id__delete
     */
    public function revokeAuthorization(string $authorizationId): OAuthDelete
    {
        $response = $this->connector->send(new Request(
            Method::Delete,
            '/oauth-apps/authorizations/'.Payload::segment($authorizationId),
        ));

        return OAuthDelete::fromArray($response->data());
    }
}
