<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\RcsPrices;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;

/**
 * RCS Wallet: 2 endpoints.
 *
 * Reach it with $sendseven->rcsWallet().
 *
 * @see https://api.sendseven.com/api/v1/docs#/RCS%20Wallet
 */
final readonly class RcsWallet
{
    public function __construct(private Connector $connector) {}

    /**
     * Get the RCS wallet.
     *
     * The prepaid RCS wallet shared by every workspace on the billing account: balance, reserved
     * amount and top-up settings.
     *
     * Scopes: billing:read. Needs the rcs feature on the SendSeven plan.
     *
     * @return array<array-key, mixed>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/RCS%20Wallet/get_rcs_wallet_api_v1_billing_rcs_wallet_get
     */
    public function get(): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/billing/rcs-wallet',
        ));

        return $response->data();
    }

    /**
     * Get your RCS unit prices.
     *
     * Net EUR prices per RCS unit (basic, single, session, mau), resolved exactly as a real send would
     * be.
     *
     * Scopes: billing:read. Needs the rcs feature on the SendSeven plan.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/RCS%20Wallet/get_rcs_prices_api_v1_billing_rcs_wallet_prices_get
     */
    public function getPrices(): RcsPrices
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/billing/rcs-wallet/prices',
        ));

        return RcsPrices::fromArray($response->data());
    }
}
