<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\AppSchemasSavedInteractiveMessageCategoryList;
use Reshapify\SendSeven\Data\SavedInteractiveMessage;
use Reshapify\SendSeven\Data\SendSavedInteractiveMessage;
use Reshapify\SendSeven\Data\Success;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Pagination\Page;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * Saved Interactive Messages: 8 endpoints.
 *
 * Reach it with $sendseven->savedInteractiveMessages().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages
 */
final readonly class SavedInteractiveMessages
{
    public function __construct(private Connector $connector) {}

    /**
     * List Saved Interactive Messages.
     *
     * List saved interactive messages visible to the current user.
     *
     * Returns the user's own messages and all shared messages. Users with canned_responses:settings
     * scope see all messages in the tenant.
     *
     * Scopes: messages:create.
     *
     * @param  ?int  $page  Page number (1-indexed)
     * @param  ?int  $pageSize  Items per page
     * @param  ?string  $type  Filter by type: 'buttons' or 'list'
     * @param  ?string  $category  Filter by category
     * @param  ?string  $search  Search in title, body, and shortcut
     * @return Page<SavedInteractiveMessage>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/list_saved_interactive_messages_api_v1_saved_interactive_messages_get
     */
    public function list(?int $page = null, ?int $pageSize = null, ?string $type = null, ?string $category = null, ?string $search = null): Page
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/saved-interactive-messages',
            query: Payload::query(['page' => $page, 'page_size' => $pageSize, 'type' => $type, 'category' => $category, 'search' => $search]),
        ));

        return Hydrate::page($response->data(), SavedInteractiveMessage::fromArray(...), fn (int $page): Page => $this->list(page: $page, pageSize: $pageSize, type: $type, category: $category, search: $search));
    }

    /**
     * Create Saved Interactive Message.
     *
     * Create a new saved interactive message template.
     *
     * By default, messages are shared (visible to all team members). Set is_shared=false to make it
     * personal. Only users with canned_responses:settings scope can create shared messages.
     *
     * ## Buttons Type - Maximum 3 reply buttons - Each button has an id (returned when clicked) and
     * title (max 20 chars)
     *
     * Scopes: messages:create.
     *
     * @param  string  $body  Main message body text (max 1024 chars)
     * @param  string  $interactiveType  Interactive message type: 'buttons' or 'list'
     * @param  string  $title  Display name for the template
     * @param  ?string  $buttonText  Menu button text for list type (e.g., 'View Options')
     * @param  list<array<string, mixed>>|null  $buttons  Buttons for type='buttons' (max 3)
     * @param  ?string  $category  Category for grouping (e.g., 'Sales', 'Support')
     * @param  ?string  $footerText  Optional footer text (max 60 chars)
     * @param  ?string  $headerAttachmentId  Attachment ID for uploaded media header. Alternative to header_media_url for image/video/document headers.
     * @param  ?string  $headerMediaUrl  URL for image/video/document header media. Required when header_type is 'image', 'video' or 'document' (unless header_attachment_id is provided).
     * @param  ?string  $headerText  Optional header text (max 60 chars). Used when header_type is 'text' or omitted.
     * @param  ?string  $headerType  Header type: 'text', 'image', 'video', 'document', or null (no header). For backward compatibility, if header_text is set but header_type is null, it is treated as 'text'.
     * @param  ?bool  $isShared  If true, visible to all team members
     * @param  list<array<string, mixed>>|null  $sections  Sections for type='list' (max 10)
     * @param  ?string  $shortcut  Optional shortcut for slash commands (e.g., 'pricing'). Stored lowercase without leading slash.
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/create_saved_interactive_message_api_v1_saved_interactive_messages_post
     */
    public function create(string $body, string $interactiveType, string $title, ?string $buttonText = null, ?array $buttons = null, ?string $category = null, ?string $footerText = null, ?string $headerAttachmentId = null, ?string $headerMediaUrl = null, ?string $headerText = null, ?string $headerType = null, ?bool $isShared = null, ?array $sections = null, ?string $shortcut = null, ?string $idempotencyKey = null): SavedInteractiveMessage
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/saved-interactive-messages',
            body: Payload::body(['body' => $body, 'interactive_type' => $interactiveType, 'title' => $title, 'button_text' => $buttonText, 'buttons' => $buttons, 'category' => $category, 'footer_text' => $footerText, 'header_attachment_id' => $headerAttachmentId, 'header_media_url' => $headerMediaUrl, 'header_text' => $headerText, 'header_type' => $headerType, 'is_shared' => $isShared, 'sections' => $sections, 'shortcut' => $shortcut]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return SavedInteractiveMessage::fromArray($response->data());
    }

    /**
     * Get By Shortcut.
     *
     * Get a saved interactive message by its shortcut.
     *
     * Used for slash command lookups (e.g., /pricing). The shortcut is case-insensitive and the
     * leading slash is optional.
     *
     * Scopes: messages:create.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/get_by_shortcut_api_v1_saved_interactive_messages_by_shortcut__shortcut__get
     */
    public function getByShortcut(string $shortcut): SavedInteractiveMessage
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/saved-interactive-messages/by-shortcut/'.Payload::segment($shortcut),
        ));

        return SavedInteractiveMessage::fromArray($response->data());
    }

    /**
     * List Categories.
     *
     * Get unique categories for saved interactive messages.
     *
     * Returns all categories from messages visible to the current user.
     *
     * Scopes: messages:create.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/list_categories_api_v1_saved_interactive_messages_categories_get
     */
    public function listCategories(): AppSchemasSavedInteractiveMessageCategoryList
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/saved-interactive-messages/categories',
        ));

        return AppSchemasSavedInteractiveMessageCategoryList::fromArray($response->data());
    }

    /**
     * Delete Saved Interactive Message.
     *
     * Delete a saved interactive message.
     *
     * Users can only delete their own messages. Users with canned_responses:settings scope can delete
     * any message.
     *
     * Scopes: messages:create.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/delete_saved_interactive_message_api_v1_saved_interactive_messages__message_id__delete
     */
    public function delete(string $messageId): Success
    {
        $response = $this->connector->send(new Request(
            Method::Delete,
            '/saved-interactive-messages/'.Payload::segment($messageId),
        ));

        return Success::fromArray($response->data());
    }

    /**
     * Get Saved Interactive Message.
     *
     * Get a specific saved interactive message by ID.
     *
     * Scopes: messages:create.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/get_saved_interactive_message_api_v1_saved_interactive_messages__message_id__get
     */
    public function get(string $messageId): SavedInteractiveMessage
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/saved-interactive-messages/'.Payload::segment($messageId),
        ));

        return SavedInteractiveMessage::fromArray($response->data());
    }

    /**
     * Update Saved Interactive Message.
     *
     * Update a saved interactive message.
     *
     * Users can only update their own messages. Users with canned_responses:settings scope can update
     * any message.
     *
     * Scopes: messages:create.
     *
     * @param  ?string  $body  Main message body text
     * @param  ?string  $buttonText  Menu button text for list type
     * @param  list<array<string, mixed>>|null  $buttons  Buttons for type='buttons'
     * @param  ?string  $category  Category for grouping
     * @param  ?string  $footerText  Optional footer text
     * @param  ?string  $headerAttachmentId  Attachment ID for uploaded media header
     * @param  ?string  $headerMediaUrl  URL for image/video/document header media
     * @param  ?string  $headerText  Optional header text
     * @param  ?string  $headerType  Header type: 'text', 'image', 'video', 'document', or null
     * @param  ?string  $interactiveType  Interactive message type
     * @param  ?bool  $isShared  If true, visible to all team members
     * @param  list<array<string, mixed>>|null  $sections  Sections for type='list'
     * @param  ?string  $shortcut  Optional shortcut for slash commands
     * @param  ?string  $title  Display name for the template
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/update_saved_interactive_message_api_v1_saved_interactive_messages__message_id__put
     */
    public function update(string $messageId, ?string $body = null, ?string $buttonText = null, ?array $buttons = null, ?string $category = null, ?string $footerText = null, ?string $headerAttachmentId = null, ?string $headerMediaUrl = null, ?string $headerText = null, ?string $headerType = null, ?string $interactiveType = null, ?bool $isShared = null, ?array $sections = null, ?string $shortcut = null, ?string $title = null): SavedInteractiveMessage
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/saved-interactive-messages/'.Payload::segment($messageId),
            body: Payload::body(['body' => $body, 'button_text' => $buttonText, 'buttons' => $buttons, 'category' => $category, 'footer_text' => $footerText, 'header_attachment_id' => $headerAttachmentId, 'header_media_url' => $headerMediaUrl, 'header_text' => $headerText, 'header_type' => $headerType, 'interactive_type' => $interactiveType, 'is_shared' => $isShared, 'sections' => $sections, 'shortcut' => $shortcut, 'title' => $title]),
        ));

        return SavedInteractiveMessage::fromArray($response->data());
    }

    /**
     * Send Saved Interactive Message.
     *
     * Send a saved interactive message to a contact.
     *
     * This endpoint retrieves the saved interactive message template and sends it to the specified
     * contact via the specified WhatsApp channel.
     *
     * The saved message must be visible to the current user (either owned by them or shared).
     *
     * Scopes: messages:create.
     *
     * @param  string  $channelId  Channel UUID (must be a WhatsApp channel)
     * @param  string  $contactId  Contact UUID (the recipient)
     * @param  array<string, mixed>|null  $meta  Custom metadata to attach to the message
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Saved%20Interactive%20Messages/send_saved_interactive_message_api_v1_saved_interactive_messages__message_id__send_post
     */
    public function send(string $messageId, string $channelId, string $contactId, ?array $meta = null, ?string $idempotencyKey = null): SendSavedInteractiveMessage
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/saved-interactive-messages/'.Payload::segment($messageId).'/send',
            body: Payload::body(['channel_id' => $channelId, 'contact_id' => $contactId, 'meta' => $meta]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return SendSavedInteractiveMessage::fromArray($response->data());
    }
}
