<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Resources;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Data\Widget;
use Reshapify\SendSeven\Data\WidgetAnalytics;
use Reshapify\SendSeven\Data\WidgetEmbedCode;
use Reshapify\SendSeven\Data\WidgetIdentitySecretReveal;
use Reshapify\SendSeven\Data\WidgetIdentitySecretRotate;
use Reshapify\SendSeven\Data\WidgetIdentityVerification;
use Reshapify\SendSeven\Enums\WidgetType;
use Reshapify\SendSeven\Enums\WidgetUseCase;
use Reshapify\SendSeven\Exceptions\ApiException;
use Reshapify\SendSeven\Http\Connector;
use Reshapify\SendSeven\Http\Method;
use Reshapify\SendSeven\Http\Request;
use Reshapify\SendSeven\Support\Hydrate;
use Reshapify\SendSeven\Support\Payload;

/**
 * Widgets: 11 endpoints.
 *
 * Reach it with $sendseven->widgets().
 *
 * @see https://api.sendseven.com/api/v1/docs#/Widgets
 */
final readonly class Widgets
{
    public function __construct(private Connector $connector) {}

    /**
     * List Widgets.
     *
     * List all widgets for the tenant
     *
     * @return list<Widget>
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/list_widgets_api_v1_widgets_get
     */
    public function list(?int $skip = null, ?int $limit = null): array
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/widgets',
            query: Payload::query(['skip' => $skip, 'limit' => $limit]),
        ));

        return Hydrate::list($response->data(), Widget::fromArray(...));
    }

    /**
     * Create Widget.
     *
     * Create a new widget
     *
     * Scopes: widgets:create.
     *
     * @param  array<string, mixed>  $config  Widget configuration
     * @param  string  $name  Internal name for the widget
     * @param  ?bool  $isActive  Widget active status
     * @param  ?bool  $isAnalyticsEnabled  Enable analytics tracking
     * @param  ?string  $privacyUrl  Customer's privacy policy URL
     * @param  WidgetUseCase|string|null  $useCase  Widget use case
     * @param  WidgetType|string|null  $widgetType  Widget display type
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/create_widget_api_v1_widgets_post
     */
    public function create(array $config, string $name, ?bool $isActive = null, ?bool $isAnalyticsEnabled = null, ?string $privacyUrl = null, WidgetUseCase|string|null $useCase = null, WidgetType|string|null $widgetType = null, ?string $idempotencyKey = null): Widget
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/widgets',
            body: Payload::body(['config' => $config, 'name' => $name, 'is_active' => $isActive, 'is_analytics_enabled' => $isAnalyticsEnabled, 'privacy_url' => $privacyUrl, 'use_case' => $useCase, 'widget_type' => $widgetType]),
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return Widget::fromArray($response->data());
    }

    /**
     * Delete Widget.
     *
     * Delete a widget
     *
     * Scopes: widgets:delete.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/delete_widget_api_v1_widgets__widget_id__delete
     */
    public function delete(string $widgetId): void
    {
        $this->connector->send(new Request(
            Method::Delete,
            '/widgets/'.Payload::segment($widgetId),
        ));
    }

    /**
     * Get Widget.
     *
     * Get a specific widget
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/get_widget_api_v1_widgets__widget_id__get
     */
    public function get(string $widgetId): Widget
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/widgets/'.Payload::segment($widgetId),
        ));

        return Widget::fromArray($response->data());
    }

    /**
     * Update Widget.
     *
     * Update a widget
     *
     * Scopes: widgets:update.
     *
     * @param  array<string, mixed>|null  $config
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/update_widget_api_v1_widgets__widget_id__put
     */
    public function update(string $widgetId, ?array $config = null, ?bool $isActive = null, ?bool $isAnalyticsEnabled = null, ?string $name = null, ?string $privacyUrl = null): Widget
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/widgets/'.Payload::segment($widgetId),
            body: Payload::body(['config' => $config, 'is_active' => $isActive, 'is_analytics_enabled' => $isAnalyticsEnabled, 'name' => $name, 'privacy_url' => $privacyUrl]),
        ));

        return Widget::fromArray($response->data());
    }

    /**
     * Get Widget Analytics.
     *
     * Get analytics data for a widget
     *
     * Returns aggregated counts by event type and daily breakdown
     *
     * Scopes: widgets:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/get_widget_analytics_api_v1_widgets__widget_id__analytics_get
     */
    public function getAnalytics(string $widgetId, ?int $days = null): WidgetAnalytics
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/widgets/'.Payload::segment($widgetId).'/analytics',
            query: Payload::query(['days' => $days]),
        ));

        return WidgetAnalytics::fromArray($response->data());
    }

    /**
     * Get Embed Code.
     *
     * Get the embed code for a widget
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/get_embed_code_api_v1_widgets__widget_id__embed_code_get
     */
    public function getEmbedCode(string $widgetId): WidgetEmbedCode
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/widgets/'.Payload::segment($widgetId).'/embed-code',
        ));

        return WidgetEmbedCode::fromArray($response->data());
    }

    /**
     * Get Identity Verification.
     *
     * Get the identity verification status of a widget
     *
     * Returns whether signed identities are verified, whether a secret exists, the last 4 characters
     * of the secret and when it was generated. Never returns the secret itself.
     *
     * Scopes: widgets:read.
     *
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/get_identity_verification_api_v1_widgets__widget_id__identity_verification_get
     */
    public function getIdentityVerification(string $widgetId): WidgetIdentityVerification
    {
        $response = $this->connector->send(new Request(
            Method::Get,
            '/widgets/'.Payload::segment($widgetId).'/identity-verification',
        ));

        return WidgetIdentityVerification::fromArray($response->data());
    }

    /**
     * Update Identity Verification.
     *
     * Enable or disable identity verification for a widget
     *
     * Body: {"enabled": true} or {"enabled": false}. Enabling requires a secret (generate one with the
     * rotate endpoint first), otherwise 409 secret_required.
     *
     * Scopes: widgets:update.
     *
     * @param  array<string, mixed>|null  $enabled  `true` to enable verification, `false` to disable it
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/update_identity_verification_api_v1_widgets__widget_id__identity_verification_put
     */
    public function updateIdentityVerification(string $widgetId, ?array $enabled = null): WidgetIdentityVerification
    {
        $response = $this->connector->send(new Request(
            Method::Put,
            '/widgets/'.Payload::segment($widgetId).'/identity-verification',
            body: Payload::body(['enabled' => $enabled]),
        ));

        return WidgetIdentityVerification::fromArray($response->data());
    }

    /**
     * Reveal Identity Verification Secret.
     *
     * Reveal the current identity verification secret of a widget
     *
     * Returns 404 secret_not_found when no secret has been generated yet.
     *
     * Only a signed-in Owner or Admin in the SendSeven app can call this. API keys, OAuth apps
     * (including MCP clients) and embed tokens get 403 interactive_session_required, whatever their
     * scopes.
     *
     * Scopes: settings:admin.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/reveal_identity_verification_secret_api_v1_widgets__widget_id__identity_verification_reveal_post
     */
    public function revealIdentityVerificationSecret(string $widgetId, ?string $idempotencyKey = null): WidgetIdentitySecretReveal
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/widgets/'.Payload::segment($widgetId).'/identity-verification/reveal',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return WidgetIdentitySecretReveal::fromArray($response->data());
    }

    /**
     * Rotate Identity Verification Secret.
     *
     * Generate a new identity verification secret for a widget
     *
     * Returns the new secret. The previous secret stops working immediately, so every identity signed
     * with it falls back to unverified until your server signs with the new one. Store the secret on
     * your server only; never put it in browser code.
     *
     * Only a signed-in Owner or Admin in the SendSeven app can call this. API keys, OAuth apps
     * (including MCP clients) and embed tokens get 403 interactive_session_required, whatever their
     * scopes.
     *
     * Scopes: settings:admin.
     *
     * @param  ?string  $idempotencyKey  Repeat a request safely: SendSeven answers a repeat with the first result. One is generated when omitted.
     *
     * @throws ApiException
     *
     * @see https://api.sendseven.com/api/v1/docs#/Widgets/rotate_identity_verification_secret_api_v1_widgets__widget_id__identity_verification_rotate_post
     */
    public function rotateIdentityVerificationSecret(string $widgetId, ?string $idempotencyKey = null): WidgetIdentitySecretRotate
    {
        $response = $this->connector->send(new Request(
            Method::Post,
            '/widgets/'.Payload::segment($widgetId).'/identity-verification/rotate',
            headers: $idempotencyKey === null ? [] : ['Idempotency-Key' => $idempotencyKey],
        ));

        return WidgetIdentitySecretRotate::fromArray($response->data());
    }
}
