<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * Supported custom field types
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum FieldType: string
{
    case Text = 'text';
    case Number = 'number';
    case Boolean = 'boolean';
    case Date = 'date';
    case Datetime = 'datetime';
    case Select = 'select';
    case Multiselect = 'multiselect';
    case Email = 'email';
    case Phone = 'phone';
    case Url = 'url';
    case Location = 'location';
    case Collection = 'collection';
}
