<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * WhatsApp Flow mode
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum FlowMode: string
{
    case Draft = 'draft';
    case Published = 'published';
}
