<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * How segment membership is resolved.
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum HubSpotSegmentRefreshMode: string
{
    case SendTime = 'send_time';
    case Cached = 'cached';
}
