<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * Lifecycle status values exposed to the API layer.
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum KbDocumentStatus: string
{
    case PendingUpload = 'pending_upload';
    case PendingIngestion = 'pending_ingestion';
    case Ready = 'ready';
    case Deleting = 'deleting';
    case Failed = 'failed';
}
