<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * What to do when escalation triggers but no agents are online (live chat)
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum OfflineEscalationBehaviorEnum: string
{
    case LeaveMessage = 'leave_message';
    case EscalateAnyway = 'escalate_anyway';
    case ContinueBot = 'continue_bot';
}
