<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * Method used to subscribe contact
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum OptInMethodEnum: string
{
    case Widget = 'widget';
    case Import = 'import';
    case Api = 'api';
    case Manual = 'manual';
}
