<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * How keywords are compared against the comment text.
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum SocialCommentRuleMatchMode: string
{
    case AnyComment = 'any_comment';
    case Contains = 'contains';
    case Exact = 'exact';
    case StartsWith = 'starts_with';
}
