<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Enums;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

/**
 * WhatsApp template approval status
 *
 * SendSeven may add values: responses carry unknown ones as plain strings.
 */
enum TemplateStatus: string
{
    case Pending = 'PENDING';
    case Approved = 'APPROVED';
    case Rejected = 'REJECTED';
    case Paused = 'PAUSED';
    case Disabled = 'DISABLED';
}
