<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Live account-/page-level insights for one connected channel.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AccountInsightsResponse)
 */
final readonly class AccountInsights extends Data
{
    /**
     * @param  string  $platform  `instagram` or `messenger`.
     * @param  ?string  $objectId  The IG account id / FB page id the insights are for.
     * @param  ?bool  $authorized  False when the connection lacks the insights permission.
     * @param  ?string  $errorCode  `insights_not_authorized`, `insights_unavailable`, or `insights_error`. Null on success.
     * @param  ?string  $message  Human-readable detail.
     * @param  string  $retrievedAt  When these numbers were fetched (nothing is stored).
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public string $platform,
        public ?string $objectId,
        public ?bool $authorized,
        public ?string $errorCode,
        public ?string $message,
        public ?SocialInsightsMetrics $metrics,
        public string $retrievedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'accountInsights'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            platform: $attributes->string('platform'),
            objectId: $attributes->nullableString('object_id'),
            authorized: $attributes->nullableBool('authorized'),
            errorCode: $attributes->nullableString('error_code'),
            message: $attributes->nullableString('message'),
            metrics: $attributes->nullableObject('metrics', SocialInsightsMetrics::fromArray(...)),
            retrievedAt: $attributes->string('retrieved_at'),
            raw: $data,
        );
    }
}
