<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for adding a contact to a list
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AddMemberResponse)
 */
final readonly class AddMember extends Data
{
    /**
     * @param  ?bool  $success  Whether the operation succeeded
     * @param  ?string  $message  Optional success message
     * @param  ?string  $memberId  ID of the membership/subscription record
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $success,
        public ?string $message,
        public ?string $memberId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'addMember'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            success: $attributes->nullableBool('success'),
            message: $attributes->nullableString('message'),
            memberId: $attributes->nullableString('member_id'),
            raw: $data,
        );
    }
}
