<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Performance metrics for a single agent
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AgentPerformance)
 */
final readonly class AgentPerformance extends Data
{
    /**
     * @param  string  $userId  Agent user ID
     * @param  string  $userName  Agent display name
     * @param  ?string  $userEmail  Agent email
     * @param  int  $conversationCount  Number of conversations handled
     * @param  int  $messageCount  Number of outbound messages sent
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $userId,
        public string $userName,
        public ?string $userEmail,
        public int $conversationCount,
        public int $messageCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'agentPerformance'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            userId: $attributes->string('user_id'),
            userName: $attributes->string('user_name'),
            userEmail: $attributes->nullableString('user_email'),
            conversationCount: $attributes->int('conversation_count'),
            messageCount: $attributes->int('message_count'),
            raw: $data,
        );
    }
}
