<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * AI/Bot performance metrics for dashboard.
 *
 * Returned by GET /api/v1/analytics/ai/performance
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AIPerformanceResponse)
 */
final readonly class AiPerformance extends Data
{
    /**
     * @param  int  $totalBotMessages  Count of messages sent by bots
     * @param  int  $totalManualMessages  Count of outbound messages NOT from bots
     * @param  int  $botSessionsCount  Total bot conversation sessions
     * @param  float  $avgConfidenceScore  Average confidence score (0.0-1.0, multiply by 100 for %)
     * @param  float  $escalationRate  Percentage of sessions that escalated to human agent
     * @param  string  $periodStart  Start of the reporting period (ISO format)
     * @param  string  $periodEnd  End of the reporting period (ISO format)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $totalBotMessages,
        public int $totalManualMessages,
        public int $botSessionsCount,
        public float $avgConfidenceScore,
        public float $escalationRate,
        public string $periodStart,
        public string $periodEnd,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'aiPerformance'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            totalBotMessages: $attributes->int('total_bot_messages'),
            totalManualMessages: $attributes->int('total_manual_messages'),
            botSessionsCount: $attributes->int('bot_sessions_count'),
            avgConfidenceScore: $attributes->float('avg_confidence_score'),
            escalationRate: $attributes->float('escalation_rate'),
            periodStart: $attributes->string('period_start'),
            periodEnd: $attributes->string('period_end'),
            raw: $data,
        );
    }
}
