<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * API token response (plaintext token NOT included).
 *
 * This is the standard response for listing and viewing tokens. The plaintext token is only shown
 * once at creation time.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ApiTokenResponse)
 */
final readonly class ApiToken extends Data
{
    /**
     * @param  string  $id  Unique identifier (UUID)
     * @param  string  $tenantId  Tenant this token belongs to
     * @param  string  $userId  User who created this token
     * @param  string  $name  Human-readable name for this token
     * @param  list<string>  $scopes  Scopes granted to this token
     * @param  ?DateTimeImmutable  $lastUsedAt  When the token was last used
     * @param  DateTimeImmutable  $createdAt  When the token was created
     * @param  ?DateTimeImmutable  $expiresAt  When the token expires
     * @param  bool  $isActive  Whether the token is active
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $userId,
        public string $name,
        public array $scopes,
        public ?DateTimeImmutable $lastUsedAt,
        public DateTimeImmutable $createdAt,
        public ?DateTimeImmutable $expiresAt,
        public bool $isActive,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'apiToken'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            userId: $attributes->string('user_id'),
            name: $attributes->string('name'),
            scopes: $attributes->strings('scopes'),
            lastUsedAt: $attributes->nullableDateTime('last_used_at'),
            createdAt: $attributes->dateTime('created_at'),
            expiresAt: $attributes->nullableDateTime('expires_at'),
            isActive: $attributes->bool('is_active'),
            raw: $data,
        );
    }
}
