<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Schema for attachment in message response
 *
 * @see https://api.sendseven.com/api/v1/docs (schema app__schemas__message__AttachmentResponse)
 */
final readonly class AppSchemasMessageAttachment extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $contentType,
        public string $createdAt,
        public int $fileSize,
        public string $filename,
        public string $id,
        public string $storagePath,
        public ?string $url,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'appSchemasMessageAttachment'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            contentType: $attributes->string('content_type'),
            createdAt: $attributes->string('created_at'),
            fileSize: $attributes->int('file_size'),
            filename: $attributes->string('filename'),
            id: $attributes->string('id'),
            storagePath: $attributes->string('storage_path'),
            url: $attributes->nullableString('url'),
            raw: $data,
        );
    }
}
