<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * WhatsApp Flow object response
 *
 * @see https://api.sendseven.com/api/v1/docs (schema app__schemas__whatsapp_flow__FlowResponse)
 */
final readonly class AppSchemasWhatsAppFlowFlow extends Data
{
    /**
     * @param  string  $id  Flow ID from WhatsApp
     * @param  string  $name  Flow name
     * @param  string  $status  Flow status: DRAFT, PUBLISHED, etc.
     * @param  list<string>  $categories  Flow categories
     * @param  list<mixed>  $validationErrors  Validation errors if any
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $name,
        public string $status,
        public array $categories,
        public array $validationErrors,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'appSchemasWhatsAppFlowFlow'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            name: $attributes->string('name'),
            status: $attributes->string('status'),
            categories: $attributes->strings('categories'),
            validationErrors: array_values($attributes->array('validation_errors')),
            raw: $data,
        );
    }
}
