<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from archive (soft-delete) operation
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ArchiveIntegrationResponse)
 */
final readonly class ArchiveIntegration extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $success,
        public string $integrationId,
        public string $message,
        public ?DateTimeImmutable $archivedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'archiveIntegration'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            success: $attributes->bool('success'),
            integrationId: $attributes->string('integration_id'),
            message: $attributes->string('message'),
            archivedAt: $attributes->nullableDateTime('archived_at'),
            raw: $data,
        );
    }
}
