<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Enums\ChannelStatus;
use Reshapify\SendSeven\Support\Attributes;

/**
 * A channel available to reach a contact
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AvailableChannelResponse)
 */
final readonly class AvailableChannel extends Data
{
    /**
     * @param  string  $channelId  Channel UUID
     * @param  string  $channelType  Channel type (whatsapp, telegram, etc.)
     * @param  string  $channelName  User-friendly channel name
     * @param  string  $identifier  Contact's identifier on this channel
     * @param  ChannelStatus|string  $status  Channel availability status
     * @param  ?WhatsAppChannelWindowStatus  $windowStatus  WhatsApp window status (WhatsApp channels only)
     * @param  ?EmailMailboxInfo  $emailMailbox  Email mailbox info (email channels only, when using mailbox-based routing)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public string $channelType,
        public string $channelName,
        public string $identifier,
        public ChannelStatus|string $status,
        public ?WhatsAppChannelWindowStatus $windowStatus,
        public ?EmailMailboxInfo $emailMailbox,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'availableChannel'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            channelType: $attributes->string('channel_type'),
            channelName: $attributes->string('channel_name'),
            identifier: $attributes->string('identifier'),
            status: $attributes->enum('status', ChannelStatus::class),
            windowStatus: $attributes->nullableObject('window_status', WhatsAppChannelWindowStatus::fromArray(...)),
            emailMailbox: $attributes->nullableObject('email_mailbox', EmailMailboxInfo::fromArray(...)),
            raw: $data,
        );
    }
}
