<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * One number offered for purchase.
 *
 * Prices are captured at list-time and are the wholesale seven.io quote (EUR net). Our markup is
 * applied server-side at provision-time.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema AvailableNumberResponse)
 */
final readonly class AvailableNumber extends Data
{
    /**
     * @param  list<string>  $features
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $number,
        public ?string $country,
        public ?string $monthlyPriceEur,
        public ?string $yearlyPriceEur,
        public array $features,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'availableNumber'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            number: $attributes->string('number'),
            country: $attributes->nullableString('country'),
            monthlyPriceEur: $attributes->nullableString('monthly_price_eur'),
            yearlyPriceEur: $attributes->nullableString('yearly_price_eur'),
            features: $attributes->strings('features'),
            raw: $data,
        );
    }
}
