<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Prepaid SMS balance + the tenant's balance-related settings.
 *
 * low_balance_warn_eur is the EFFECTIVE low-balance warning threshold (per-tenant override if set,
 * else the platform default); low_balance_warn_is_default tells whether it is the platform
 * default. Change it with PUT /sms/low-balance-threshold.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BalanceResponse)
 */
final readonly class Balance extends Data
{
    /**
     * @param  string  $lowBalanceWarnEur  Effective low-balance warning threshold in EUR: the per-workspace override when set, otherwise the platform default.
     * @param  ?bool  $lowBalanceWarnIsDefault  True when no per-workspace override is set (platform default applies).
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $balanceEur,
        public ?bool $autoTopupEnabled,
        public ?int $autoTopupThresholdCents,
        public ?int $autoTopupAmountCents,
        public ?DateTimeImmutable $lastCheckedAt,
        public string $lowBalanceWarnEur,
        public ?bool $lowBalanceWarnIsDefault,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'balance'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            balanceEur: $attributes->string('balance_eur'),
            autoTopupEnabled: $attributes->nullableBool('auto_topup_enabled'),
            autoTopupThresholdCents: $attributes->nullableInt('auto_topup_threshold_cents'),
            autoTopupAmountCents: $attributes->nullableInt('auto_topup_amount_cents'),
            lastCheckedAt: $attributes->nullableDateTime('last_checked_at'),
            lowBalanceWarnEur: $attributes->string('low_balance_warn_eur'),
            lowBalanceWarnIsDefault: $attributes->nullableBool('low_balance_warn_is_default'),
            raw: $data,
        );
    }
}
