<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Summary analytics across all bots
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BotAnalyticsSummary)
 */
final readonly class BotAnalyticsSummary extends Data
{
    /**
     * @param  list<BotBreakdownItem>  $botBreakdown
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $activeBots,
        public ?float $avgMessagesPerSession,
        public array $botBreakdown,
        public ?float $overallEscalationRate,
        public ?float $overallResolutionRate,
        public ?int $periodDays,
        public DateTimeImmutable $periodEnd,
        public DateTimeImmutable $periodStart,
        public string $tenantId,
        public ?int $totalAbandonments,
        public ?int $totalBots,
        public ?int $totalCompletions,
        public ?int $totalEscalations,
        public ?int $totalMessages,
        public ?int $totalSessions,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'botAnalyticsSummary'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            activeBots: $attributes->nullableInt('active_bots'),
            avgMessagesPerSession: $attributes->nullableFloat('avg_messages_per_session'),
            botBreakdown: $attributes->list('bot_breakdown', BotBreakdownItem::fromArray(...)),
            overallEscalationRate: $attributes->nullableFloat('overall_escalation_rate'),
            overallResolutionRate: $attributes->nullableFloat('overall_resolution_rate'),
            periodDays: $attributes->nullableInt('period_days'),
            periodEnd: $attributes->dateTime('period_end'),
            periodStart: $attributes->dateTime('period_start'),
            tenantId: $attributes->string('tenant_id'),
            totalAbandonments: $attributes->nullableInt('total_abandonments'),
            totalBots: $attributes->nullableInt('total_bots'),
            totalCompletions: $attributes->nullableInt('total_completions'),
            totalEscalations: $attributes->nullableInt('total_escalations'),
            totalMessages: $attributes->nullableInt('total_messages'),
            totalSessions: $attributes->nullableInt('total_sessions'),
            raw: $data,
        );
    }
}
