<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Bounce analytics response
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BounceAnalyticsResponse)
 */
final readonly class BounceAnalytics extends Data
{
    /**
     * @param  list<BounceAnalyticsCategoryCount>  $topCategories
     * @param  list<BounceAnalyticsDomainCount>  $topDomains
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public float $hardBounceRate,
        public int $hardBounces,
        public int $periodDays,
        public float $softBounceRate,
        public int $softBounces,
        public array $topCategories,
        public array $topDomains,
        public int $totalBounces,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'bounceAnalytics'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            hardBounceRate: $attributes->float('hard_bounce_rate'),
            hardBounces: $attributes->int('hard_bounces'),
            periodDays: $attributes->int('period_days'),
            softBounceRate: $attributes->float('soft_bounce_rate'),
            softBounces: $attributes->int('soft_bounces'),
            topCategories: $attributes->list('top_categories', BounceAnalyticsCategoryCount::fromArray(...)),
            topDomains: $attributes->list('top_domains', BounceAnalyticsDomainCount::fromArray(...)),
            totalBounces: $attributes->int('total_bounces'),
            raw: $data,
        );
    }
}
