<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Bounce count by domain
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BounceAnalyticsDomainCount)
 */
final readonly class BounceAnalyticsDomainCount extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $count,
        public string $domain,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'bounceAnalyticsDomainCount'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            count: $attributes->int('count'),
            domain: $attributes->string('domain'),
            raw: $data,
        );
    }
}
