<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Brand color configuration
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BrandColors)
 */
final readonly class BrandColors extends Data
{
    /**
     * @param  ?string  $accent  Accent color (hex code)
     * @param  ?string  $primary  Primary brand color (hex code)
     * @param  ?string  $secondary  Secondary brand color (hex code)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $accent,
        public ?string $primary,
        public ?string $secondary,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'brandColors'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            accent: $attributes->nullableString('accent'),
            primary: $attributes->nullableString('primary'),
            secondary: $attributes->nullableString('secondary'),
            raw: $data,
        );
    }
}
