<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * BulkDeleteContactsResponse from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BulkDeleteContactsResponse)
 */
final readonly class BulkDeleteContacts extends Data
{
    /**
     * @param  list<string>  $failedIds
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $failedCount,
        public array $failedIds,
        public int $successCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'bulkDeleteContacts'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            failedCount: $attributes->int('failed_count'),
            failedIds: $attributes->strings('failed_ids'),
            successCount: $attributes->int('success_count'),
            raw: $data,
        );
    }
}
