<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * BulkActionPreviewResponse from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BulkActionPreviewResponse)
 */
final readonly class BulkActionPreview extends Data
{
    /**
     * @param  int  $affectedCount  Contacts currently matching the selection
     * @param  string  $confirmationToken  Pass back verbatim to /execute together with the SAME selection+actions
     * @param  int  $expiresInSeconds  Token TTL (seconds)
     * @param  list<BulkActionSampleContact>  $sample  Up to 5 matching contacts for the confirmation dialog
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $affectedCount,
        public string $confirmationToken,
        public int $expiresInSeconds,
        public array $sample,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'bulkActionPreview'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            affectedCount: $attributes->int('affected_count'),
            confirmationToken: $attributes->string('confirmation_token'),
            expiresInSeconds: $attributes->int('expires_in_seconds'),
            sample: $attributes->list('sample', BulkActionSampleContact::fromArray(...)),
            raw: $data,
        );
    }
}
