<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response body for POST /documents/bulk-delete.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema BulkDeleteResponse)
 */
final readonly class BulkDelete extends Data
{
    /**
     * @param  list<BulkDeleteQueuedItem>  $queued  Per-document job handles. Poll GET /jobs/{job_id} for progress.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $queued,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'bulkDelete'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            queued: $attributes->list('queued', BulkDeleteQueuedItem::fromArray(...)),
            raw: $data,
        );
    }
}
