<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Campaign metadata for messages sent via campaigns.
 *
 * When a message was sent as part of a campaign (newsletter/broadcast), this object is populated
 * so the frontend can display a campaign badge in the conversation timeline.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CampaignInfo)
 */
final readonly class CampaignInfo extends Data
{
    /**
     * @param  string  $campaignId  Campaign UUID
     * @param  ?string  $campaignMessageId  CampaignMessage UUID for tracking
     * @param  string  $campaignName  Campaign display name
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $campaignId,
        public ?string $campaignMessageId,
        public string $campaignName,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'campaignInfo'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            campaignId: $attributes->string('campaign_id'),
            campaignMessageId: $attributes->nullableString('campaign_message_id'),
            campaignName: $attributes->string('campaign_name'),
            raw: $data,
        );
    }
}
