<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Campaign performance analytics.
 *
 * Returned by GET /api/v1/analytics/campaigns/performance
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CampaignPerformanceResponse)
 */
final readonly class CampaignPerformance extends Data
{
    /**
     * @param  list<ChannelCampaignStats>  $byChannel  Campaign stats by channel type
     * @param  ?int  $completedCampaigns  Completed campaigns in the period
     * @param  ?float  $deliveryRate  Delivery rate percentage (delivered/sent)
     * @param  ?EmailBreakdown  $email  Email volume split by single/transactional vs campaign, each aligned to invoiced usage
     * @param  ?float  $emailBounceRate  Email bounce rate percentage (bounced/sent)
     * @param  ?int  $emailBounced  Total email bounces
     * @param  ?float  $emailClickRate  Email click rate percentage (clicked/opened)
     * @param  ?int  $emailClicked  Total email clicks
     * @param  ?int  $emailComplained  Total email spam complaints
     * @param  ?float  $emailOpenRate  Email open rate percentage (opened/sent)
     * @param  ?int  $emailOpened  Total email opens
     * @param  ?int  $emailSent  Total email campaign messages sent
     * @param  string  $periodEnd  End of the reporting period (ISO format)
     * @param  string  $periodStart  Start of the reporting period (ISO format)
     * @param  ?float  $readRate  Read rate percentage (read/delivered)
     * @param  list<RecentCampaign>  $recentCampaigns  Last 5 completed campaigns
     * @param  ?SupportBreakdown  $support  Customer-support volume: bot vs human (rollup-sourced) + single/transactional emails
     * @param  ?int  $totalCampaigns  Total campaigns in the period
     * @param  ?int  $totalDelivered  Total messages delivered
     * @param  ?int  $totalFailed  Total messages failed
     * @param  ?int  $totalRead  Total messages read
     * @param  ?int  $totalSent  Total messages sent across all campaigns
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $byChannel,
        public ?int $completedCampaigns,
        public ?float $deliveryRate,
        public ?EmailBreakdown $email,
        public ?float $emailBounceRate,
        public ?int $emailBounced,
        public ?float $emailClickRate,
        public ?int $emailClicked,
        public ?int $emailComplained,
        public ?float $emailOpenRate,
        public ?int $emailOpened,
        public ?int $emailSent,
        public string $periodEnd,
        public string $periodStart,
        public ?float $readRate,
        public array $recentCampaigns,
        public ?SupportBreakdown $support,
        public ?int $totalCampaigns,
        public ?int $totalDelivered,
        public ?int $totalFailed,
        public ?int $totalRead,
        public ?int $totalSent,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'campaignPerformance'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            byChannel: $attributes->list('by_channel', ChannelCampaignStats::fromArray(...)),
            completedCampaigns: $attributes->nullableInt('completed_campaigns'),
            deliveryRate: $attributes->nullableFloat('delivery_rate'),
            email: $attributes->nullableObject('email', EmailBreakdown::fromArray(...)),
            emailBounceRate: $attributes->nullableFloat('email_bounce_rate'),
            emailBounced: $attributes->nullableInt('email_bounced'),
            emailClickRate: $attributes->nullableFloat('email_click_rate'),
            emailClicked: $attributes->nullableInt('email_clicked'),
            emailComplained: $attributes->nullableInt('email_complained'),
            emailOpenRate: $attributes->nullableFloat('email_open_rate'),
            emailOpened: $attributes->nullableInt('email_opened'),
            emailSent: $attributes->nullableInt('email_sent'),
            periodEnd: $attributes->string('period_end'),
            periodStart: $attributes->string('period_start'),
            readRate: $attributes->nullableFloat('read_rate'),
            recentCampaigns: $attributes->list('recent_campaigns', RecentCampaign::fromArray(...)),
            support: $attributes->nullableObject('support', SupportBreakdown::fromArray(...)),
            totalCampaigns: $attributes->nullableInt('total_campaigns'),
            totalDelivered: $attributes->nullableInt('total_delivered'),
            totalFailed: $attributes->nullableInt('total_failed'),
            totalRead: $attributes->nullableInt('total_read'),
            totalSent: $attributes->nullableInt('total_sent'),
            raw: $data,
        );
    }
}
