<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Batch opt-out counts keyed by campaign id (missing id => 0).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CampaignUnsubscribeCountsResponse)
 */
final readonly class CampaignUnsubscribeCounts extends Data
{
    /**
     * @param  array<array-key, mixed>  $counts  Map of campaign id -> {total, exact, estimated}. Ids with no opt-outs are omitted.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $counts,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'campaignUnsubscribeCounts'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            counts: $attributes->array('counts'),
            raw: $data,
        );
    }
}
