<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Per-batch delivery counts (one row per batch number).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CampaignBatchItem)
 */
final readonly class CampaignBatchItem extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $batchNumber,
        public ?int $delivered,
        public ?int $failed,
        public ?int $pending,
        public ?int $read,
        public ?int $sent,
        public ?int $skipped,
        public ?int $total,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'campaignBatchItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            batchNumber: $attributes->int('batch_number'),
            delivered: $attributes->nullableInt('delivered'),
            failed: $attributes->nullableInt('failed'),
            pending: $attributes->nullableInt('pending'),
            read: $attributes->nullableInt('read'),
            sent: $attributes->nullableInt('sent'),
            skipped: $attributes->nullableInt('skipped'),
            total: $attributes->nullableInt('total'),
            raw: $data,
        );
    }
}
