<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Message count for a single channel type
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ChannelMessageCount)
 */
final readonly class ChannelMessageCount extends Data
{
    /**
     * @param  string  $channelType  Channel type (whatsapp, telegram, etc.)
     * @param  int  $messageCount  Number of messages for this channel
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelType,
        public int $messageCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'channelMessageCount'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelType: $attributes->string('channel_type'),
            messageCount: $attributes->int('message_count'),
            raw: $data,
        );
    }
}
