<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Unified response schema for channel profile
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ChannelProfileResponse)
 */
final readonly class ChannelProfile extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public string $channelType,
        public string $channelName,
        public ?WhatsAppProfile $whatsApp,
        public ?TelegramProfile $telegram,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'channelProfile'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            channelType: $attributes->string('channel_type'),
            channelName: $attributes->string('channel_name'),
            whatsApp: $attributes->nullableObject('whatsapp', WhatsAppProfile::fromArray(...)),
            telegram: $attributes->nullableObject('telegram', TelegramProfile::fromArray(...)),
            raw: $data,
        );
    }
}
