<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Feature matrix for a channel
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ChannelFeatures)
 */
final readonly class ChannelFeatures extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $audio,
        public mixed $carousels,
        public ?bool $contacts,
        public ?bool $documents,
        public ?bool $images,
        public mixed $interactiveButtons,
        public mixed $interactiveLists,
        public ?bool $location,
        public ?int $maxMediaCaptionLength,
        public ?int $maxTextLength,
        public ?bool $proxy,
        public mixed $quickReplies,
        public ?bool $reactions,
        public ?bool $stickers,
        public ?bool $supportsReply,
        public ?bool $templates,
        public ?bool $text,
        public ?bool $videos,
        public ?bool $voice,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'channelFeatures'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            audio: $attributes->nullableBool('audio'),
            carousels: $data['carousels'] ?? null,
            contacts: $attributes->nullableBool('contacts'),
            documents: $attributes->nullableBool('documents'),
            images: $attributes->nullableBool('images'),
            interactiveButtons: $data['interactive_buttons'] ?? null,
            interactiveLists: $data['interactive_lists'] ?? null,
            location: $attributes->nullableBool('location'),
            maxMediaCaptionLength: $attributes->nullableInt('max_media_caption_length'),
            maxTextLength: $attributes->nullableInt('max_text_length'),
            proxy: $attributes->nullableBool('proxy'),
            quickReplies: $data['quick_replies'] ?? null,
            reactions: $attributes->nullableBool('reactions'),
            stickers: $attributes->nullableBool('stickers'),
            supportsReply: $attributes->nullableBool('supports_reply'),
            templates: $attributes->nullableBool('templates'),
            text: $attributes->nullableBool('text'),
            videos: $attributes->nullableBool('videos'),
            voice: $attributes->nullableBool('voice'),
            raw: $data,
        );
    }
}
