<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response with health status of all channel integrations
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ChannelHealthResponse)
 */
final readonly class ChannelHealth extends Data
{
    /**
     * @param  list<ChannelHealthItem>  $integrations
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $hasErrors,
        public int $errorCount,
        public array $integrations,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'channelHealth'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            hasErrors: $attributes->bool('has_errors'),
            errorCount: $attributes->int('error_count'),
            integrations: $attributes->list('integrations', ChannelHealthItem::fromArray(...)),
            raw: $data,
        );
    }
}
