<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Health status of a single channel/integration
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ChannelHealthItem)
 */
final readonly class ChannelHealthItem extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelType,
        public string $connectionStatus,
        public ?string $emailAddress,
        public string $id,
        public ?string $integrationType,
        public ?string $lastError,
        public ?string $lastErrorAt,
        public string $name,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'channelHealthItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelType: $attributes->string('channel_type'),
            connectionStatus: $attributes->string('connection_status'),
            emailAddress: $attributes->nullableString('email_address'),
            id: $attributes->string('id'),
            integrationType: $attributes->nullableString('integration_type'),
            lastError: $attributes->nullableString('last_error'),
            lastErrorAt: $attributes->nullableString('last_error_at'),
            name: $attributes->string('name'),
            raw: $data,
        );
    }
}
