<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * A single click event
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ClickDetail)
 */
final readonly class ClickDetail extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $clickedAt,
        public ?string $deviceType,
        public ?string $ipAddress,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'clickDetail'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            clickedAt: $attributes->nullableString('clicked_at'),
            deviceType: $attributes->nullableString('device_type'),
            ipAddress: $attributes->nullableString('ip_address'),
            raw: $data,
        );
    }
}
