<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Polling payload for the frontend Coexistence syncing screen.
 *
 * All fields except channel_id and is_coexistence may be null on fresh / non-coexistence channels.
 * Datetimes are timezone-aware UTC.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CoexistenceStatusResponse)
 */
final readonly class CoexistenceStatus extends Data
{
    /**
     * @param  ?string  $historySyncStatus  One of: not_started, requested, in_progress, completed, declined, failed, unavailable (Meta's one-time 24h-from-onboarding sync window closed before history could be requested)
     * @param  ?string  $contactsSyncStatus  One of: not_started, requested, completed, failed, unavailable (24h sync window closed before the address book could be requested)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public bool $isCoexistence,
        public ?bool $isOnBizApp,
        public ?string $platformType,
        public ?DateTimeImmutable $coexistenceOnboardedAt,
        public ?string $historySyncStatus,
        public ?int $historySyncProgress,
        public ?int $historySyncPhase,
        public ?string $contactsSyncStatus,
        public ?DateTimeImmutable $disconnectedAt,
        public ?string $disconnectionReason,
        public ?DateTimeImmutable $reconnectedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'coexistenceStatus'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            isCoexistence: $attributes->bool('is_coexistence'),
            isOnBizApp: $attributes->nullableBool('is_on_biz_app'),
            platformType: $attributes->nullableString('platform_type'),
            coexistenceOnboardedAt: $attributes->nullableDateTime('coexistence_onboarded_at'),
            historySyncStatus: $attributes->nullableString('history_sync_status'),
            historySyncProgress: $attributes->nullableInt('history_sync_progress'),
            historySyncPhase: $attributes->nullableInt('history_sync_phase'),
            contactsSyncStatus: $attributes->nullableString('contacts_sync_status'),
            disconnectedAt: $attributes->nullableDateTime('disconnected_at'),
            disconnectionReason: $attributes->nullableString('disconnection_reason'),
            reconnectedAt: $attributes->nullableDateTime('reconnected_at'),
            raw: $data,
        );
    }
}
