<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from validating compliance footer HTML
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ComplianceFooterValidationResponse)
 */
final readonly class ComplianceFooterValidation extends Data
{
    /**
     * @param  list<string>  $errors  List of validation errors
     * @param  bool  $isValid  Whether the footer HTML is valid
     * @param  ?string  $sanitizedHtml  Sanitized HTML after validation
     * @param  list<string>  $warnings  List of validation warnings
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $errors,
        public bool $isValid,
        public ?string $sanitizedHtml,
        public array $warnings,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'complianceFooterValidation'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            errors: $attributes->strings('errors'),
            isValid: $attributes->bool('is_valid'),
            sanitizedHtml: $attributes->nullableString('sanitized_html'),
            warnings: $attributes->strings('warnings'),
            raw: $data,
        );
    }
}
