<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from configuring SendGrid webhooks
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ConfigureWebhooksResponse)
 */
final readonly class ConfigureWebhooks extends Data
{
    /**
     * @param  bool  $success  Whether webhook configuration succeeded
     * @param  string  $webhookUrl  The configured webhook URL
     * @param  string  $message  Status message
     * @param  array<array-key, mixed>  $currentSettings  Current webhook settings from SendGrid
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $success,
        public string $webhookUrl,
        public string $message,
        public array $currentSettings,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'configureWebhooks'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            success: $attributes->bool('success'),
            webhookUrl: $attributes->string('webhook_url'),
            message: $attributes->string('message'),
            currentSettings: $attributes->array('current_settings'),
            raw: $data,
        );
    }
}
