<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Compact contact representation for list contexts (duplicate groups).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactSummary)
 */
final readonly class ContactSummary extends Data
{
    /**
     * @param  list<DuplicateRefMethod>  $methods
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public ?string $name,
        public ?string $firstName,
        public ?string $lastName,
        public ?string $phone,
        public ?string $email,
        public ?DateTimeImmutable $createdAt,
        public array $methods,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactSummary'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            name: $attributes->nullableString('name'),
            firstName: $attributes->nullableString('first_name'),
            lastName: $attributes->nullableString('last_name'),
            phone: $attributes->nullableString('phone'),
            email: $attributes->nullableString('email'),
            createdAt: $attributes->nullableDateTime('created_at'),
            methods: $attributes->list('methods', DuplicateRefMethod::fromArray(...)),
            raw: $data,
        );
    }
}
