<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Aggregated external links for a single contact.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactIntegrationsResponse)
 */
final readonly class ContactIntegrations extends Data
{
    /**
     * @param  list<ContactIntegrationLink>  $items
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $items,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactIntegrations'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            items: $attributes->list('items', ContactIntegrationLink::fromArray(...)),
            raw: $data,
        );
    }
}
