<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Enums\FieldType;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for a single contact's custom field value.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactFieldValue)
 */
final readonly class ContactFieldValue extends Data
{
    /**
     * @param  string  $fieldId  Custom field definition ID
     * @param  string  $fieldKey  Field key
     * @param  string  $fieldName  Field display name
     * @param  FieldType|string  $fieldType  Field data type
     * @param  mixed  $value  Current value
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $fieldId,
        public string $fieldKey,
        public string $fieldName,
        public FieldType|string $fieldType,
        public mixed $value,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactFieldValue'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            fieldId: $attributes->string('field_id'),
            fieldKey: $attributes->string('field_key'),
            fieldName: $attributes->string('field_name'),
            fieldType: $attributes->enum('field_type', FieldType::class),
            value: $data['value'] ?? null,
            raw: $data,
        );
    }
}
