<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Keyset-paginated, newest-first list of ALL media exchanged with a contact across every
 * conversation.
 *
 * Pagination is keyset/cursor only (DESC by (created_at, message_id)). next_cursor is the opaque
 * cursor of the LAST returned item when has_more is true, otherwise null.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactAttachmentsResponse)
 */
final readonly class ContactAttachments extends Data
{
    /**
     * @param  list<ContactAttachmentItem>  $items  Media items, newest first
     * @param  ?string  $nextCursor  Opaque cursor for the next (older) page; null when no more
     * @param  ?bool  $hasMore  Whether older media exist beyond this page
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $items,
        public ?string $nextCursor,
        public ?bool $hasMore,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactAttachments'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            items: $attributes->list('items', ContactAttachmentItem::fromArray(...)),
            nextCursor: $attributes->nullableString('next_cursor'),
            hasMore: $attributes->nullableBool('has_more'),
            raw: $data,
        );
    }
}
