<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Progress + final result for an async contact export job.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactExportStatusResponse)
 */
final readonly class ContactExportStatus extends Data
{
    /**
     * @param  list<string>  $columns  Ordered export column headers; present when completed
     * @param  ?string  $downloadUrl  Relative download URL (302 to a signed URL); present when completed
     * @param  ?string  $errorMessage  Present when status == failed
     * @param  ?string  $filename  Download filename; present once status == completed
     * @param  ?string  $format  csv | xlsx (once known)
     * @param  ?string  $message  Human-readable status message
     * @param  ?int  $processedItems  Contacts written so far
     * @param  ?int  $progressPercent  0-100
     * @param  string  $status  queued | processing | completed | failed | cancelled
     * @param  ?int  $totalContacts  Contacts in the finished file; present when completed
     * @param  ?int  $totalItems  Total contacts matched by the filters
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $columns,
        public ?string $downloadUrl,
        public ?string $errorMessage,
        public ?string $filename,
        public ?string $format,
        public string $jobId,
        public ?string $message,
        public ?int $processedItems,
        public ?int $progressPercent,
        public string $status,
        public ?int $totalContacts,
        public ?int $totalItems,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactExportStatus'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            columns: $attributes->strings('columns'),
            downloadUrl: $attributes->nullableString('download_url'),
            errorMessage: $attributes->nullableString('error_message'),
            filename: $attributes->nullableString('filename'),
            format: $attributes->nullableString('format'),
            jobId: $attributes->string('job_id'),
            message: $attributes->nullableString('message'),
            processedItems: $attributes->nullableInt('processed_items'),
            progressPercent: $attributes->nullableInt('progress_percent'),
            status: $attributes->string('status'),
            totalContacts: $attributes->nullableInt('total_contacts'),
            totalItems: $attributes->nullableInt('total_items'),
            raw: $data,
        );
    }
}
