<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for a contact method
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ContactMethodResponse)
 */
final readonly class ContactMethod extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $bounceCount,
        public ?string $channelId,
        public string $contactId,
        public ?DateTimeImmutable $createdAt,
        public ?string $displayName,
        public ?string $emailStatus,
        public string $id,
        public ?bool $isPrimary,
        public ?DateTimeImmutable $lastBounceAt,
        public ?DateTimeImmutable $lastUsedAt,
        public string $methodType,
        public ?string $phoneType,
        public string $value,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'contactMethod'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            bounceCount: $attributes->nullableInt('bounce_count'),
            channelId: $attributes->nullableString('channel_id'),
            contactId: $attributes->string('contact_id'),
            createdAt: $attributes->nullableDateTime('created_at'),
            displayName: $attributes->nullableString('display_name'),
            emailStatus: $attributes->nullableString('email_status'),
            id: $attributes->string('id'),
            isPrimary: $attributes->nullableBool('is_primary'),
            lastBounceAt: $attributes->nullableDateTime('last_bounce_at'),
            lastUsedAt: $attributes->nullableDateTime('last_used_at'),
            methodType: $attributes->string('method_type'),
            phoneType: $attributes->nullableString('phone_type'),
            value: $attributes->string('value'),
            raw: $data,
        );
    }
}
