<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Summary of a previously crawled domain for re-crawl selection.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema CrawlDomainSummary)
 */
final readonly class CrawlDomainSummary extends Data
{
    /**
     * @param  string  $baseUrl  Full base URL used for crawl
     * @param  string  $crawledAt  ISO datetime when crawl completed
     * @param  ?int  $daysSinceCrawl  Days since last crawl
     * @param  string  $domain  Domain name (e.g., docs.example.com)
     * @param  string  $id  History record ID
     * @param  ?bool  $isEligibleForRecrawl  Whether this domain is eligible for bulk re-crawl (must be 14+ days old)
     * @param  int  $pageCount  Number of pages in stored list
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $baseUrl,
        public string $crawledAt,
        public ?int $daysSinceCrawl,
        public string $domain,
        public string $id,
        public ?bool $isEligibleForRecrawl,
        public int $pageCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'crawlDomainSummary'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            baseUrl: $attributes->string('base_url'),
            crawledAt: $attributes->string('crawled_at'),
            daysSinceCrawl: $attributes->nullableInt('days_since_crawl'),
            domain: $attributes->string('domain'),
            id: $attributes->string('id'),
            isEligibleForRecrawl: $attributes->nullableBool('is_eligible_for_recrawl'),
            pageCount: $attributes->int('page_count'),
            raw: $data,
        );
    }
}
