<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for resource deletion
 *
 * @see https://api.sendseven.com/api/v1/docs (schema DeleteResponse)
 */
final readonly class Delete extends Data
{
    /**
     * @param  string  $id  ID of deleted resource
     * @param  ?bool  $success  Whether deletion succeeded
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public ?string $message,
        public ?bool $success,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'delete'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            message: $attributes->nullableString('message'),
            success: $attributes->nullableBool('success'),
            raw: $data,
        );
    }
}
