<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * DNS record for domain verification
 *
 * @see https://api.sendseven.com/api/v1/docs (schema DnsRecordResponse)
 */
final readonly class DnsRecord extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public bool $isVerified,
        public ?DateTimeImmutable $lastCheckAt,
        public string $recordName,
        public string $recordType,
        public string $recordValue,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'dnsRecord'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            isVerified: $attributes->bool('is_verified'),
            lastCheckAt: $attributes->nullableDateTime('last_check_at'),
            recordName: $attributes->string('record_name'),
            recordType: $attributes->string('record_type'),
            recordValue: $attributes->string('record_value'),
            raw: $data,
        );
    }
}
