<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for single document move operation.
 *
 * Includes document data and information about corpus move status.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema DocumentMoveResponse)
 */
final readonly class DocumentMove extends Data
{
    /**
     * @param  ?bool  $corpusMoved  Whether the Vertex AI corpus was updated. If false, AI search may not work correctly.
     * @param  string  $createdAt  ISO datetime when created
     * @param  string  $documentType  Document type
     * @param  ?string  $folderId  New folder ID
     * @param  ?string  $geminiFileName  RAG file reference
     * @param  ?string  $geminiStoreName  Vertex AI RAG Corpus name
     * @param  string  $id  Document ID
     * @param  ?string  $sourceUrl  Source URL if applicable
     * @param  string  $tenantId  Tenant ID
     * @param  string  $title  Document title
     * @param  string  $updatedAt  ISO datetime when last updated
     * @param  ?string  $uploadedByUserId  User who uploaded
     * @param  ?string  $warning  Warning message if corpus move had issues
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $corpusMoved,
        public string $createdAt,
        public string $documentType,
        public ?string $folderId,
        public ?string $geminiFileName,
        public ?string $geminiStoreName,
        public string $id,
        public ?string $sourceUrl,
        public string $tenantId,
        public string $title,
        public string $updatedAt,
        public ?string $uploadedByUserId,
        public ?string $warning,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'documentMove'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            corpusMoved: $attributes->nullableBool('corpus_moved'),
            createdAt: $attributes->string('created_at'),
            documentType: $attributes->string('document_type'),
            folderId: $attributes->nullableString('folder_id'),
            geminiFileName: $attributes->nullableString('gemini_file_name'),
            geminiStoreName: $attributes->nullableString('gemini_store_name'),
            id: $attributes->string('id'),
            sourceUrl: $attributes->nullableString('source_url'),
            tenantId: $attributes->string('tenant_id'),
            title: $attributes->string('title'),
            updatedAt: $attributes->string('updated_at'),
            uploadedByUserId: $attributes->nullableString('uploaded_by_user_id'),
            warning: $attributes->nullableString('warning'),
            raw: $data,
        );
    }
}
