<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response after sending confirmation email
 *
 * @see https://api.sendseven.com/api/v1/docs (schema DoubleOptInSendResponse)
 */
final readonly class DoubleOptInSend extends Data
{
    /**
     * @param  string  $email  Email address confirmation was sent to
     * @param  DateTimeImmutable  $expiresAt  When the token expires
     * @param  string  $message  Success message
     * @param  string  $tokenId  Unique token ID
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $email,
        public DateTimeImmutable $expiresAt,
        public string $message,
        public string $tokenId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'doubleOptInSend'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            email: $attributes->string('email'),
            expiresAt: $attributes->dateTime('expires_at'),
            message: $attributes->string('message'),
            tokenId: $attributes->string('token_id'),
            raw: $data,
        );
    }
}
