<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Light-weight contact reference returned in duplicate-detection responses.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema DuplicateRef)
 */
final readonly class DuplicateRef extends Data
{
    /**
     * @param  list<DuplicateRefMethod>  $methods
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $email,
        public string $id,
        public array $methods,
        public ?string $name,
        public ?string $phone,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'duplicateRef'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            email: $attributes->nullableString('email'),
            id: $attributes->string('id'),
            methods: $attributes->list('methods', DuplicateRefMethod::fromArray(...)),
            name: $attributes->nullableString('name'),
            phone: $attributes->nullableString('phone'),
            raw: $data,
        );
    }
}
