<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for listing email connections
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailConnectionListResponse)
 */
final readonly class EmailConnectionList extends Data
{
    /**
     * @param  list<EmailConnection>  $connections  List of email connections
     * @param  int  $total  Total number of connections
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $connections,
        public int $total,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailConnectionList'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            connections: $attributes->list('connections', EmailConnection::fromArray(...)),
            total: $attributes->int('total'),
            raw: $data,
        );
    }
}
