<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for create integration - includes DNS records for SES
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailIntegrationCreateResponse)
 */
final readonly class EmailIntegrationCreateResponse extends Data
{
    /**
     * @param  list<SesSetupDnsRecord>  $dnsRecords
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $name,
        public ?string $emailAddress,
        public ?string $oAuthEmail,
        public string $integrationType,
        public bool $isActive,
        public string $connectionStatus,
        public ?string $sesTenantName,
        public ?string $sesConfigurationSet,
        public ?string $sesDomain,
        public ?string $sesReputationPolicy,
        public ?string $dnsVerificationStatus,
        public array $dnsRecords,
        public ?string $setupMessage,
        public DateTimeImmutable $createdAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailIntegrationCreateResponse'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            name: $attributes->string('name'),
            emailAddress: $attributes->nullableString('email_address'),
            oAuthEmail: $attributes->nullableString('oauth_email'),
            integrationType: $attributes->string('integration_type'),
            isActive: $attributes->bool('is_active'),
            connectionStatus: $attributes->string('connection_status'),
            sesTenantName: $attributes->nullableString('ses_tenant_name'),
            sesConfigurationSet: $attributes->nullableString('ses_configuration_set'),
            sesDomain: $attributes->nullableString('ses_domain'),
            sesReputationPolicy: $attributes->nullableString('ses_reputation_policy'),
            dnsVerificationStatus: $attributes->nullableString('dns_verification_status'),
            dnsRecords: $attributes->list('dns_records', SesSetupDnsRecord::fromArray(...)),
            setupMessage: $attributes->nullableString('setup_message'),
            createdAt: $attributes->dateTime('created_at'),
            raw: $data,
        );
    }
}
