<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Detailed campaign analytics response
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailCampaignAnalyticsResponse)
 */
final readonly class EmailCampaignAnalytics extends Data
{
    /**
     * @param  array<array-key, mixed>  $sendsByHour
     * @param  array<array-key, mixed>  $opensByHour
     * @param  array<array-key, mixed>  $clicksByHour
     * @param  list<mixed>  $topLinks
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $campaignId,
        public string $emailCampaignId,
        public ?int $totalRecipients,
        public ?int $sentCount,
        public ?int $deliveredCount,
        public ?int $openedCount,
        public ?int $clickedCount,
        public ?int $bouncedCount,
        public ?int $complainedCount,
        public ?int $failedCount,
        public ?int $heldCount,
        public ?float $deliveryRate,
        public ?float $openRate,
        public ?float $clickRate,
        public ?float $clickToOpenRate,
        public ?float $bounceRate,
        public ?float $complaintRate,
        public array $sendsByHour,
        public array $opensByHour,
        public array $clicksByHour,
        public array $topLinks,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailCampaignAnalytics'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            campaignId: $attributes->string('campaign_id'),
            emailCampaignId: $attributes->string('email_campaign_id'),
            totalRecipients: $attributes->nullableInt('total_recipients'),
            sentCount: $attributes->nullableInt('sent_count'),
            deliveredCount: $attributes->nullableInt('delivered_count'),
            openedCount: $attributes->nullableInt('opened_count'),
            clickedCount: $attributes->nullableInt('clicked_count'),
            bouncedCount: $attributes->nullableInt('bounced_count'),
            complainedCount: $attributes->nullableInt('complained_count'),
            failedCount: $attributes->nullableInt('failed_count'),
            heldCount: $attributes->nullableInt('held_count'),
            deliveryRate: $attributes->nullableFloat('delivery_rate'),
            openRate: $attributes->nullableFloat('open_rate'),
            clickRate: $attributes->nullableFloat('click_rate'),
            clickToOpenRate: $attributes->nullableFloat('click_to_open_rate'),
            bounceRate: $attributes->nullableFloat('bounce_rate'),
            complaintRate: $attributes->nullableFloat('complaint_rate'),
            sendsByHour: $attributes->array('sends_by_hour'),
            opensByHour: $attributes->array('opens_by_hour'),
            clicksByHour: $attributes->array('clicks_by_hour'),
            topLinks: array_values($attributes->array('top_links')),
            raw: $data,
        );
    }
}
