<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Full email content response with variable system
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailContentResponse)
 */
final readonly class EmailContent extends Data
{
    /**
     * @param  ?bool  $aiGenerated  AI-generated flag
     * @param  ?int  $aiGenerationCostCents  AI cost
     * @param  ?string  $aiModelUsed  AI model
     * @param  ?string  $aiPrompt  AI prompt
     * @param  ?string  $compiledHtml  Compiled HTML content from Stripo or MJML compilation
     * @param  ?string  $contentType  Content type: 'html' or 'plain_text'
     * @param  DateTimeImmutable  $createdAt  Creation timestamp
     * @param  ?string  $createdBy  Creator user ID
     * @param  ?string  $description  Content description
     * @param  ?string  $editorType  Editor type: 'stripo' or 'mjml' (legacy)
     * @param  ?string  $footerMode  Compliance footer override for this email: `inherit` (default — use the account setting), `both` (unsubscribe + manage preferences), `unsubscribe_only`, or `none` (no visible footer, for transactional mail). RFC 8058 List-Unsubscribe headers are sent regardless.
     * @param  ?string  $fromEmail  Sender email
     * @param  ?string  $fromName  Sender name
     * @param  string  $id  Unique identifier (UUID)
     * @param  ?bool  $isSystem  System template flag
     * @param  bool  $isValid  Validation status
     * @param  ?LayoutTemplateInfo  $layoutTemplate  Layout template info
     * @param  ?string  $mjmlSource  Full MJML content (legacy, html type only)
     * @param  string  $name  Content name
     * @param  ?string  $previewText  Preview text
     * @param  ?string  $stripoDesignJson  Stripo editor design JSON for re-opening designs
     * @param  ?string  $subjectLine  Email subject line
     * @param  ?string  $templateId  Email template ID
     * @param  string  $tenantId  Tenant this resource belongs to
     * @param  ?string  $textBody  Plain text template content (plain_text type only)
     * @param  DateTimeImmutable  $updatedAt  Last update timestamp
     * @param  list<string>  $validationErrors  Validation errors
     * @param  array<array-key, mixed>  $variableValues  Variable values
     * @param  list<string>  $variablesUsed  Extracted variables
     * @param  int  $version  Content version
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $aiGenerated,
        public ?int $aiGenerationCostCents,
        public ?string $aiModelUsed,
        public ?string $aiPrompt,
        public ?string $compiledHtml,
        public ?string $contentType,
        public DateTimeImmutable $createdAt,
        public ?string $createdBy,
        public ?string $description,
        public ?string $editorType,
        public ?string $footerMode,
        public ?string $fromEmail,
        public ?string $fromName,
        public string $id,
        public ?bool $isSystem,
        public bool $isValid,
        public ?LayoutTemplateInfo $layoutTemplate,
        public ?string $mjmlSource,
        public string $name,
        public ?string $previewText,
        public ?string $stripoDesignJson,
        public ?string $subjectLine,
        public ?string $templateId,
        public string $tenantId,
        public ?string $textBody,
        public DateTimeImmutable $updatedAt,
        public array $validationErrors,
        public array $variableValues,
        public array $variablesUsed,
        public int $version,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailContent'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            aiGenerated: $attributes->nullableBool('ai_generated'),
            aiGenerationCostCents: $attributes->nullableInt('ai_generation_cost_cents'),
            aiModelUsed: $attributes->nullableString('ai_model_used'),
            aiPrompt: $attributes->nullableString('ai_prompt'),
            compiledHtml: $attributes->nullableString('compiled_html'),
            contentType: $attributes->nullableString('content_type'),
            createdAt: $attributes->dateTime('created_at'),
            createdBy: $attributes->nullableString('created_by'),
            description: $attributes->nullableString('description'),
            editorType: $attributes->nullableString('editor_type'),
            footerMode: $attributes->nullableString('footer_mode'),
            fromEmail: $attributes->nullableString('from_email'),
            fromName: $attributes->nullableString('from_name'),
            id: $attributes->string('id'),
            isSystem: $attributes->nullableBool('is_system'),
            isValid: $attributes->bool('is_valid'),
            layoutTemplate: $attributes->nullableObject('layout_template', LayoutTemplateInfo::fromArray(...)),
            mjmlSource: $attributes->nullableString('mjml_source'),
            name: $attributes->string('name'),
            previewText: $attributes->nullableString('preview_text'),
            stripoDesignJson: $attributes->nullableString('stripo_design_json'),
            subjectLine: $attributes->nullableString('subject_line'),
            templateId: $attributes->nullableString('template_id'),
            tenantId: $attributes->string('tenant_id'),
            textBody: $attributes->nullableString('text_body'),
            updatedAt: $attributes->dateTime('updated_at'),
            validationErrors: $attributes->strings('validation_errors'),
            variableValues: $attributes->array('variable_values'),
            variablesUsed: $attributes->strings('variables_used'),
            version: $attributes->int('version'),
            raw: $data,
        );
    }
}
