<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Email address with optional display name
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailAddress)
 */
final readonly class EmailAddress extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $email,
        public ?string $name,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailAddress'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            email: $attributes->string('email'),
            name: $attributes->nullableString('name'),
            raw: $data,
        );
    }
}
