<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Enums\OptInMethodEnum;
use Reshapify\SendSeven\Enums\SubscriptionStatusEnum;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Schema for email contact details
 *
 * @see https://api.sendseven.com/api/v1/docs (schema EmailContactResponse)
 */
final readonly class EmailContact extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $contactId,
        public DateTimeImmutable $createdAt,
        public string $email,
        public string $id,
        public ?string $name,
        public ?DateTimeImmutable $optInConfirmedAt,
        public OptInMethodEnum|string $optInMethod,
        public ?string $phone,
        public string $subscriptionCategory,
        public SubscriptionStatusEnum|string $subscriptionStatus,
        public string $tenantId,
        public ?DateTimeImmutable $unsubscribedAt,
        public DateTimeImmutable $updatedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'emailContact'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            contactId: $attributes->string('contact_id'),
            createdAt: $attributes->dateTime('created_at'),
            email: $attributes->string('email'),
            id: $attributes->string('id'),
            name: $attributes->nullableString('name'),
            optInConfirmedAt: $attributes->nullableDateTime('opt_in_confirmed_at'),
            optInMethod: $attributes->enum('opt_in_method', OptInMethodEnum::class),
            phone: $attributes->nullableString('phone'),
            subscriptionCategory: $attributes->string('subscription_category'),
            subscriptionStatus: $attributes->enum('subscription_status', SubscriptionStatusEnum::class),
            tenantId: $attributes->string('tenant_id'),
            unsubscribedAt: $attributes->nullableDateTime('unsubscribed_at'),
            updatedAt: $attributes->dateTime('updated_at'),
            raw: $data,
        );
    }
}
