<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Info about an existing closed conversation that could be reopened
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ExistingConversationInfo)
 */
final readonly class ExistingConversationInfo extends Data
{
    /**
     * @param  ?string  $closedAt  When the conversation was closed
     * @param  string  $conversationId  Existing conversation ID
     * @param  ?string  $lastMessageAt  When the last message was sent/received
     * @param  ?int  $messageCount  Number of messages in the conversation
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $closedAt,
        public string $conversationId,
        public ?string $lastMessageAt,
        public ?int $messageCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'existingConversationInfo'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            closedAt: $attributes->nullableString('closed_at'),
            conversationId: $attributes->string('conversation_id'),
            lastMessageAt: $attributes->nullableString('last_message_at'),
            messageCount: $attributes->nullableInt('message_count'),
            raw: $data,
        );
    }
}
