<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * The parameters a run was started with (echoed back on start/status).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema FAQMigrationParams)
 */
final readonly class FaqMigrationParams extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $dryRun,
        public ?int $limit,
        public ?int $maxClusters,
        public ?int $minClusterSize,
        public ?bool $includeSingletons,
        public ?bool $retireFolderWhenDone,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'faqMigrationParams'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            dryRun: $attributes->nullableBool('dry_run'),
            limit: $attributes->nullableInt('limit'),
            maxClusters: $attributes->nullableInt('max_clusters'),
            minClusterSize: $attributes->nullableInt('min_cluster_size'),
            includeSingletons: $attributes->nullableBool('include_singletons'),
            retireFolderWhenDone: $attributes->nullableBool('retire_folder_when_done'),
            raw: $data,
        );
    }
}
