<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Information about a screen in a flow
 *
 * @see https://api.sendseven.com/api/v1/docs (schema FlowScreenInfo)
 */
final readonly class FlowScreenInfo extends Data
{
    /**
     * @param  list<FlowFieldInfo>  $fields  Input fields on this screen
     * @param  string  $id  Screen ID
     * @param  ?string  $title  Screen title
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $fields,
        public string $id,
        public ?string $title,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'flowScreenInfo'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            fields: $attributes->list('fields', FlowFieldInfo::fromArray(...)),
            id: $attributes->string('id'),
            title: $attributes->nullableString('title'),
            raw: $data,
        );
    }
}
