<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * One structured publish-time validation error.
 *
 * path is a best-effort dotted/bracketed locator (e.g. "nodes[sales_bot].bot_id" or
 * "trigger.recurrence_rule") so the Flows editor can highlight the offending node / trigger inline
 * without re-running save-then-fail. Graph-level errors (orphan node, unreachable from entry,
 * cycle) carry path="" and the human-readable message stays in message.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema FlowValidationError)
 */
final readonly class FlowValidationError extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $message,
        public ?string $path,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'flowValidationError'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            message: $attributes->string('message'),
            path: $attributes->nullableString('path'),
            raw: $data,
        );
    }
}
