<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Body of GET /flows/{id}/observability/funnel.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema FunnelResponse)
 */
final readonly class Funnel extends Data
{
    /**
     * @param  list<FunnelItem>  $items
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $items,
        public int $totalEntered,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'funnel'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            items: $attributes->list('items', FunnelItem::fromArray(...)),
            totalEntered: $attributes->int('total_entered'),
            raw: $data,
        );
    }
}
