<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Single row in the funnel — one node in canvas order.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema FunnelItem)
 */
final readonly class FunnelItem extends Data
{
    /**
     * @param  ?float  $dropFromPrevious  Fraction of contacts who reached the previous node but not this one. ``0.0`` for the first row and whenever the previous count was zero.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $count,
        public ?float $dropFromPrevious,
        public string $nodeId,
        public string $nodeName,
        public string $nodeType,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'funnelItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            count: $attributes->int('count'),
            dropFromPrevious: $attributes->nullableFloat('drop_from_previous'),
            nodeId: $attributes->string('node_id'),
            nodeName: $attributes->string('node_name'),
            nodeType: $attributes->string('node_type'),
            raw: $data,
        );
    }
}
