<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * HubSpotStatusResponse from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema HubSpotStatusResponse)
 */
final readonly class HubSpotStatus extends Data
{
    /**
     * @param  ?string  $status  pending | active | suspended | disconnected
     * @param  list<string>  $grantedScopes
     * @param  array<array-key, mixed>  $syncDirectionConfig
     * @param  array<array-key, mixed>  $fieldMapping
     * @param  array<array-key, mixed>  $contactMethodMapping  Category-based mapping: {"contact_methods": {hubspot_property: [target, ...]}, "social_profiles": {hubspot_property: [target, ...]}}. Targets are contact-method/social-profile enum values (email/whatsapp_id/phone for contact_methods; linkedin/instagram_handle/facebook/homepage/social_other for social_profiles). One HubSpot property may map to MULTIPLE targets (e.g. HubSpot 'phone' -> both 'phone' and 'whatsapp_id').
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $connected,
        public ?bool $isConnected,
        public ?int $portalId,
        public ?string $syncDirection,
        public ?bool $syncTranscripts,
        public ?string $connectedAt,
        public ?string $status,
        public ?int $hubId,
        public ?string $hubDomain,
        public array $grantedScopes,
        public array $syncDirectionConfig,
        public array $fieldMapping,
        public array $contactMethodMapping,
        public ?bool $sendsevenLinkCompleted,
        public ?int $linkedContacts,
        public ?string $lastFullSyncAt,
        public ?string $installedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'hubSpotStatus'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            connected: $attributes->bool('connected'),
            isConnected: $attributes->nullableBool('is_connected'),
            portalId: $attributes->nullableInt('portal_id'),
            syncDirection: $attributes->nullableString('sync_direction'),
            syncTranscripts: $attributes->nullableBool('sync_transcripts'),
            connectedAt: $attributes->nullableString('connected_at'),
            status: $attributes->nullableString('status'),
            hubId: $attributes->nullableInt('hub_id'),
            hubDomain: $attributes->nullableString('hub_domain'),
            grantedScopes: $attributes->strings('granted_scopes'),
            syncDirectionConfig: $attributes->array('sync_direction_config'),
            fieldMapping: $attributes->array('field_mapping'),
            contactMethodMapping: $attributes->array('contact_method_mapping'),
            sendsevenLinkCompleted: $attributes->nullableBool('sendseven_link_completed'),
            linkedContacts: $attributes->nullableInt('linked_contacts'),
            lastFullSyncAt: $attributes->nullableString('last_full_sync_at'),
            installedAt: $attributes->nullableString('installed_at'),
            raw: $data,
        );
    }
}
