<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * HubSpotSegmentPreviewResponse from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema HubSpotSegmentPreviewResponse)
 */
final readonly class HubSpotSegmentPreview extends Data
{
    /**
     * @param  int  $totalMembers  HubSpot members inspected (capped when sampled)
     * @param  int  $resolvedContacts  Members matched to an existing SendSeven contact
     * @param  int  $wouldCreate  Members that would auto-create a new contact
     * @param  int  $unresolvedMembers  Members skipped (no usable identifier / policy=skip)
     * @param  bool  $sampled  True when only a sample of the list was inspected
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $totalMembers,
        public int $resolvedContacts,
        public int $wouldCreate,
        public int $unresolvedMembers,
        public bool $sampled,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'hubSpotSegmentPreview'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            totalMembers: $attributes->int('total_members'),
            resolvedContacts: $attributes->int('resolved_contacts'),
            wouldCreate: $attributes->int('would_create'),
            unresolvedMembers: $attributes->int('unresolved_members'),
            sampled: $attributes->bool('sampled'),
            raw: $data,
        );
    }
}
