<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * HubSpotContactSyncFilterList from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema HubSpotContactSyncFilterList)
 */
final readonly class HubSpotContactSyncFilterList extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $hubSpotListId,
        public ?string $listName,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'hubSpotContactSyncFilterList'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            hubSpotListId: $attributes->string('hubspot_list_id'),
            listName: $attributes->nullableString('list_name'),
            raw: $data,
        );
    }
}
