<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * HubSpotContactSyncFilterProperties from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema HubSpotContactSyncFilterProperties)
 */
final readonly class HubSpotContactSyncFilterProperties extends Data
{
    /**
     * @param  list<HubSpotSearchFilterGroupSchema>  $filterGroups
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $filterGroups,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'hubSpotContactSyncFilterProperties'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            filterGroups: $attributes->list('filter_groups', HubSpotSearchFilterGroupSchema::fromArray(...)),
            raw: $data,
        );
    }
}
