<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Returned by POST /email-contacts/import (202 Accepted).
 *
 * The import now runs in a background worker so large CSVs no longer hit the request/proxy
 * timeout. Poll poll_url (or call getImportStatus(job_id)) until status is completed or failed.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ImportJobStartResponse)
 */
final readonly class ImportJobStart extends Data
{
    /**
     * @param  string  $jobId  PubSubJob id; use to poll status
     * @param  string  $message  Human-readable status message
     * @param  string  $pollUrl  Relative URL to poll for progress
     * @param  ?string  $status  Initial job status
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $jobId,
        public string $message,
        public string $pollUrl,
        public ?string $status,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'importJobStart'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            jobId: $attributes->string('job_id'),
            message: $attributes->string('message'),
            pollUrl: $attributes->string('poll_url'),
            status: $attributes->nullableString('status'),
            raw: $data,
        );
    }
}
