<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Email connection assigned to an inbox, with optional alias subset.
 *
 * allowed_recipients semantics (catchall subset filter): - None or [] -> the inbox accepts every
 * address this connection can receive on (its email_address plus everything in accepted_aliases).
 * - non-empty list -> the inbox routes only inbound conversations whose
 * Conversation.recipient_address is one of the listed values. Each entry MUST be in the
 * connection's email_address ∪ accepted_aliases; the service enforces this.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema InboxEmailConnection)
 */
final readonly class InboxEmailConnection extends Data
{
    /**
     * @param  string  $emailIntegrationId  Email integration row id (the receiving connection — must have can_receive_support=True).
     * @param  list<string>  $allowedRecipients  Optional subset of addresses on the connection to route to this inbox. None or empty list = all addresses.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $emailIntegrationId,
        public array $allowedRecipients,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'inboxEmailConnection'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            emailIntegrationId: $attributes->string('email_integration_id'),
            allowedRecipients: $attributes->strings('allowed_recipients'),
            raw: $data,
        );
    }
}
