<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response after uploading inline image
 *
 * @see https://api.sendseven.com/api/v1/docs (schema InlineImageUploadResponse)
 */
final readonly class InlineImageUpload extends Data
{
    /**
     * @param  string  $contentId  Content-ID for use in HTML (cid:xxx)
     * @param  string  $url  Signed URL for preview
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $attachmentId,
        public string $contentId,
        public string $url,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'inlineImageUpload'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            attachmentId: $attributes->string('attachment_id'),
            contentId: $attributes->string('content_id'),
            url: $attributes->string('url'),
            raw: $data,
        );
    }
}
