<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Unified list response for the integrations catalog.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema IntegrationCatalogResponse)
 */
final readonly class IntegrationCatalog extends Data
{
    /**
     * @param  list<IntegrationCatalogEntry>  $items  Available integrations
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $items,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'integrationCatalog'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            items: $attributes->list('items', IntegrationCatalogEntry::fromArray(...)),
            raw: $data,
        );
    }
}
