<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Outbound interactive message content (WhatsApp-style Meta format).
 *
 * Mirrors the object an adapter sends and is persisted verbatim under messages.meta.interactive by
 * the flow Send-node handler. The conversation UI + flow test panel render an interactive bubble
 * from this shape (MessageBubble.getInteractiveContent).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema InteractiveContent)
 */
final readonly class InteractiveContent extends Data
{
    /**
     * @param  array<array-key, mixed>  $action  Action object: {buttons:[...]} or {button, sections:[...]}
     * @param  array<array-key, mixed>  $body  Body object: {text: ...}
     * @param  array<array-key, mixed>  $footer  Footer object: {text: ...}
     * @param  array<array-key, mixed>  $header  Header object (text or media), Meta format
     * @param  ?string  $type  Interactive type: 'button' or 'list'
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $action,
        public array $body,
        public array $footer,
        public array $header,
        public ?string $type,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'interactiveContent'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            action: $attributes->array('action'),
            body: $attributes->array('body'),
            footer: $attributes->array('footer'),
            header: $attributes->array('header'),
            type: $attributes->nullableString('type'),
            raw: $data,
        );
    }
}
