<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Enums\InvitationStatusEnum;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Schema for invitation response
 *
 * @see https://api.sendseven.com/api/v1/docs (schema InvitationResponse)
 */
final readonly class Invitation extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $email,
        public string $invitedRole,
        public string $invitedByUserId,
        public string $invitationToken,
        public InvitationStatusEnum|string $status,
        public DateTimeImmutable $expiresAt,
        public ?DateTimeImmutable $acceptedAt,
        public ?DateTimeImmutable $declinedAt,
        public DateTimeImmutable $createdAt,
        public ?DateTimeImmutable $updatedAt,
        public ?string $tenantName,
        public ?string $invitedByName,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'invitation'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            email: $attributes->string('email'),
            invitedRole: $attributes->string('invited_role'),
            invitedByUserId: $attributes->string('invited_by_user_id'),
            invitationToken: $attributes->string('invitation_token'),
            status: $attributes->enum('status', InvitationStatusEnum::class),
            expiresAt: $attributes->dateTime('expires_at'),
            acceptedAt: $attributes->nullableDateTime('accepted_at'),
            declinedAt: $attributes->nullableDateTime('declined_at'),
            createdAt: $attributes->dateTime('created_at'),
            updatedAt: $attributes->nullableDateTime('updated_at'),
            tenantName: $attributes->nullableString('tenant_name'),
            invitedByName: $attributes->nullableString('invited_by_name'),
            raw: $data,
        );
    }
}
