<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Single line item on an invoice
 *
 * @see https://api.sendseven.com/api/v1/docs (schema InvoiceLineItemResponse)
 */
final readonly class InvoiceLineItem extends Data
{
    /**
     * @param  string  $description  Human-readable description (e.g., 'WhatsApp Messages +49171231231')
     * @param  int  $quantity  Number of units
     * @param  string  $unitPriceEuros  Price per unit in EUR
     * @param  string  $totalEuros  Total amount in EUR (quantity x unit_price)
     * @param  string  $costType  Cost type identifier (e.g., 'message_whatsapp')
     * @param  ?string  $connectionIdentifier  Connection identifier (e.g., '@BotName', '+49171231231')
     * @param  int  $unitPriceCents  Unit price in cents for backward compatibility
     * @param  int  $totalCents  Total in cents for backward compatibility
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $description,
        public int $quantity,
        public string $unitPriceEuros,
        public string $totalEuros,
        public string $costType,
        public ?string $connectionIdentifier,
        public int $unitPriceCents,
        public int $totalCents,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'invoiceLineItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            description: $attributes->string('description'),
            quantity: $attributes->int('quantity'),
            unitPriceEuros: $attributes->string('unit_price_euros'),
            totalEuros: $attributes->string('total_euros'),
            costType: $attributes->string('cost_type'),
            connectionIdentifier: $attributes->nullableString('connection_identifier'),
            unitPriceCents: $attributes->int('unit_price_cents'),
            totalCents: $attributes->int('total_cents'),
            raw: $data,
        );
    }
}
