<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Full response model for a KB folder.
 *
 * Includes document count and recursive children for tree display.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema KBFolderResponse)
 */
final readonly class KbFolder extends Data
{
    /**
     * @param  list<KbFolder>  $children  Child folders (for tree structure)
     * @param  string  $createdAt  ISO datetime when created
     * @param  ?int  $documentCount  Number of documents directly in this folder
     * @param  ?bool  $hasCorpus  Whether a Vertex AI corpus exists for this folder
     * @param  string  $id  Unique identifier (UUID)
     * @param  ?bool  $isAiSearchable  Whether this folder is included in AI agent suggestions (/ai, /suggest)
     * @param  bool  $isSystem  Whether this is a system folder
     * @param  string  $name  Folder name
     * @param  ?string  $parentId  Parent folder ID
     * @param  string  $slug  URL-safe folder identifier
     * @param  int  $sortOrder  Display order within parent
     * @param  string  $tenantId  Tenant this resource belongs to
     * @param  string  $updatedAt  ISO datetime when last updated
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $children,
        public string $createdAt,
        public ?int $documentCount,
        public ?bool $hasCorpus,
        public string $id,
        public ?bool $isAiSearchable,
        public bool $isSystem,
        public string $name,
        public ?string $parentId,
        public string $slug,
        public int $sortOrder,
        public string $tenantId,
        public string $updatedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'kbFolder'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            children: $attributes->list('children', KbFolder::fromArray(...)),
            createdAt: $attributes->string('created_at'),
            documentCount: $attributes->nullableInt('document_count'),
            hasCorpus: $attributes->nullableBool('has_corpus'),
            id: $attributes->string('id'),
            isAiSearchable: $attributes->nullableBool('is_ai_searchable'),
            isSystem: $attributes->bool('is_system'),
            name: $attributes->string('name'),
            parentId: $attributes->nullableString('parent_id'),
            slug: $attributes->string('slug'),
            sortOrder: $attributes->int('sort_order'),
            tenantId: $attributes->string('tenant_id'),
            updatedAt: $attributes->string('updated_at'),
            raw: $data,
        );
    }
}
