<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * A FAQ entry as it appears in any KB-health bucket.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema KBHealthEntry)
 */
final readonly class KbHealthEntry extends Data
{
    /**
     * @param  list<string>  $duplicateOf
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $answerPreview,
        public ?DateTimeImmutable $contentUpdatedAt,
        public ?int $duplicateCount,
        public array $duplicateOf,
        public ?int $flaggedCount,
        public ?string $folderId,
        public string $id,
        public ?string $language,
        public ?DateTimeImmutable $lastUsedAt,
        public ?DateTimeImmutable $lastVerifiedAt,
        public ?float $negativeMass,
        public string $origin,
        public ?float $positiveMass,
        public ?float $qualityScore,
        public string $question,
        public ?string $staleReason,
        public string $status,
        public ?int $timesCited,
        public ?int $timesInSentReply,
        public ?int $timesRetrieved,
        public ?DateTimeImmutable $updatedAt,
        public ?bool $verifiedByUsage,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'kbHealthEntry'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            answerPreview: $attributes->nullableString('answer_preview'),
            contentUpdatedAt: $attributes->nullableDateTime('content_updated_at'),
            duplicateCount: $attributes->nullableInt('duplicate_count'),
            duplicateOf: $attributes->strings('duplicate_of'),
            flaggedCount: $attributes->nullableInt('flagged_count'),
            folderId: $attributes->nullableString('folder_id'),
            id: $attributes->string('id'),
            language: $attributes->nullableString('language'),
            lastUsedAt: $attributes->nullableDateTime('last_used_at'),
            lastVerifiedAt: $attributes->nullableDateTime('last_verified_at'),
            negativeMass: $attributes->nullableFloat('negative_mass'),
            origin: $attributes->string('origin'),
            positiveMass: $attributes->nullableFloat('positive_mass'),
            qualityScore: $attributes->nullableFloat('quality_score'),
            question: $attributes->string('question'),
            staleReason: $attributes->nullableString('stale_reason'),
            status: $attributes->string('status'),
            timesCited: $attributes->nullableInt('times_cited'),
            timesInSentReply: $attributes->nullableInt('times_in_sent_reply'),
            timesRetrieved: $attributes->nullableInt('times_retrieved'),
            updatedAt: $attributes->nullableDateTime('updated_at'),
            verifiedByUsage: $attributes->nullableBool('verified_by_usage'),
            raw: $data,
        );
    }
}
