<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * KbHealthTotals from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema KBHealthTotals)
 */
final readonly class KbHealthTotals extends Data
{
    /**
     * @param  ?int  $unscoredEntries  Entries with quality_score NULL — unknown, not bad
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $archived,
        public ?float $averageQualityScore,
        public ?int $draft,
        public ?int $needsReview,
        public ?int $openCorrections,
        public ?int $published,
        public ?int $scoredEntries,
        public ?int $totalEntries,
        public ?int $unscoredEntries,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'kbHealthTotals'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            archived: $attributes->nullableInt('archived'),
            averageQualityScore: $attributes->nullableFloat('average_quality_score'),
            draft: $attributes->nullableInt('draft'),
            needsReview: $attributes->nullableInt('needs_review'),
            openCorrections: $attributes->nullableInt('open_corrections'),
            published: $attributes->nullableInt('published'),
            scoredEntries: $attributes->nullableInt('scored_entries'),
            totalEntries: $attributes->nullableInt('total_entries'),
            unscoredEntries: $attributes->nullableInt('unscored_entries'),
            raw: $data,
        );
    }
}
