<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * The last outbound campaign message this contact received that belongs to the list (populated
 * only for unsubscribed events).
 *
 * attribution: - exact — the campaign targeted ONLY this list. - ambiguous — the campaign
 * targeted multiple lists, or was an all-contacts send (ignores_newsletter_subscriptions). - none
 * — no matching campaign message was found (all other fields are then null).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema LastMessageInList)
 */
final readonly class LastMessageInList extends Data
{
    /**
     * @param  ?string  $sentAt  ISO 8601 (Z); null when attribution is 'none'
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $attribution,
        public ?string $campaignId,
        public ?string $campaignName,
        public ?string $messageId,
        public ?string $preview,
        public ?string $sentAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'lastMessageInList'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            attribution: $attributes->string('attribution'),
            campaignId: $attributes->nullableString('campaign_id'),
            campaignName: $attributes->nullableString('campaign_name'),
            messageId: $attributes->nullableString('message_id'),
            preview: $attributes->nullableString('preview'),
            sentAt: $attributes->nullableString('sent_at'),
            raw: $data,
        );
    }
}
