<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * One entry in Meta's template library.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema LibraryTemplate)
 */
final readonly class LibraryTemplate extends Data
{
    /**
     * @param  ?string  $id  Meta's library template ID
     * @param  string  $name  Library template name — the value to pass as ``library_template_name`` when adopting (e.g. ``delivery_update_1``)
     * @param  string  $language  Meta language code, e.g. ``en_US``
     * @param  ?string  $category  UTILITY or AUTHENTICATION
     * @param  ?string  $topic  e.g. ``PAYMENTS``
     * @param  ?string  $usecase  e.g. ``LOW_BALANCE_WARNING``
     * @param  list<string>  $industry  e.g. ``["FINANCIAL_SERVICES"]``
     * @param  ?string  $header  Text header, if any
     * @param  string  $body  Body text with ``{{1}}`` placeholders
     * @param  ?string  $footer  Footer text, if any
     * @param  list<string>  $bodyParams  Meta's example values, index-aligned with the placeholders
     * @param  list<string>  $bodyParamTypes  Semantic type per placeholder, when Meta provides it
     * @param  list<LibraryTemplateButton>  $buttons
     * @param  ?bool  $alreadyAdded  True when this tenant already has a template with the same name and language on the selected channel. Set by the API, not by Meta.
     * @param  ?bool  $requiresInput  True when at least one button needs a customer-specific value (link URL, phone number). Meta's catalog ships placeholder destinations for those, so they cannot be adopted unchanged — the UI must collect the value first. False means the entry can be added with a single click.
     * @param  ?bool  $hasCallPermissionRequest  True when the entry includes a call permission request (asks the customer for permission to call them). Such a template can only be sent from a number with WhatsApp Calling turned on.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $id,
        public string $name,
        public string $language,
        public ?string $category,
        public ?string $topic,
        public ?string $usecase,
        public array $industry,
        public ?string $header,
        public string $body,
        public ?string $footer,
        public array $bodyParams,
        public array $bodyParamTypes,
        public array $buttons,
        public ?bool $alreadyAdded,
        public ?bool $requiresInput,
        public ?bool $hasCallPermissionRequest,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'libraryTemplate'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->nullableString('id'),
            name: $attributes->string('name'),
            language: $attributes->string('language'),
            category: $attributes->nullableString('category'),
            topic: $attributes->nullableString('topic'),
            usecase: $attributes->nullableString('usecase'),
            industry: $attributes->strings('industry'),
            header: $attributes->nullableString('header'),
            body: $attributes->string('body'),
            footer: $attributes->nullableString('footer'),
            bodyParams: $attributes->strings('body_params'),
            bodyParamTypes: $attributes->strings('body_param_types'),
            buttons: $attributes->list('buttons', LibraryTemplateButton::fromArray(...)),
            alreadyAdded: $attributes->nullableBool('already_added'),
            requiresInput: $attributes->nullableBool('requires_input'),
            hasCallPermissionRequest: $attributes->nullableBool('has_call_permission_request'),
            raw: $data,
        );
    }
}
