<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Subscription counts for a single list
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ListStatusBreakdown)
 */
final readonly class ListStatusBreakdown extends Data
{
    /**
     * @param  ?int  $bounced  Bounced subscriptions
     * @param  ?int  $complained  Spam-complained subscriptions
     * @param  string  $listId  List ID
     * @param  string  $listName  List name
     * @param  ?int  $pending  Pending confirmations
     * @param  ?int  $subscribed  Active subscriptions
     * @param  ?int  $total  Total subscriptions for this list
     * @param  ?int  $unsubscribed  Opted-out subscriptions
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $bounced,
        public ?int $complained,
        public string $listId,
        public string $listName,
        public ?int $pending,
        public ?int $subscribed,
        public ?int $total,
        public ?int $unsubscribed,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'listStatusBreakdown'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            bounced: $attributes->nullableInt('bounced'),
            complained: $attributes->nullableInt('complained'),
            listId: $attributes->string('list_id'),
            listName: $attributes->string('list_name'),
            pending: $attributes->nullableInt('pending'),
            subscribed: $attributes->nullableInt('subscribed'),
            total: $attributes->nullableInt('total'),
            unsubscribed: $attributes->nullableInt('unsubscribed'),
            raw: $data,
        );
    }
}
