<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from sending a live chat message
 *
 * @see https://api.sendseven.com/api/v1/docs (schema LiveChatMessageSendResponse)
 */
final readonly class LiveChatMessageSendResponse extends Data
{
    /**
     * @param  DateTimeImmutable  $createdAt  When the message was created
     * @param  string  $messageId  ID of the sent message
     * @param  bool  $success  Whether message was sent successfully
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public DateTimeImmutable $createdAt,
        public string $messageId,
        public bool $success,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'liveChatMessageSendResponse'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            createdAt: $attributes->dateTime('created_at'),
            messageId: $attributes->string('message_id'),
            success: $attributes->bool('success'),
            raw: $data,
        );
    }
}
