<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for POST /contacts/{id}/merge.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema MergeContactsResponse)
 */
final readonly class MergeContacts extends Data
{
    /**
     * @param  int  $mergedCount  Number of secondary contacts merged into the primary
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public Contact $contact,
        public int $mergedCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'mergeContacts'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            contact: $attributes->object('contact', Contact::fromArray(...)),
            mergedCount: $attributes->int('merged_count'),
            raw: $data,
        );
    }
}
