<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for POST /contacts/{id}/merge/preview — read-only, nothing is changed.
 *
 * A merge keeps a merged contact's running flows going on the surviving contact. A flow run is
 * only stopped when the surviving contact is already running the same flow, or when several merged
 * contacts run the same flow (one of them keeps running).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema MergeContactsPreviewResponse)
 */
final readonly class MergeContactsPreview extends Data
{
    /**
     * @param  list<MergeContactsPreviewFlow>  $cancelledFlows
     * @param  int  $flowRunsToCancel  Running flow runs the merge would stop
     * @param  int  $flowRunsToKeep  Running flow runs that would continue on the surviving contact
     * @param  string  $primaryContactId  The contact that would survive the merge
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $cancelledFlows,
        public int $flowRunsToCancel,
        public int $flowRunsToKeep,
        public string $primaryContactId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'mergeContactsPreview'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            cancelledFlows: $attributes->list('cancelled_flows', MergeContactsPreviewFlow::fromArray(...)),
            flowRunsToCancel: $attributes->int('flow_runs_to_cancel'),
            flowRunsToKeep: $attributes->int('flow_runs_to_keep'),
            primaryContactId: $attributes->string('primary_contact_id'),
            raw: $data,
        );
    }
}
