<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Outcome of resubscribing ONE Facebook Messenger Page to feed.
 *
 * The write-side counterpart to ChannelCommentCapability: the capability probe says a Messenger
 * page needs a resubscribe (resubscribe_required); this reports whether that resubscribe
 * succeeded. Instagram is never here — it needs a customer reconnect, which a resubscribe cannot
 * substitute for.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema MessengerResubscribeResult)
 */
final readonly class MessengerResubscribeResult extends Data
{
    /**
     * @param  bool  $ok  True when Facebook accepted the `subscribed_apps` update.
     * @param  string  $reason  Stable machine code: `resubscribed` (success), `missing_credentials`, `graph_error`.
     * @param  ?string  $detail  Human-readable explanation (English; UI translates by `reason`).
     * @param  list<string>  $subscribedFields  The full field list POSTed (a full replace, incl. `feed`).
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public string $channelType,
        public string $channelName,
        public ?string $pageId,
        public bool $ok,
        public string $reason,
        public ?string $detail,
        public array $subscribedFields,
        public DateTimeImmutable $checkedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'messengerResubscribeResult'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            channelType: $attributes->string('channel_type'),
            channelName: $attributes->string('channel_name'),
            pageId: $attributes->nullableString('page_id'),
            ok: $attributes->bool('ok'),
            reason: $attributes->string('reason'),
            detail: $attributes->nullableString('detail'),
            subscribedFields: $attributes->strings('subscribed_fields'),
            checkedAt: $attributes->dateTime('checked_at'),
            raw: $data,
        );
    }
}
