<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Count by opt-in method
 *
 * @see https://api.sendseven.com/api/v1/docs (schema OptInMethodCount)
 */
final readonly class OptInMethodCount extends Data
{
    /**
     * @param  int  $count  Number of subscriptions via this method
     * @param  string  $method  Opt-in method (widget, import, api, manual, etc.)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $count,
        public string $method,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'optInMethodCount'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            count: $attributes->int('count'),
            method: $attributes->string('method'),
            raw: $data,
        );
    }
}
