<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Details of a pending email confirmation
 *
 * @see https://api.sendseven.com/api/v1/docs (schema PendingConfirmation)
 */
final readonly class PendingConfirmation extends Data
{
    /**
     * @param  string  $tokenId  Token ID
     * @param  string  $email  Email address awaiting confirmation
     * @param  DateTimeImmutable  $sentAt  When confirmation email was sent
     * @param  DateTimeImmutable  $expiresAt  When token expires
     * @param  ?string  $listName  List name if subscribing to specific list
     * @param  ?string  $category  Subscription category
     * @param  bool  $isExpired  Whether token has expired
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $tokenId,
        public string $email,
        public DateTimeImmutable $sentAt,
        public DateTimeImmutable $expiresAt,
        public ?string $listName,
        public ?string $category,
        public bool $isExpired,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'pendingConfirmation'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            tokenId: $attributes->string('token_id'),
            email: $attributes->string('email'),
            sentAt: $attributes->dateTime('sent_at'),
            expiresAt: $attributes->dateTime('expires_at'),
            listName: $attributes->nullableString('list_name'),
            category: $attributes->nullableString('category'),
            isExpired: $attributes->bool('is_expired'),
            raw: $data,
        );
    }
}
