<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * List of pending confirmations with pagination
 *
 * @see https://api.sendseven.com/api/v1/docs (schema PendingConfirmationListResponse)
 */
final readonly class PendingConfirmationList extends Data
{
    /**
     * @param  list<PendingConfirmation>  $pendingConfirmations  List of pending confirmations
     * @param  int  $total  Total number of pending confirmations
     * @param  int  $limit  Items per page
     * @param  int  $offset  Current offset
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $pendingConfirmations,
        public int $total,
        public int $limit,
        public int $offset,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'pendingConfirmationList'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            pendingConfirmations: $attributes->list('pending_confirmations', PendingConfirmation::fromArray(...)),
            total: $attributes->int('total'),
            limit: $attributes->int('limit'),
            offset: $attributes->int('offset'),
            raw: $data,
        );
    }
}
