<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from checking if user has required scopes
 *
 * @see https://api.sendseven.com/api/v1/docs (schema PermissionCheckResponse)
 */
final readonly class PermissionCheck extends Data
{
    /**
     * @param  bool  $hasAll  True if user has all required scopes
     * @param  array<array-key, mixed>  $results  Map of scope to whether user has it
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $hasAll,
        public array $results,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'permissionCheck'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            hasAll: $attributes->bool('has_all'),
            results: $attributes->array('results'),
            raw: $data,
        );
    }
}
