<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Whether ONE channel can publish authored posts, and which formats.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema PostChannelCapability)
 */
final readonly class PostChannelCapability extends Data
{
    /**
     * @param  bool  $canPublish  True when this channel type supports at least one post format.
     * @param  array<array-key, mixed>  $formats  Per-format support, e.g. `{"text": false, "image": true, ...}`.
     * @param  ?int  $maxMediaItems  Maximum media items (carousel slides) this channel accepts in one post, when the capability matrix reports it (e.g. Meta's carousel ceiling). `null` when the matrix does not advertise a limit — the adapter still enforces the hard Meta rule. Never hardcoded here; surfaced verbatim from `post_publish.post_capabilities_for_channel`.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $canPublish,
        public string $channelId,
        public string $channelName,
        public string $channelType,
        public array $formats,
        public ?string $identifier,
        public ?int $maxMediaItems,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'postChannelCapability'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            canPublish: $attributes->bool('can_publish'),
            channelId: $attributes->string('channel_id'),
            channelName: $attributes->string('channel_name'),
            channelType: $attributes->string('channel_type'),
            formats: $attributes->array('formats'),
            identifier: $attributes->nullableString('identifier'),
            maxMediaItems: $attributes->nullableInt('max_media_items'),
            raw: $data,
        );
    }
}
