<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Per-recipient reachability for THIS agent.
 *
 * reachable: false is an ANSWER, not an error. RBM returns 404 for every kind of unreachable —
 * no RCS on the device, RCS switched off, a carrier the agent is not launched on, or a tester who
 * has not accepted the invite yet — and it cannot tell them apart. So the endpoint returns 200
 * with reachable: false and a coarse reason; inventing a specific cause would be a guess presented
 * as a fact.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RcsCapabilityResponse)
 */
final readonly class RcsCapability extends Data
{
    /**
     * @param  ?bool  $cached  True when served from the Redis capability cache
     * @param  string  $checkedAt  When this answer was produced
     * @param  list<string>  $features  RBM feature strings, when Google returned any
     * @param  string  $msisdn  The probed number, normalised to E.164
     * @param  ?string  $reason  Coarse cause when unreachable: 'not_rcs_reachable' (Google's 404 — cause unknowable) or 'probe_failed' (we could not complete the call).
     * @param  ?string  $testerStatus  Allowlist status of this MSISDN after the probe, when it is one of our tester devices. A reachable probe promotes 'pending' to 'accepted' — the only acceptance signal Google gives us.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $cached,
        public ?string $carrier,
        public string $checkedAt,
        public array $features,
        public string $msisdn,
        public bool $reachable,
        public ?string $reason,
        public ?string $testerStatus,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'rcsCapability'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            cached: $attributes->nullableBool('cached'),
            carrier: $attributes->nullableString('carrier'),
            checkedAt: $attributes->string('checked_at'),
            features: $attributes->strings('features'),
            msisdn: $attributes->string('msisdn'),
            reachable: $attributes->bool('reachable'),
            reason: $attributes->nullableString('reason'),
            testerStatus: $attributes->nullableString('tester_status'),
            raw: $data,
        );
    }
}
