<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for POST /{campaign_id}/recipients/{recipient_id}/unsubscribe.
 *
 * - unsubscribed_lists is the set of the campaign's lists the contact was actively subscribed to
 * and has now been opted out of (deduped by list; empty when the campaign targets no lists, or the
 * contact was subscribed to none of them). - already_unsubscribed is True only when the contact
 * HAD subscription rows for the campaign's lists but every one was already opted out (nothing to
 * flip). It stays False when there were simply no originating lists.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RecipientUnsubscribeResponse)
 */
final readonly class RecipientUnsubscribe extends Data
{
    /**
     * @param  list<UnsubscribedListItem>  $unsubscribedLists  Lists the contact was opted out of by this action (deduped by list_id)
     * @param  ?bool  $alreadyUnsubscribed  True when the contact was already opted out of all of the campaign's lists
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $success,
        public array $unsubscribedLists,
        public ?bool $alreadyUnsubscribed,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'recipientUnsubscribe'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            success: $attributes->nullableBool('success'),
            unsubscribedLists: $attributes->list('unsubscribed_lists', UnsubscribedListItem::fromArray(...)),
            alreadyUnsubscribed: $attributes->nullableBool('already_unsubscribed'),
            raw: $data,
        );
    }
}
