<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Audience preview (and optional price) for an unsaved campaign.
 *
 * subscribed == recipient_count == the number of emails the send will actually go to. total =
 * subscribed + unsubscribed + bounced + duplicate_email_skipped_count + no_email_count.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RecipientCountResponse)
 */
final readonly class RecipientCount extends Data
{
    /**
     * @param  int  $total  Contacts matching the audience before exclusions
     * @param  int  $subscribed  Valid recipients (what the send delivers to)
     * @param  int  $unsubscribed  Excluded: opted out / complained
     * @param  int  $bounced  Excluded: hard-bounced, invalid or suppressed address
     * @param  ?int  $recipientCount  Same as subscribed
     * @param  ?int  $duplicateEmailSkippedCount  Excluded: another (older) contact has the same address
     * @param  ?int  $noEmailCount  Excluded: no usable email address
     * @param  array<array-key, mixed>  $listBreakdown  Subscribed members per target list id (before exclusions)
     * @param  array<array-key, mixed>  $subscriptionBreakdown  Subscribed members per subscription category (before exclusions)
     * @param  ?EmailCampaignCostQuote  $cost  Price quote; present when a sending method was given
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $total,
        public int $subscribed,
        public int $unsubscribed,
        public int $bounced,
        public ?int $recipientCount,
        public ?int $duplicateEmailSkippedCount,
        public ?int $noEmailCount,
        public array $listBreakdown,
        public array $subscriptionBreakdown,
        public ?EmailCampaignCostQuote $cost,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'recipientCount'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            total: $attributes->int('total'),
            subscribed: $attributes->int('subscribed'),
            unsubscribed: $attributes->int('unsubscribed'),
            bounced: $attributes->int('bounced'),
            recipientCount: $attributes->nullableInt('recipient_count'),
            duplicateEmailSkippedCount: $attributes->nullableInt('duplicate_email_skipped_count'),
            noEmailCount: $attributes->nullableInt('no_email_count'),
            listBreakdown: $attributes->array('list_breakdown'),
            subscriptionBreakdown: $attributes->array('subscription_breakdown'),
            cost: $attributes->nullableObject('cost', EmailCampaignCostQuote::fromArray(...)),
            raw: $data,
        );
    }
}
