<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from refreshing verified domains
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RefreshDomainsResponse)
 */
final readonly class RefreshDomains extends Data
{
    /**
     * @param  int  $domainCount  Number of verified domains
     * @param  bool  $success  Whether domain refresh succeeded
     * @param  string  $updatedAt  ISO8601 timestamp of update
     * @param  list<string>  $verifiedDomains  List of verified domains
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public int $domainCount,
        public bool $success,
        public string $updatedAt,
        public array $verifiedDomains,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'refreshDomains'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            domainCount: $attributes->int('domain_count'),
            success: $attributes->bool('success'),
            updatedAt: $attributes->string('updated_at'),
            verifiedDomains: $attributes->strings('verified_domains'),
            raw: $data,
        );
    }
}
