<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * One event in the replay timeline.
 *
 * The schema is loose on purpose — node_executed carries node_id / node_name / node_type /
 * summary, while message_sent / message_received carry channel / body / message_id.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ReplayEvent)
 */
final readonly class ReplayEvent extends Data
{
    /**
     * @param  ?string  $nodeName  Human-readable label of the executed node, resolved from the run's snapshotted definition (``context.definition_snapshot``) so a post-run rename doesn't change historical replays. Falls back to ``node_id`` when the snapshot lacks the node (e.g. it was added after this run). Emitted alongside ``node_type`` so the observability tab identifies WHICH node ran, not just its type.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $type,
        public ?string $ts,
        public ?string $nodeId,
        public ?string $nodeName,
        public ?string $nodeType,
        public ?string $summary,
        public ?string $status,
        public ?string $channel,
        public ?string $body,
        public ?string $messageId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'replayEvent'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            type: $attributes->string('type'),
            ts: $attributes->nullableString('ts'),
            nodeId: $attributes->nullableString('node_id'),
            nodeName: $attributes->nullableString('node_name'),
            nodeType: $attributes->nullableString('node_type'),
            summary: $attributes->nullableString('summary'),
            status: $attributes->nullableString('status'),
            channel: $attributes->nullableString('channel'),
            body: $attributes->nullableString('body'),
            messageId: $attributes->nullableString('message_id'),
            raw: $data,
        );
    }
}
