<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Current retention policy + value for the caller's tenant.
 *
 * Drives the settings UI without the frontend re-deriving product rules. allowed_options is an
 * ordered list of selectable values where 0 represents "unlimited"; the frontend maps each integer
 * to an i18n label.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RetentionPolicyResponse)
 */
final readonly class RetentionPolicy extends Data
{
    /**
     * @param  list<int>  $allowedOptions
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $allowedOptions,
        public ?int $ceiling,
        public ?int $effectiveDays,
        public int $floor,
        public bool $isApiOnly,
        public bool $isConfigurable,
        public int $messageRetentionDays,
        public string $tenantId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'retentionPolicy'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            allowedOptions: $attributes->ints('allowed_options'),
            ceiling: $attributes->nullableInt('ceiling'),
            effectiveDays: $attributes->nullableInt('effective_days'),
            floor: $attributes->int('floor'),
            isApiOnly: $attributes->bool('is_api_only'),
            isConfigurable: $attributes->bool('is_configurable'),
            messageRetentionDays: $attributes->int('message_retention_days'),
            tenantId: $attributes->string('tenant_id'),
            raw: $data,
        );
    }
}
