<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Information about a user's role assignment in a tenant
 *
 * @see https://api.sendseven.com/api/v1/docs (schema RoleAssignmentInfo)
 */
final readonly class RoleAssignmentInfo extends Data
{
    /**
     * @param  DateTimeImmutable  $assignedAt  When the role was assigned
     * @param  ?string  $assignedByUserId  User who assigned this role
     * @param  ?DateTimeImmutable  $expiresAt  When the role expires (if temporary)
     * @param  string  $roleId  RBAC role ID
     * @param  string  $roleName  RBAC role name
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public DateTimeImmutable $assignedAt,
        public ?string $assignedByUserId,
        public ?DateTimeImmutable $expiresAt,
        public string $roleId,
        public string $roleName,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'roleAssignmentInfo'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            assignedAt: $attributes->dateTime('assigned_at'),
            assignedByUserId: $attributes->nullableString('assigned_by_user_id'),
            expiresAt: $attributes->nullableDateTime('expires_at'),
            roleId: $attributes->string('role_id'),
            roleName: $attributes->string('role_name'),
            raw: $data,
        );
    }
}
