<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Enums\ChannelType;
use Reshapify\SendSeven\Enums\ScheduledSendStatus;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Wire format for a ScheduledSend row.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ScheduledSendResponse)
 */
final readonly class ScheduledSend extends Data
{
    /**
     * @param  array<array-key, mixed>  $payload
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $contactId,
        public ?string $channelId,
        public ?string $emailMailboxId,
        public ChannelType|string $channelType,
        public array $payload,
        public string $sendAt,
        public string $nextRunAt,
        public ?string $recurrenceRule,
        public ScheduledSendStatus|string $status,
        public ?string $flowRunId,
        public ?string $ruleId,
        public ?string $createdByUserId,
        public string $createdAt,
        public string $updatedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'scheduledSend'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            contactId: $attributes->string('contact_id'),
            channelId: $attributes->nullableString('channel_id'),
            emailMailboxId: $attributes->nullableString('email_mailbox_id'),
            channelType: $attributes->enum('channel_type', ChannelType::class),
            payload: $attributes->array('payload'),
            sendAt: $attributes->string('send_at'),
            nextRunAt: $attributes->string('next_run_at'),
            recurrenceRule: $attributes->nullableString('recurrence_rule'),
            status: $attributes->enum('status', ScheduledSendStatus::class),
            flowRunId: $attributes->nullableString('flow_run_id'),
            ruleId: $attributes->nullableString('rule_id'),
            createdByUserId: $attributes->nullableString('created_by_user_id'),
            createdAt: $attributes->string('created_at'),
            updatedAt: $attributes->string('updated_at'),
            raw: $data,
        );
    }
}
