<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * One publish target (IG/FB page channel) of an authored post.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ScheduledPostTargetResponse)
 */
final readonly class ScheduledPostTarget extends Data
{
    /**
     * @param  string  $channelId  The channel this target publishes to.
     * @param  ?string  $errorCode  Meta error code/subcode when this target failed.
     * @param  ?string  $errorMessage  Human-readable failure reason for this target.
     * @param  string  $id  Target id.
     * @param  ?string  $metaPostId  Meta's id for the published post (IG media id / FB `{page}_{post}`).
     * @param  ?string  $permalink  Public link to the published post.
     * @param  ?string  $publishedAt  When this target published.
     * @param  string  $status  `pending`, `publishing`, `published`, `failed` or `cancelled`.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public ?string $errorCode,
        public ?string $errorMessage,
        public string $id,
        public ?string $metaPostId,
        public ?string $permalink,
        public ?string $publishedAt,
        public string $status,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'scheduledPostTarget'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            errorCode: $attributes->nullableString('error_code'),
            errorMessage: $attributes->nullableString('error_message'),
            id: $attributes->string('id'),
            metaPostId: $attributes->nullableString('meta_post_id'),
            permalink: $attributes->nullableString('permalink'),
            publishedAt: $attributes->nullableString('published_at'),
            status: $attributes->string('status'),
            raw: $data,
        );
    }
}
