<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from granting a scope directly to a user
 *
 * @see https://api.sendseven.com/api/v1/docs (schema ScopeGrantResponse)
 */
final readonly class ScopeGrant extends Data
{
    /**
     * @param  string  $message  Success message
     * @param  string  $grantId  ID of the created scope grant
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $message,
        public string $grantId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'scopeGrant'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            message: $attributes->string('message'),
            grantId: $attributes->string('grant_id'),
            raw: $data,
        );
    }
}
