<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from knowledge base search.
 *
 * Contains AI-generated answer with citations and sources.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SearchKnowledgeResponse)
 */
final readonly class SearchKnowledge extends Data
{
    /**
     * @param  string  $answer  AI-generated answer
     * @param  list<mixed>  $citations  Citations from source documents
     * @param  string  $query  Original search query
     * @param  int  $sourceCount  Number of sources used
     * @param  list<mixed>  $sources  Source documents used for answer
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $answer,
        public array $citations,
        public string $query,
        public int $sourceCount,
        public array $sources,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'searchKnowledge'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            answer: $attributes->string('answer'),
            citations: array_values($attributes->array('citations')),
            query: $attributes->string('query'),
            sourceCount: $attributes->int('source_count'),
            sources: array_values($attributes->array('sources')),
            raw: $data,
        );
    }
}
