<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response after sending a carousel message
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SendCarouselResponse)
 */
final readonly class SendCarousel extends Data
{
    /**
     * @param  string  $id  Message UUID
     * @param  string  $conversationId  Conversation UUID
     * @param  ?string  $externalId  Platform message ID
     * @param  string  $status  Message status: pending, sent, failed
     * @param  string  $platform  Platform: whatsapp, messenger
     * @param  int  $cardsCount  Number of cards/elements sent
     * @param  ?string  $error  Error message if status is 'failed'
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $conversationId,
        public ?string $externalId,
        public string $status,
        public string $platform,
        public int $cardsCount,
        public ?string $error,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'sendCarousel'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            conversationId: $attributes->string('conversation_id'),
            externalId: $attributes->nullableString('external_id'),
            status: $attributes->string('status'),
            platform: $attributes->string('platform'),
            cardsCount: $attributes->int('cards_count'),
            error: $attributes->nullableString('error'),
            raw: $data,
        );
    }
}
