<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response from sending a Flow message
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SendFlowResponse)
 */
final readonly class SendFlow extends Data
{
    /**
     * @param  string  $conversationId  Conversation ID (new or existing)
     * @param  ?string  $externalId  WhatsApp message ID
     * @param  ?string  $flowToken  Flow token for tracking
     * @param  ?string  $messageId  Internal message ID
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $conversationId,
        public ?string $error,
        public ?string $externalId,
        public ?string $flowToken,
        public ?string $messageId,
        public bool $success,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'sendFlow'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            conversationId: $attributes->string('conversation_id'),
            error: $attributes->nullableString('error'),
            externalId: $attributes->nullableString('external_id'),
            flowToken: $attributes->nullableString('flow_token'),
            messageId: $attributes->nullableString('message_id'),
            success: $attributes->bool('success'),
            raw: $data,
        );
    }
}
