<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * GET /campaigns/{id}/send-plan: speed, batches and estimated duration.
 *
 * effective_rate_per_minute is the requested speed capped by what the campaign's channels can
 * send; rate_limited_by says which of the two decides. eta_seconds is the estimated time to send
 * every remaining recipient (excluding the time spent paused between batches).
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SendPlanResponse)
 */
final readonly class SendPlan extends Data
{
    /**
     * @param  bool  $pacingAvailable  False when send speed and batches are not available for this account yet
     * @param  ?string  $pacingUnavailableReason  Why pacing_available is false: "disabled" (not available for this account yet) or "pacer_offline" (briefly unavailable, try again shortly)
     * @param  list<SendPlanChannel>  $channels
     * @param  ?string  $rateLimitedBy  "campaign" or "channel"
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public bool $pacingAvailable,
        public ?string $pacingUnavailableReason,
        public ?int $totalRecipients,
        public ?int $remaining,
        public array $channels,
        public ?int $requestedRatePerMinute,
        public ?float $effectiveRatePerMinute,
        public ?int $batchSize,
        public ?int $batches,
        public ?int $etaSeconds,
        public ?int $etaSecondsPerBatch,
        public ?string $rateLimitedBy,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'sendPlan'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            pacingAvailable: $attributes->bool('pacing_available'),
            pacingUnavailableReason: $attributes->nullableString('pacing_unavailable_reason'),
            totalRecipients: $attributes->nullableInt('total_recipients'),
            remaining: $attributes->nullableInt('remaining'),
            channels: $attributes->list('channels', SendPlanChannel::fromArray(...)),
            requestedRatePerMinute: $attributes->nullableInt('requested_rate_per_minute'),
            effectiveRatePerMinute: $attributes->nullableFloat('effective_rate_per_minute'),
            batchSize: $attributes->nullableInt('batch_size'),
            batches: $attributes->nullableInt('batches'),
            etaSeconds: $attributes->nullableInt('eta_seconds'),
            etaSecondsPerBatch: $attributes->nullableInt('eta_seconds_per_batch'),
            rateLimitedBy: $attributes->nullableString('rate_limited_by'),
            raw: $data,
        );
    }
}
