<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * SmsPricelistRow from the SendSeven API.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SmsPricelistRow)
 */
final readonly class SmsPricelistRow extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $isSupported,
        public string $iso,
        public string $name,
        public string $platformFeeEur,
        public string $prefix,
        public string $sendsevenFeeEur,
        public string $totalPerSegmentEur,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'smsPricelistRow'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            isSupported: $attributes->nullableBool('is_supported'),
            iso: $attributes->string('iso'),
            name: $attributes->string('name'),
            platformFeeEur: $attributes->string('platform_fee_eur'),
            prefix: $attributes->string('prefix'),
            sendsevenFeeEur: $attributes->string('sendseven_fee_eur'),
            totalPerSegmentEur: $attributes->string('total_per_segment_eur'),
            raw: $data,
        );
    }
}
