<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Platform-agnostic metric snapshot. A null field means the platform (or this object type) does
 * NOT expose that metric — it is never fabricated.
 *
 * Instagram media exposes reach + engagement (total_interactions) + likes / comments / shares /
 * saves, but NOT impressions on the current API. A Facebook post/page exposes reach + impressions
 * + engagement via /insights; per-post likes/comments/shares come from a different edge and stay
 * null in Phase 1.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SocialInsightsMetrics)
 */
final readonly class SocialInsightsMetrics extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $reach,
        public ?int $impressions,
        public ?int $engagement,
        public ?int $likes,
        public ?int $comments,
        public ?int $shares,
        public ?int $saves,
        public ?int $videoViews,
        public ?int $clicks,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'socialInsightsMetrics'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            reach: $attributes->nullableInt('reach'),
            impressions: $attributes->nullableInt('impressions'),
            engagement: $attributes->nullableInt('engagement'),
            likes: $attributes->nullableInt('likes'),
            comments: $attributes->nullableInt('comments'),
            shares: $attributes->nullableInt('shares'),
            saves: $attributes->nullableInt('saves'),
            videoViews: $attributes->nullableInt('video_views'),
            clicks: $attributes->nullableInt('clicks'),
            raw: $data,
        );
    }
}
