<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * GET /comments/posts/insights/summary — aggregate insights totals.
 *
 * Totals across the tenant's comment-synced posts, for two windows. The 30-day window sums posts
 * published (posted_at) in the last 30 days; the all-time window sums every non-deleted post.
 * Because per-post insights are Meta LIFETIME totals, the window selects WHICH posts are summed,
 * not a daily series.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SocialPostInsightsSummaryResponse)
 */
final readonly class SocialPostInsightsSummary extends Data
{
    /**
     * @param  ?string  $lastRefreshedAt  The most recent ``insights_refreshed_at`` across the tenant's posts — how fresh the freshest number in this summary is. Null when no post has ever been refreshed.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public SocialPostInsightsWindow $last30Days,
        public SocialPostInsightsWindow $allTime,
        public ?string $lastRefreshedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'socialPostInsightsSummary'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            last30Days: $attributes->object('last_30_days', SocialPostInsightsWindow::fromArray(...)),
            allTime: $attributes->object('all_time', SocialPostInsightsWindow::fromArray(...)),
            lastRefreshedAt: $attributes->nullableString('last_refreshed_at'),
            raw: $data,
        );
    }
}
