<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Insights for one published target (one channel) of an authored post.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SocialInsightsTarget)
 */
final readonly class SocialInsightsTarget extends Data
{
    /**
     * @param  ?bool  $authorized  False when the connection lacks the insights permission — the frontend should prompt a reconnect. See `error_code`.
     * @param  string  $channelId  The channel this target published to.
     * @param  ?string  $errorCode  `insights_not_authorized` (reconnect to grant insights), `insights_unavailable` (Meta has no insights for this object), `insights_unsupported_platform`, or `insights_error`. Null on success.
     * @param  ?string  $lastRefreshedAt  When this target's cached numbers were last refreshed from Meta. Null if this target has never been cached.
     * @param  ?string  $message  Human-readable detail when `error_code` is set.
     * @param  ?string  $objectId  Meta's id read (IG media id / FB `{page}_{post}`).
     * @param  string  $platform  `instagram` or `messenger`.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $authorized,
        public string $channelId,
        public ?string $errorCode,
        public ?string $lastRefreshedAt,
        public ?string $message,
        public ?SocialInsightsMetrics $metrics,
        public ?string $objectId,
        public string $platform,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'socialInsightsTarget'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            authorized: $attributes->nullableBool('authorized'),
            channelId: $attributes->string('channel_id'),
            errorCode: $attributes->nullableString('error_code'),
            lastRefreshedAt: $attributes->nullableString('last_refreshed_at'),
            message: $attributes->nullableString('message'),
            metrics: $attributes->nullableObject('metrics', SocialInsightsMetrics::fromArray(...)),
            objectId: $attributes->nullableString('object_id'),
            platform: $attributes->string('platform'),
            raw: $data,
        );
    }
}
