<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * POST /comments/posts/{post_id}/insights/refresh — one post's fresh insights.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SocialPostInsightsRefreshResponse)
 */
final readonly class SocialPostInsightsRefresh extends Data
{
    /**
     * @param  string  $postId  Our post id.
     * @param  SocialPostInsights  $insights  The freshly-refreshed (and re-cached) insights for the post.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $postId,
        public SocialPostInsights $insights,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'socialPostInsightsRefresh'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            postId: $attributes->string('post_id'),
            insights: $attributes->object('insights', SocialPostInsights::fromArray(...)),
            raw: $data,
        );
    }
}
