<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Summed insights across a set of comment-synced posts (one time window).
 *
 * Per-post insights are Meta LIFETIME totals, so a window filters WHICH posts are summed, NOT a
 * per-day series — the totals are lifetime numbers for the posts in scope. Each metric sums only
 * the non-null cached values (so a metric a platform never exposes never distorts the total); a
 * metric is null only when NO post in scope has a value for it. post_count is how many posts have
 * cached insights and thus contributed.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SocialPostInsightsWindow)
 */
final readonly class SocialPostInsightsWindow extends Data
{
    /**
     * @param  ?int  $postCount  Posts in this window that have cached insights (``insights_refreshed_at`` set) and therefore contributed to the totals above.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $reach,
        public ?int $impressions,
        public ?int $engagement,
        public ?int $likes,
        public ?int $comments,
        public ?int $shares,
        public ?int $saves,
        public ?int $videoViews,
        public ?int $clicks,
        public ?int $postCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'socialPostInsightsWindow'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            reach: $attributes->nullableInt('reach'),
            impressions: $attributes->nullableInt('impressions'),
            engagement: $attributes->nullableInt('engagement'),
            likes: $attributes->nullableInt('likes'),
            comments: $attributes->nullableInt('comments'),
            shares: $attributes->nullableInt('shares'),
            saves: $attributes->nullableInt('saves'),
            videoViews: $attributes->nullableInt('video_views'),
            clicks: $attributes->nullableInt('clicks'),
            postCount: $attributes->nullableInt('post_count'),
            raw: $data,
        );
    }
}
