<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Schema for subscription statistics by list
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SubscriptionStatsResponse)
 */
final readonly class SubscriptionStats extends Data
{
    /**
     * @param  list<ChannelStats>  $channels
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $channels,
        public string $listId,
        public string $listName,
        public int $totalSubscriptions,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'subscriptionStats'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channels: $attributes->list('channels', ChannelStats::fromArray(...)),
            listId: $attributes->string('list_id'),
            listName: $attributes->string('list_name'),
            totalSubscriptions: $attributes->int('total_subscriptions'),
            raw: $data,
        );
    }
}
