<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * A single opt-in or opt-out event derived from a subscription's current state.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SubscriptionActivityItem)
 */
final readonly class SubscriptionActivityItem extends Data
{
    /**
     * @param  ?LastMessageInList  $lastMessageInList  Populated only for unsubscribed events; null for subscribed events
     * @param  string  $occurredAt  ISO 8601 (Z)
     * @param  ?string  $unsubscribeMethod  link/keyword/manual/bounce/complaint/api; null for subscribed events
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelType,
        public string $contactId,
        public ?string $contactName,
        public string $event,
        public ?LastMessageInList $lastMessageInList,
        public string $occurredAt,
        public ?string $unsubscribeMethod,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'subscriptionActivityItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelType: $attributes->string('channel_type'),
            contactId: $attributes->string('contact_id'),
            contactName: $attributes->nullableString('contact_name'),
            event: $attributes->string('event'),
            lastMessageInList: $attributes->nullableObject('last_message_in_list', LastMessageInList::fromArray(...)),
            occurredAt: $attributes->string('occurred_at'),
            unsubscribeMethod: $attributes->nullableString('unsubscribe_method'),
            raw: $data,
        );
    }
}
