<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response when marking a suggestion as accepted.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SuggestionAcceptResponse)
 */
final readonly class SuggestionAccept extends Data
{
    /**
     * @param  ?string  $aiAnswerEventId  AI answer event marked as accepted, if one was resolved
     * @param  string  $message  Success message
     * @param  string  $suggestionId  ID of accepted suggestion
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $aiAnswerEventId,
        public string $message,
        public string $suggestionId,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'suggestionAccept'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            aiAnswerEventId: $attributes->nullableString('ai_answer_event_id'),
            message: $attributes->string('message'),
            suggestionId: $attributes->string('suggestion_id'),
            raw: $data,
        );
    }
}
