<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Result of a posts sync — how many posts were seen and how many were new.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema SyncPostsResponse)
 */
final readonly class SyncPosts extends Data
{
    /**
     * @param  ?int  $created  Of the synced posts, how many did not exist before this call.
     * @param  ?int  $synced  Posts read from Meta and upserted (created OR refreshed), summed across every channel touched.
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $created,
        public ?int $synced,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'syncPosts'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            created: $attributes->nullableInt('created'),
            synced: $attributes->nullableInt('synced'),
            raw: $data,
        );
    }
}
