<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for Telegram bot profile
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TelegramProfileResponse)
 */
final readonly class TelegramProfile extends Data
{
    /**
     * @param  list<TelegramBotCommand>  $commands
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?bool $canJoinGroups,
        public ?bool $canReadAllGroupMessages,
        public array $commands,
        public ?string $description,
        public ?string $displayName,
        public ?string $name,
        public ?string $shortDescription,
        public ?bool $supportsInlineQueries,
        public ?string $username,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'telegramProfile'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            canJoinGroups: $attributes->nullableBool('can_join_groups'),
            canReadAllGroupMessages: $attributes->nullableBool('can_read_all_group_messages'),
            commands: $attributes->list('commands', TelegramBotCommand::fromArray(...)),
            description: $attributes->nullableString('description'),
            displayName: $attributes->nullableString('display_name'),
            name: $attributes->nullableString('name'),
            shortDescription: $attributes->nullableString('short_description'),
            supportsInlineQueries: $attributes->nullableBool('supports_inline_queries'),
            username: $attributes->nullableString('username'),
            raw: $data,
        );
    }
}
