<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * WhatsApp template button
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TemplateButton)
 */
final readonly class TemplateButton extends Data
{
    /**
     * @param  ?string  $example  Example value for variable URL
     * @param  ?string  $phoneNumber  Phone number for PHONE_NUMBER buttons
     * @param  ?string  $text  Button text. Required for every type EXCEPT `REQUEST_CONTACT_INFO`, whose label is fixed by Meta and filled in automatically.
     * @param  string  $type  Button type: QUICK_REPLY, URL, PHONE_NUMBER, COPY_CODE, REQUEST_CONTACT_INFO
     * @param  ?string  $url  URL for URL buttons
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $example,
        public ?string $phoneNumber,
        public ?string $text,
        public string $type,
        public ?string $url,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'templateButton'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            example: $attributes->nullableString('example'),
            phoneNumber: $attributes->nullableString('phone_number'),
            text: $attributes->nullableString('text'),
            type: $attributes->string('type'),
            url: $attributes->nullableString('url'),
            raw: $data,
        );
    }
}
