<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response model for a ticket summary stored in knowledge base.
 *
 * This represents tickets that have been summarized and uploaded to the Vertex AI RAG Corpus for
 * similarity search.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TicketSummaryResponse)
 */
final readonly class TicketSummary extends Data
{
    /**
     * @param  ?string  $aiSummary  AI-generated summary
     * @param  ?DateTimeImmutable  $closedAt  ISO datetime when ticket was closed
     * @param  ?string  $contactId  Related contact ID
     * @param  string  $conversationId  Related conversation ID
     * @param  ?DateTimeImmutable  $createdAt  ISO datetime when ticket was created
     * @param  ?string  $geminiDocumentName  Vertex AI RAG Corpus reference
     * @param  string  $id  Unique identifier (UUID)
     * @param  ?string  $resolutionSummary  How it was resolved
     * @param  ?string  $sentimentAnalysis  Customer sentiment
     * @param  ?string  $subject  Ticket subject
     * @param  ?DateTimeImmutable  $summarizedAt  ISO datetime when AI summary was generated
     * @param  list<string>  $tags  AI-generated tags
     * @param  string  $tenantId  Tenant this resource belongs to
     * @param  ?string  $userIntent  What the user wanted
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $aiSummary,
        public ?DateTimeImmutable $closedAt,
        public ?string $contactId,
        public string $conversationId,
        public ?DateTimeImmutable $createdAt,
        public ?string $geminiDocumentName,
        public string $id,
        public ?string $resolutionSummary,
        public ?string $sentimentAnalysis,
        public ?string $subject,
        public ?DateTimeImmutable $summarizedAt,
        public array $tags,
        public string $tenantId,
        public ?string $userIntent,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'ticketSummary'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            aiSummary: $attributes->nullableString('ai_summary'),
            closedAt: $attributes->nullableDateTime('closed_at'),
            contactId: $attributes->nullableString('contact_id'),
            conversationId: $attributes->string('conversation_id'),
            createdAt: $attributes->nullableDateTime('created_at'),
            geminiDocumentName: $attributes->nullableString('gemini_document_name'),
            id: $attributes->string('id'),
            resolutionSummary: $attributes->nullableString('resolution_summary'),
            sentimentAnalysis: $attributes->nullableString('sentiment_analysis'),
            subject: $attributes->nullableString('subject'),
            summarizedAt: $attributes->nullableDateTime('summarized_at'),
            tags: $attributes->strings('tags'),
            tenantId: $attributes->string('tenant_id'),
            userIntent: $attributes->nullableString('user_intent'),
            raw: $data,
        );
    }
}
