<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response time and resolution time metrics over time for charting.
 *
 * Returned by GET /api/v1/analytics/time-metrics
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TimeMetricsOverTimeResponse)
 */
final readonly class TimeMetricsOverTime extends Data
{
    /**
     * @param  list<TimeMetricPoint>  $timeline  Daily averages for charting
     * @param  array<array-key, mixed>  $byChannel  Per-channel daily averages
     * @param  string  $periodStart  Start of the reporting period (ISO format)
     * @param  string  $periodEnd  End of the reporting period (ISO format)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public array $timeline,
        public array $byChannel,
        public string $periodStart,
        public string $periodEnd,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'timeMetricsOverTime'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            timeline: $attributes->list('timeline', TimeMetricPoint::fromArray(...)),
            byChannel: $attributes->array('by_channel'),
            periodStart: $attributes->string('period_start'),
            periodEnd: $attributes->string('period_end'),
            raw: $data,
        );
    }
}
