<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Time metrics at a specific point in time
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TimeMetricPoint)
 */
final readonly class TimeMetricPoint extends Data
{
    /**
     * @param  string  $date  Date in YYYY-MM-DD format
     * @param  ?float  $resolutionHours  Average resolution time in hours
     * @param  ?float  $responseMinutes  Average response time in minutes
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $date,
        public ?float $resolutionHours,
        public ?float $responseMinutes,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'timeMetricPoint'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            date: $attributes->string('date'),
            resolutionHours: $attributes->nullableFloat('resolution_hours'),
            responseMinutes: $attributes->nullableFloat('response_minutes'),
            raw: $data,
        );
    }
}
