<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Top performing tracked link
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TopPerformingLink)
 */
final readonly class TopPerformingLink extends Data
{
    /**
     * @param  string  $shortCode  Short code for the link
     * @param  string  $originalUrl  Original destination URL
     * @param  int  $clicks  Total click count
     * @param  ?string  $label  Link label/name
     * @param  ?string  $firstClickAt  Timestamp of first click (ISO format)
     * @param  ?string  $lastClickAt  Timestamp of last click (ISO format)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $shortCode,
        public string $originalUrl,
        public int $clicks,
        public ?string $label,
        public ?string $firstClickAt,
        public ?string $lastClickAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'topPerformingLink'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            shortCode: $attributes->string('short_code'),
            originalUrl: $attributes->string('original_url'),
            clicks: $attributes->int('clicks'),
            label: $attributes->nullableString('label'),
            firstClickAt: $attributes->nullableString('first_click_at'),
            lastClickAt: $attributes->nullableString('last_click_at'),
            raw: $data,
        );
    }
}
