<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Summary item for list view
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TrackedLinkListItem)
 */
final readonly class TrackedLinkListItem extends Data
{
    /**
     * @param  list<string>  $tags
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $shortCode,
        public string $shortUrl,
        public string $originalUrl,
        public string $featureType,
        public ?string $customAlias,
        public ?string $label,
        public array $tags,
        public DateTimeImmutable $createdAt,
        public ?DateTimeImmutable $expiresAt,
        public bool $isActive,
        public int $clickCount,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'trackedLinkListItem'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            shortCode: $attributes->string('short_code'),
            shortUrl: $attributes->string('short_url'),
            originalUrl: $attributes->string('original_url'),
            featureType: $attributes->string('feature_type'),
            customAlias: $attributes->nullableString('custom_alias'),
            label: $attributes->nullableString('label'),
            tags: $attributes->strings('tags'),
            createdAt: $attributes->dateTime('created_at'),
            expiresAt: $attributes->nullableDateTime('expires_at'),
            isActive: $attributes->bool('is_active'),
            clickCount: $attributes->int('click_count'),
            raw: $data,
        );
    }
}
