<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response with translated message
 *
 * @see https://api.sendseven.com/api/v1/docs (schema TranslateMessageResponse)
 */
final readonly class TranslateMessage extends Data
{
    /**
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $language,
        public string $messageId,
        public string $original,
        public string $translated,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'translateMessage'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            language: $attributes->string('language'),
            messageId: $attributes->string('message_id'),
            original: $attributes->string('original'),
            translated: $attributes->string('translated'),
            raw: $data,
        );
    }
}
