<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Unsubscribe statistics for reporting
 *
 * @see https://api.sendseven.com/api/v1/docs (schema UnsubscribeStats)
 */
final readonly class UnsubscribeStats extends Data
{
    /**
     * @param  list<string>  $commonReasons  Most common unsubscribe reasons
     * @param  array<array-key, mixed>  $methods  Breakdown by unsubscribe method
     * @param  int  $periodDays  Number of days analyzed
     * @param  int  $totalUnsubscribes  Total unsubscribes in period
     * @param  ?float  $unsubscribeRatePercent  Unsubscribe rate as percentage (if campaign context available)
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $campaignId,
        public array $commonReasons,
        public ?string $emailCampaignId,
        public array $methods,
        public int $periodDays,
        public int $totalUnsubscribes,
        public ?float $unsubscribeRatePercent,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'unsubscribeStats'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            campaignId: $attributes->nullableString('campaign_id'),
            commonReasons: $attributes->strings('common_reasons'),
            emailCampaignId: $attributes->nullableString('email_campaign_id'),
            methods: $attributes->array('methods'),
            periodDays: $attributes->int('period_days'),
            totalUnsubscribes: $attributes->int('total_unsubscribes'),
            unsubscribeRatePercent: $attributes->nullableFloat('unsubscribe_rate_percent'),
            raw: $data,
        );
    }
}
