<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Current per-user inbox-access settings.
 *
 * Returned by GET /users/{user_id}/inbox-access.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema UserInboxAccessResponse)
 */
final readonly class UserInboxAccessResponse extends Data
{
    /**
     * @param  list<string>  $inboxIds
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $mode,
        public array $inboxIds,
        public ?string $contactHistoryVisibility,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'userInboxAccessResponse'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            mode: $attributes->string('mode'),
            inboxIds: $attributes->strings('inbox_ids'),
            contactHistoryVisibility: $attributes->nullableString('contact_history_visibility'),
            raw: $data,
        );
    }
}
