<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response containing a user's effective scopes
 *
 * @see https://api.sendseven.com/api/v1/docs (schema UserEffectiveScopesResponse)
 */
final readonly class UserEffectiveScopes extends Data
{
    /**
     * @param  string  $userId  User UUID
     * @param  string  $tenantId  Tenant UUID
     * @param  list<string>  $scopes  List of effective scopes
     * @param  int  $total  Total number of scopes
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $userId,
        public string $tenantId,
        public array $scopes,
        public int $total,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'userEffectiveScopes'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            userId: $attributes->string('user_id'),
            tenantId: $attributes->string('tenant_id'),
            scopes: $attributes->strings('scopes'),
            total: $attributes->int('total'),
            raw: $data,
        );
    }
}
