<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for user signature
 *
 * @see https://api.sendseven.com/api/v1/docs (schema UserSignatureResponse)
 */
final readonly class UserSignature extends Data
{
    /**
     * @param  string  $id  Signature ID
     * @param  string  $tenantId  Tenant ID
     * @param  string  $userId  User ID who owns this signature
     * @param  string  $contentHtml  HTML content
     * @param  ?string  $contentText  Plain text version
     * @param  bool  $isActive  Whether this signature is active
     * @param  string  $createdAt  When the signature was created
     * @param  string  $updatedAt  When the signature was last updated
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $tenantId,
        public string $userId,
        public string $contentHtml,
        public ?string $contentText,
        public bool $isActive,
        public string $createdAt,
        public string $updatedAt,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'userSignature'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            tenantId: $attributes->string('tenant_id'),
            userId: $attributes->string('user_id'),
            contentHtml: $attributes->string('content_html'),
            contentText: $attributes->nullableString('content_text'),
            isActive: $attributes->bool('is_active'),
            createdAt: $attributes->string('created_at'),
            updatedAt: $attributes->string('updated_at'),
            raw: $data,
        );
    }
}
