<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use DateTimeImmutable;
use Reshapify\SendSeven\Enums\UserRole;
use Reshapify\SendSeven\Support\Attributes;

/**
 * Response for a tenant the user belongs to.
 *
 * Used in GET /users/me/tenants endpoint.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema UserTenantResponse)
 */
final readonly class UserTenant extends Data
{
    /**
     * @param  string  $id  Tenant ID
     * @param  string  $name  Tenant name
     * @param  ?string  $slug  Tenant URL slug
     * @param  UserRole|string  $role  User's role in this tenant
     * @param  DateTimeImmutable  $joinedAt  When user joined this tenant
     * @param  ?bool  $isTrial  Whether tenant is on trial
     * @param  ?DateTimeImmutable  $trialEndsAt  When trial ends
     * @param  ?string  $billingAccountId  Associated billing account ID
     * @param  ?string  $defaultCountry  Tenant default country (ISO-3166-1 alpha-2) or null
     * @param  ?string  $defaultTimezone  Tenant default IANA timezone (e.g. 'Europe/Berlin')
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $id,
        public string $name,
        public ?string $slug,
        public UserRole|string $role,
        public DateTimeImmutable $joinedAt,
        public ?bool $isTrial,
        public ?DateTimeImmutable $trialEndsAt,
        public ?string $billingAccountId,
        public ?string $defaultCountry,
        public ?string $defaultTimezone,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'userTenant'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            id: $attributes->string('id'),
            name: $attributes->string('name'),
            slug: $attributes->nullableString('slug'),
            role: $attributes->enum('role', UserRole::class),
            joinedAt: $attributes->dateTime('joined_at'),
            isTrial: $attributes->nullableBool('is_trial'),
            trialEndsAt: $attributes->nullableDateTime('trial_ends_at'),
            billingAccountId: $attributes->nullableString('billing_account_id'),
            defaultCountry: $attributes->nullableString('default_country'),
            defaultTimezone: $attributes->nullableString('default_timezone'),
            raw: $data,
        );
    }
}
