<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Schema for a single webhook event type
 *
 * @see https://api.sendseven.com/api/v1/docs (schema WebhookEventTypeSchema)
 */
final readonly class WebhookEventTypeSchema extends Data
{
    /**
     * @param  string  $event  Event type identifier (e.g., 'message.received')
     * @param  string  $description  Human-readable description of the event
     * @param  string  $category  Event category (e.g., 'message', 'conversation')
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $event,
        public string $description,
        public string $category,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'webhookEventTypeSchema'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            event: $attributes->string('event'),
            description: $attributes->string('description'),
            category: $attributes->string('category'),
            raw: $data,
        );
    }
}
