<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Response schema for WhatsApp Business Profile
 *
 * @see https://api.sendseven.com/api/v1/docs (schema WhatsAppProfileResponse)
 */
final readonly class WhatsAppProfile extends Data
{
    /**
     * @param  list<string>  $websites
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?string $about,
        public ?string $address,
        public ?string $description,
        public ?string $email,
        public ?string $profilePictureUrl,
        public ?string $vertical,
        public array $websites,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'whatsAppProfile'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            about: $attributes->nullableString('about'),
            address: $attributes->nullableString('address'),
            description: $attributes->nullableString('description'),
            email: $attributes->nullableString('email'),
            profilePictureUrl: $attributes->nullableString('profile_picture_url'),
            vertical: $attributes->nullableString('vertical'),
            websites: $attributes->strings('websites'),
            raw: $data,
        );
    }
}
