<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Result of claiming or changing a WhatsApp business username.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema WhatsAppUsernameUpdateResponse)
 */
final readonly class WhatsAppUsernameUpdate extends Data
{
    /**
     * @param  string  $channelId  The channel's ID
     * @param  string  $message  Human-readable status message
     * @param  ?string  $status  'approved' or 'reserved'
     * @param  bool  $success  Whether WhatsApp accepted the username
     * @param  ?string  $username  The username that was set
     * @param  ?string  $waMeUrl  Short link for the username
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public string $message,
        public ?string $status,
        public bool $success,
        public ?string $username,
        public ?string $waMeUrl,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'whatsAppUsernameUpdate'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            message: $attributes->string('message'),
            status: $attributes->nullableString('status'),
            success: $attributes->bool('success'),
            username: $attributes->nullableString('username'),
            waMeUrl: $attributes->nullableString('wa_me_url'),
            raw: $data,
        );
    }
}
