<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * The username currently held by a WhatsApp channel's phone number.
 *
 * @see https://api.sendseven.com/api/v1/docs (schema WhatsAppUsernameResponse)
 */
final readonly class WhatsAppUsername extends Data
{
    /**
     * @param  string  $channelId  The channel's ID
     * @param  ?string  $status  'approved' (live) or 'reserved' (accepted, still propagating)
     * @param  list<string>  $suggestions  Available usernames suggested by WhatsApp (empty if unavailable)
     * @param  ?string  $username  Current username, or null if none is claimed
     * @param  ?string  $waMeUrl  Short link customers can use to start a chat
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public string $channelId,
        public ?string $status,
        public array $suggestions,
        public ?string $username,
        public ?string $waMeUrl,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'whatsAppUsername'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            channelId: $attributes->string('channel_id'),
            status: $attributes->nullableString('status'),
            suggestions: $attributes->strings('suggestions'),
            username: $attributes->nullableString('username'),
            waMeUrl: $attributes->nullableString('wa_me_url'),
            raw: $data,
        );
    }
}
