<?php

declare(strict_types=1);

namespace Reshapify\SendSeven\Data;

// This file is @generated by bin/generate from SendSeven's OpenAPI spec. Do not edit it:
// change the generator or openapi/patches, then regenerate.

use Reshapify\SendSeven\Support\Attributes;

/**
 * Aggregated analytics totals
 *
 * @see https://api.sendseven.com/api/v1/docs (schema WidgetAnalyticsTotals)
 */
final readonly class WidgetAnalyticsTotals extends Data
{
    /**
     * @param  ?int  $views  Total views
     * @param  ?int  $interactions  Total interactions
     * @param  ?int  $channelClicks  Total channel clicks
     * @param  ?int  $liveChatStarts  Live chat sessions started
     * @param  ?int  $liveChatMessages  Live chat messages sent
     * @param  ?int  $newsletterSubmits  Newsletter form submissions
     * @param  ?int  $pushSubscribes  Push notification subscriptions
     * @param  array<array-key, mixed>  $raw
     */
    public function __construct(
        public ?int $views,
        public ?int $interactions,
        public ?int $channelClicks,
        public ?int $liveChatStarts,
        public ?int $liveChatMessages,
        public ?int $newsletterSubmits,
        public ?int $pushSubscribes,
        array $raw = [],
    ) {
        parent::__construct($raw);
    }

    /**
     * @param  array<array-key, mixed>  $data
     */
    public static function fromArray(array $data, string $path = 'widgetAnalyticsTotals'): self
    {
        $attributes = new Attributes($data, $path);

        return new self(
            views: $attributes->nullableInt('views'),
            interactions: $attributes->nullableInt('interactions'),
            channelClicks: $attributes->nullableInt('channel_clicks'),
            liveChatStarts: $attributes->nullableInt('live_chat_starts'),
            liveChatMessages: $attributes->nullableInt('live_chat_messages'),
            newsletterSubmits: $attributes->nullableInt('newsletter_submits'),
            pushSubscribes: $attributes->nullableInt('push_subscribes'),
            raw: $data,
        );
    }
}
